<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validation;

use Prefabcortex\UpsTimeInTransit\Exception\ApiException;
use RuntimeException;
use Symfony\Component\Validator\ConstraintViolationListInterface;

use function sprintf;

/**
 * A document that does not satisfy the constraints its schema declares — out of an operation, a
 * request body checked before it is sent. An operation checks only under `ValidationMode::Strict`;
 * under `Lax`, the default, the body is sent as its model holds it.
 *
 * Carries {@see ApiException} because it leaves an operation on the same path and in the same
 * `@throws` list as the operation exceptions beside it, so the one catch the README documents
 * covers it.
 *
 * It carries no response accessors and so is not a `ResponseException`: where it is raised there is
 * no response. A *response* that breaks its constraints raises `ResponseValidationException`, a
 * sibling rather than a subclass on purpose: a catch of this class means "nothing was sent".
 */
final class ValidationException extends RuntimeException implements ApiException
{
    public function __construct(private readonly ConstraintViolationListInterface $violationList)
    {
        parent::__construct(sprintf('Model validation failed with %d errors.', $violationList->count()), 400);
    }

    public function getViolationList(): ConstraintViolationListInterface
    {
        return $this->violationList;
    }
}
