<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validation;

use Symfony\Component\Validator\Constraint;
use Symfony\Component\Validator\Validation;

/**
 * Part of the package's public contract: a caller validating data against a model's rules uses it,
 * with the model's `…Constraint::constraints()` — the operations use it the same way.
 */
trait ValidatorTrait
{
    /**
     * @param array<array-key, mixed> $data
     * @param list<Constraint>        $constraints
     *
     * @throws ValidationException
     */
    final protected function validate(array $data, array $constraints): void
    {
        $validator = Validation::createValidator();
        $violations = $validator->validate($data, $constraints);
        if ($violations->count() > 0) {
            throw new ValidationException($violations);
        }
    }
}
