<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Authentication;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;
use Psr\Http\Message\RequestInterface;

use function array_diff;
use function array_map;
use function count;
use function implode;
use function in_array;
use function sprintf;

/**
 * The authenticators a client was built with, and the rule for choosing among them.
 *
 * An operation states its security requirements as alternatives: a list of scheme-name sets, any
 * one of which is sufficient. This applies an alternative whose schemes are all covered by a
 * registered authenticator, which is what "OR between entries, AND within one" means in an OpenAPI
 * `security` block — of several, the one using most of them, the first where they tie. A request
 * whose requirements none of the registered authenticators satisfy goes out unsigned — the server,
 * not the client, decides what that is worth.
 *
 * That rule stays quiet: a description may name a scheme this package generates no authenticator
 * for (`openIdConnect`, `mutualTLS`), and its caller signs that part in their own PSR-18 client.
 * From inside here, "signed elsewhere" and "forgotten" look exactly alike. An authenticator for a
 * scheme no operation requires is another matter — no request would ever apply it, so it is refused
 * when the registry is built.
 *
 * To register several schemes for one request, call the factory the client emits for that
 * requirement, or `Client::withAuthenticators()`.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class AuthenticatorRegistry
{
    /**
     * @param list<Authenticator> $authenticators
     * @param list<string>        $requiredSchemes every scheme an operation of the package requires
     *
     * @throws UnsupportedValueException when an authenticator is for a scheme none of them is
     */
    public function __construct(private array $authenticators, array $requiredSchemes)
    {
        foreach ($authenticators as $authenticator) {
            $scheme = $authenticator->getSecuritySchemeName();
            if (!in_array($scheme, $requiredSchemes, true)) {
                throw new UnsupportedValueException(
                    sprintf(
                        '%s signs for the security scheme "%s", which no operation of this API requires (%s), so no request would ever apply it. To sign every request your own way, pass an HTTP client that does so to ClientConfig::withHttpClient().',
                        $authenticator::class,
                        $scheme,
                        [] === $requiredSchemes ? 'its description declares none' : 'they require ' . implode(
                            ', ',
                            array_map(static fn (string $name): string => '"' . $name . '"', $requiredSchemes),
                        ),
                    ),
                );
            }
        }
    }

    /** @param list<list<string>> $securityRequirements alternatives, each a set of scheme names */
    public function authenticate(RequestInterface $request, array $securityRequirements): RequestInterface
    {
        $registeredSchemes = array_map(
            static fn (Authenticator $authenticator): string => $authenticator->getSecuritySchemeName(),
            $this->authenticators,
        );
        // Of the alternatives the registered authenticators satisfy, the one that uses most of them;
        // the first of those where several do. A client built with two credentials for an API that
        // takes either alone or both together sends both, whichever the description lists first.
        $chosen = [];
        foreach ($securityRequirements as $requiredSchemes) {
            if (
                [] === array_diff($requiredSchemes, $registeredSchemes)
                && ([] === $chosen || count($requiredSchemes) > count($chosen[0]))
            ) {
                $chosen = [$requiredSchemes];
            }
        }
        foreach ($chosen as $requiredSchemes) {
            foreach ($this->authenticators as $authenticator) {
                if (in_array($authenticator->getSecuritySchemeName(), $requiredSchemes, true)) {
                    $request = $authenticator->authenticate($request);
                }
            }
        }

        return $request;
    }
}
