<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Authentication;

use InvalidArgumentException;
use Override;
use Psr\Http\Message\RequestInterface;
use SensitiveParameter;

use function sprintf;

final readonly class OAuth2Authentication implements Authenticator
{
    public function __construct(#[SensitiveParameter] private string $token)
    {
    }

    /** @throws InvalidArgumentException */
    #[Override]
    public function authenticate(RequestInterface $request): RequestInterface
    {
        $header = sprintf('Bearer %s', $this->token);
        $request = $request->withHeader('Authorization', $header);

        return $request;
    }

    #[Override]
    public function getSecuritySchemeName(): string
    {
        return 'OAuth2';
    }

    /**
     * What `print_r()` and `var_dump()` show of this object: the credential is redacted.
     *
     * `var_export()` and `serialize()` do not ask this method and still read the value.
     *
     * @return array<string, mixed>
     */
    public function __debugInfo(): array
    {
        return ['token' => '[redacted]'];
    }
}
