<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class CandidateAddress implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $countryCode
     * @param Option<string>           $stateProvince
     * @param Option<string>           $city
     * @param Option<string>           $town
     * @param Option<string>           $postalCode
     * @param Option<string>           $postalCodeLow
     * @param Option<string>           $postalCodeHigh
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $countryName,
        private Option $countryCode,
        private Option $stateProvince,
        private Option $city,
        private Option $town,
        private Option $postalCode,
        private Option $postalCodeLow,
        private Option $postalCodeHigh,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $countryName): CandidateAddressBuilder
    {
        return new CandidateAddressBuilder(
            $countryName,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Spelled out country name.
     */
    public function getCountryName(): string
    {
        return $this->countryName;
    }

    /**
     * Country code, follows ISO-defined country codes.
     *
     * @return Option<string>
     */
    public function getCountryCode(): Option
    {
        return $this->countryCode;
    }

    /**
     * Present on response when candidate value has a political division 1 value available.
     *
     * @return Option<string>
     */
    public function getStateProvince(): Option
    {
        return $this->stateProvince;
    }

    /**
     * Present on response when candidate value has a political division 2 value available.
     *
     * @return Option<string>
     */
    public function getCity(): Option
    {
        return $this->city;
    }

    /**
     * Present on response when candidate value has a political division 3 value available.
     *
     * @return Option<string>
     */
    public function getTown(): Option
    {
        return $this->town;
    }

    /**
     * Present on response when candidate has a postal code value available.
     *
     * @return Option<string>
     */
    public function getPostalCode(): Option
    {
        return $this->postalCode;
    }

    /**
     * Present on response when candidate value has a postal code range value available. This is the
     * postal range low value.
     *
     * @return Option<string>
     */
    public function getPostalCodeLow(): Option
    {
        return $this->postalCodeLow;
    }

    /**
     * Present on response when candidate value has a postal code range value available. This is the
     * postal range high value.
     *
     * @return Option<string>
     */
    public function getPostalCodeHigh(): Option
    {
        return $this->postalCodeHigh;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $countryName = null;
        $countryCode = None::create();
        $stateProvince = None::create();
        $city = None::create();
        $town = None::create();
        $postalCode = None::create();
        $postalCodeLow = None::create();
        $postalCodeHigh = None::create();
        if (array_key_exists('countryName', $data)) {
            $countryNameRaw = $data['countryName'];
            if (!is_string($countryNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "countryName" must be string, got %s.', get_debug_type($countryNameRaw)),
                );
            }
            $countryName = $countryNameRaw;
        }
        if (array_key_exists('countryCode', $data) && $data['countryCode'] !== null) {
            $countryCodeRaw = $data['countryCode'];
            if (!is_string($countryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "countryCode" must be string, got %s.', get_debug_type($countryCodeRaw)),
                );
            }
            $countryCode = Some::create($countryCodeRaw);
        }
        if (array_key_exists('stateProvince', $data) && $data['stateProvince'] !== null) {
            $stateProvinceRaw = $data['stateProvince'];
            if (!is_string($stateProvinceRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "stateProvince" must be string, got %s.', get_debug_type($stateProvinceRaw)),
                );
            }
            $stateProvince = Some::create($stateProvinceRaw);
        }
        if (array_key_exists('city', $data) && $data['city'] !== null) {
            $cityRaw = $data['city'];
            if (!is_string($cityRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "city" must be string, got %s.', get_debug_type($cityRaw)),
                );
            }
            $city = Some::create($cityRaw);
        }
        if (array_key_exists('town', $data) && $data['town'] !== null) {
            $townRaw = $data['town'];
            if (!is_string($townRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "town" must be string, got %s.', get_debug_type($townRaw)),
                );
            }
            $town = Some::create($townRaw);
        }
        if (array_key_exists('postalCode', $data) && $data['postalCode'] !== null) {
            $postalCodeRaw = $data['postalCode'];
            if (!is_string($postalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "postalCode" must be string, got %s.', get_debug_type($postalCodeRaw)),
                );
            }
            $postalCode = Some::create($postalCodeRaw);
        }
        if (array_key_exists('postalCodeLow', $data) && $data['postalCodeLow'] !== null) {
            $postalCodeLowRaw = $data['postalCodeLow'];
            if (!is_string($postalCodeLowRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "postalCodeLow" must be string, got %s.', get_debug_type($postalCodeLowRaw)),
                );
            }
            $postalCodeLow = Some::create($postalCodeLowRaw);
        }
        if (array_key_exists('postalCodeHigh', $data) && $data['postalCodeHigh'] !== null) {
            $postalCodeHighRaw = $data['postalCodeHigh'];
            if (!is_string($postalCodeHighRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "postalCodeHigh" must be string, got %s.', get_debug_type($postalCodeHighRaw)),
                );
            }
            $postalCodeHigh = Some::create($postalCodeHighRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'countryName' => true,
                'countryCode' => true,
                'stateProvince' => true,
                'city' => true,
                'town' => true,
                'postalCode' => true,
                'postalCodeLow' => true,
                'postalCodeHigh' => true,
            ],
        );
        if ($countryName === null) {
            throw new MalformedDataException('Required property "countryName" is missing from the document.');
        }

        return new self(
            $countryName,
            $countryCode,
            $stateProvince,
            $city,
            $town,
            $postalCode,
            $postalCodeLow,
            $postalCodeHigh,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['countryName'] = $this->countryName;
        $countryCodeOption = $this->countryCode;
        if ($countryCodeOption->isDefined()) {
            $countryCode = $countryCodeOption->get();
            $dataArray['countryCode'] = $countryCode;
        }
        $stateProvinceOption = $this->stateProvince;
        if ($stateProvinceOption->isDefined()) {
            $stateProvince = $stateProvinceOption->get();
            $dataArray['stateProvince'] = $stateProvince;
        }
        $cityOption = $this->city;
        if ($cityOption->isDefined()) {
            $city = $cityOption->get();
            $dataArray['city'] = $city;
        }
        $townOption = $this->town;
        if ($townOption->isDefined()) {
            $town = $townOption->get();
            $dataArray['town'] = $town;
        }
        $postalCodeOption = $this->postalCode;
        if ($postalCodeOption->isDefined()) {
            $postalCode = $postalCodeOption->get();
            $dataArray['postalCode'] = $postalCode;
        }
        $postalCodeLowOption = $this->postalCodeLow;
        if ($postalCodeLowOption->isDefined()) {
            $postalCodeLow = $postalCodeLowOption->get();
            $dataArray['postalCodeLow'] = $postalCodeLow;
        }
        $postalCodeHighOption = $this->postalCodeHigh;
        if ($postalCodeHighOption->isDefined()) {
            $postalCodeHigh = $postalCodeHighOption->get();
            $dataArray['postalCodeHigh'] = $postalCodeHigh;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): CandidateAddressBuilder
    {
        return new CandidateAddressBuilder(
            $this->countryName,
            $this->countryCode,
            $this->stateProvince,
            $this->city,
            $this->town,
            $this->postalCode,
            $this->postalCodeLow,
            $this->postalCodeHigh,
            $this->additionalProperties,
        );
    }
}
