<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see CandidateAddress}.
 */
final class CandidateAddressBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $countryCode
     * @param Option<string>           $stateProvince
     * @param Option<string>           $city
     * @param Option<string>           $town
     * @param Option<string>           $postalCode
     * @param Option<string>           $postalCodeLow
     * @param Option<string>           $postalCodeHigh
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $countryName,
        private Option $countryCode,
        private Option $stateProvince,
        private Option $city,
        private Option $town,
        private Option $postalCode,
        private Option $postalCodeLow,
        private Option $postalCodeHigh,
        private array $additionalProperties,
    ) {
    }

    /**
     * Spelled out country name.
     */
    public function setCountryName(string $countryName): self
    {
        $this->countryName = $countryName;

        return $this;
    }

    /**
     * Country code, follows ISO-defined country codes.
     */
    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = Some::create($countryCode);

        return $this;
    }

    /**
     * Present on response when candidate value has a political division 1 value available.
     */
    public function setStateProvince(string $stateProvince): self
    {
        $this->stateProvince = Some::create($stateProvince);

        return $this;
    }

    /**
     * Present on response when candidate value has a political division 2 value available.
     */
    public function setCity(string $city): self
    {
        $this->city = Some::create($city);

        return $this;
    }

    /**
     * Present on response when candidate value has a political division 3 value available.
     */
    public function setTown(string $town): self
    {
        $this->town = Some::create($town);

        return $this;
    }

    /**
     * Present on response when candidate has a postal code value available.
     */
    public function setPostalCode(string $postalCode): self
    {
        $this->postalCode = Some::create($postalCode);

        return $this;
    }

    /**
     * Present on response when candidate value has a postal code range value available. This is the
     * postal range low value.
     */
    public function setPostalCodeLow(string $postalCodeLow): self
    {
        $this->postalCodeLow = Some::create($postalCodeLow);

        return $this;
    }

    /**
     * Present on response when candidate value has a postal code range value available. This is the
     * postal range high value.
     */
    public function setPostalCodeHigh(string $postalCodeHigh): self
    {
        $this->postalCodeHigh = Some::create($postalCodeHigh);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): CandidateAddress
    {
        return new CandidateAddress(
            $this->countryName,
            $this->countryCode,
            $this->stateProvince,
            $this->city,
            $this->town,
            $this->postalCode,
            $this->postalCodeLow,
            $this->postalCodeHigh,
            $this->additionalProperties,
        );
    }
}
