<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see EmsResponse}.
 */
final class EmsResponseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $serviceLevel
     * @param Option<string>           $dutyType
     * @param Option<string>           $destinationPostalCode
     * @param Option<string>           $destinationPostalCodeLow
     * @param Option<string>           $destinationPostalCodeHigh
     * @param Option<string>           $destinationStateProvince
     * @param Option<string>           $destinationCityName
     * @param Option<string>           $originPostalCode
     * @param Option<string>           $originPostalCodeLow
     * @param Option<string>           $originPostalCodeHigh
     * @param Option<string>           $originStateProvince
     * @param Option<string>           $originCityName
     * @param Option<string>           $weight
     * @param Option<string>           $weightUnitOfMeasure
     * @param Option<string>           $shipmentContentsValue
     * @param Option<string>           $shipmentContentsCurrencyCode
     * @param Option<list<Services>>   $services
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $shipDate,
        private string $shipTime,
        private string $billType,
        private string $residentialIndicator,
        private string $destinationCountryName,
        private string $destinationCountryCode,
        private string $originCountryName,
        private string $originCountryCode,
        private bool $guaranteeSuspended,
        private int $numberOfServices,
        private Option $serviceLevel,
        private Option $dutyType,
        private Option $destinationPostalCode,
        private Option $destinationPostalCodeLow,
        private Option $destinationPostalCodeHigh,
        private Option $destinationStateProvince,
        private Option $destinationCityName,
        private Option $originPostalCode,
        private Option $originPostalCodeLow,
        private Option $originPostalCodeHigh,
        private Option $originStateProvince,
        private Option $originCityName,
        private Option $weight,
        private Option $weightUnitOfMeasure,
        private Option $shipmentContentsValue,
        private Option $shipmentContentsCurrencyCode,
        private Option $services,
        private array $additionalProperties,
    ) {
    }

    /**
     * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). This date may or may not be the UPS business date.
     *
     * Valid Format: YYYY-MM-DD
     */
    public function setShipDate(string $shipDate): self
    {
        $this->shipDate = $shipDate;

        return $this;
    }

    /**
     * The time the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS).
     *
     * Valid Format: HH:MM:SS
     */
    public function setShipTime(string $shipTime): self
    {
        $this->shipTime = $shipTime;

        return $this;
    }

    /**
     * Represents the shipment type.
     *
     * Valid values: "02","03","04","07" 02 - Document 03 - Non-Document 04 - WWEF 07 - Pallet
     */
    public function setBillType(string $billType): self
    {
        $this->billType = $billType;

        return $this;
    }

    /**
     * residential Indicator that was sent in on the request.
     *
     * Valid values: "01","02"
     *
     * 01 - Residential 02 - Commercial
     */
    public function setResidentialIndicator(string $residentialIndicator): self
    {
        $this->residentialIndicator = $residentialIndicator;

        return $this;
    }

    /**
     * Destination country name value.
     */
    public function setDestinationCountryName(string $destinationCountryName): self
    {
        $this->destinationCountryName = $destinationCountryName;

        return $this;
    }

    /**
     * Destination country code, conforms to ISO-defined country codes.
     */
    public function setDestinationCountryCode(string $destinationCountryCode): self
    {
        $this->destinationCountryCode = $destinationCountryCode;

        return $this;
    }

    /**
     * Origin country name value.
     */
    public function setOriginCountryName(string $originCountryName): self
    {
        $this->originCountryName = $originCountryName;

        return $this;
    }

    /**
     * Origin country code, conforms to ISO-defined country codes.
     */
    public function setOriginCountryCode(string $originCountryCode): self
    {
        $this->originCountryCode = $originCountryCode;

        return $this;
    }

    /**
     * Returns TRUE if the shipment dates fall within a defined peak date range. When the guarantee
     * is suspended, it is suspended for all services in the response.
     *
     *   The logic for determining if guarantees are suspended applies per origin country.
     *
     * The following will be used to determine if a shipment falls within a defined peak date range:
     * shipDate (from the response), deliveryDate (from the response), server Date.
     *
     * Defined peak date range (range for when guarantees are suspended) is inclusive of start and
     * end dates.
     */
    public function setGuaranteeSuspended(bool $guaranteeSuspended): self
    {
        $this->guaranteeSuspended = $guaranteeSuspended;

        return $this;
    }

    /**
     * Number of services being returned in the services array.
     */
    public function setNumberOfServices(int $numberOfServices): self
    {
        $this->numberOfServices = $numberOfServices;

        return $this;
    }

    /**
     * Service Levels being returned.
     *
     * A = all service levels.
     *
     * Blank is the default for all Service Level values.
     */
    public function setServiceLevel(string $serviceLevel): self
    {
        $this->serviceLevel = Some::create($serviceLevel);

        return $this;
    }

    /**
     * Populated with valid duty types for international transactions only.
     *
     * Valid Duty Types: "01","02","03","04","05","06","07","08","09" 01 - Dutiable 02 - Non
     * Dutiable 03 - Low Value 04 - Courier Remission 05 - Gift 06 - Military 07 - Exception 08 -
     * Line Release 09 - Low Value
     */
    public function setDutyType(string $dutyType): self
    {
        $this->dutyType = Some::create($dutyType);

        return $this;
    }

    /**
     * The shipment destination postal code. Required for US domestic requests.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     */
    public function setDestinationPostalCode(string $destinationPostalCode): self
    {
        $this->destinationPostalCode = Some::create($destinationPostalCode);

        return $this;
    }

    /**
     * The shipment destination postal code low range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     */
    public function setDestinationPostalCodeLow(string $destinationPostalCodeLow): self
    {
        $this->destinationPostalCodeLow = Some::create($destinationPostalCodeLow);

        return $this;
    }

    /**
     * The shipment destination postal code high range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     */
    public function setDestinationPostalCodeHigh(string $destinationPostalCodeHigh): self
    {
        $this->destinationPostalCodeHigh = Some::create($destinationPostalCodeHigh);

        return $this;
    }

    /**
     * The shipment destination state or province.
     *
     * For U.S. addresses, the value will be a valid 2-Character value (per U.S. Mail Standards).
     *
     * For non-U.S. addresses the full State or Province name will be returned.
     */
    public function setDestinationStateProvince(string $destinationStateProvince): self
    {
        $this->destinationStateProvince = Some::create($destinationStateProvince);

        return $this;
    }

    /**
     * The shipment destination city.
     *
     * Required for International requests for those countries that do not utilize postal codes.
     */
    public function setDestinationCityName(string $destinationCityName): self
    {
        $this->destinationCityName = Some::create($destinationCityName);

        return $this;
    }

    /**
     * The shipment origin postal code. Required for US domestic requests.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     */
    public function setOriginPostalCode(string $originPostalCode): self
    {
        $this->originPostalCode = Some::create($originPostalCode);

        return $this;
    }

    /**
     * The shipment origin postal code low range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     */
    public function setOriginPostalCodeLow(string $originPostalCodeLow): self
    {
        $this->originPostalCodeLow = Some::create($originPostalCodeLow);

        return $this;
    }

    /**
     * The shipment origin postal code high range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     */
    public function setOriginPostalCodeHigh(string $originPostalCodeHigh): self
    {
        $this->originPostalCodeHigh = Some::create($originPostalCodeHigh);

        return $this;
    }

    /**
     * The shipment origin state or province.
     *
     * For U.S. addresses, the value will be a valid 2-Character value (per U.S. Mail Standards).
     *
     * For non-U.S. addresses the full State or Province name will be returned.
     */
    public function setOriginStateProvince(string $originStateProvince): self
    {
        $this->originStateProvince = Some::create($originStateProvince);

        return $this;
    }

    /**
     * The shipment origin city.
     *
     * Required for International requests for those countries that do not utilize postal codes.
     */
    public function setOriginCityName(string $originCityName): self
    {
        $this->originCityName = Some::create($originCityName);

        return $this;
    }

    /**
     * Shipment weight. Value is only required for international shipment.
     *
     * Defaults to 0.0
     */
    public function setWeight(string $weight): self
    {
        $this->weight = Some::create($weight);

        return $this;
    }

    /**
     * Returned on response when weight was present on the request.
     */
    public function setWeightUnitOfMeasure(string $weightUnitOfMeasure): self
    {
        $this->weightUnitOfMeasure = Some::create($weightUnitOfMeasure);

        return $this;
    }

    /**
     * Shipment contents value. Value is only required for international shipment.
     *
     * Defaults to 0.0
     */
    public function setShipmentContentsValue(string $shipmentContentsValue): self
    {
        $this->shipmentContentsValue = Some::create($shipmentContentsValue);

        return $this;
    }

    /**
     * Returned on response when shipmentContentsValue was present on the request.
     */
    public function setShipmentContentsCurrencyCode(string $shipmentContentsCurrencyCode): self
    {
        $this->shipmentContentsCurrencyCode = Some::create($shipmentContentsCurrencyCode);

        return $this;
    }

    /** @param list<Services> $services */
    public function setServices(array $services): self
    {
        $this->services = Some::create($services);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): EmsResponse
    {
        return new EmsResponse(
            $this->shipDate,
            $this->shipTime,
            $this->billType,
            $this->residentialIndicator,
            $this->destinationCountryName,
            $this->destinationCountryCode,
            $this->originCountryName,
            $this->originCountryCode,
            $this->guaranteeSuspended,
            $this->numberOfServices,
            $this->serviceLevel,
            $this->dutyType,
            $this->destinationPostalCode,
            $this->destinationPostalCodeLow,
            $this->destinationPostalCodeHigh,
            $this->destinationStateProvince,
            $this->destinationCityName,
            $this->originPostalCode,
            $this->originPostalCodeLow,
            $this->originPostalCodeHigh,
            $this->originStateProvince,
            $this->originCityName,
            $this->weight,
            $this->weightUnitOfMeasure,
            $this->shipmentContentsValue,
            $this->shipmentContentsCurrencyCode,
            $this->services,
            $this->additionalProperties,
        );
    }
}
