<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_int;
use function is_string;
use function sprintf;

final readonly class EmsResponse implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $serviceLevel
     * @param Option<string>           $dutyType
     * @param Option<string>           $destinationPostalCode
     * @param Option<string>           $destinationPostalCodeLow
     * @param Option<string>           $destinationPostalCodeHigh
     * @param Option<string>           $destinationStateProvince
     * @param Option<string>           $destinationCityName
     * @param Option<string>           $originPostalCode
     * @param Option<string>           $originPostalCodeLow
     * @param Option<string>           $originPostalCodeHigh
     * @param Option<string>           $originStateProvince
     * @param Option<string>           $originCityName
     * @param Option<string>           $weight
     * @param Option<string>           $weightUnitOfMeasure
     * @param Option<string>           $shipmentContentsValue
     * @param Option<string>           $shipmentContentsCurrencyCode
     * @param Option<list<Services>>   $services
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $shipDate,
        private string $shipTime,
        private string $billType,
        private string $residentialIndicator,
        private string $destinationCountryName,
        private string $destinationCountryCode,
        private string $originCountryName,
        private string $originCountryCode,
        private bool $guaranteeSuspended,
        private int $numberOfServices,
        private Option $serviceLevel,
        private Option $dutyType,
        private Option $destinationPostalCode,
        private Option $destinationPostalCodeLow,
        private Option $destinationPostalCodeHigh,
        private Option $destinationStateProvince,
        private Option $destinationCityName,
        private Option $originPostalCode,
        private Option $originPostalCodeLow,
        private Option $originPostalCodeHigh,
        private Option $originStateProvince,
        private Option $originCityName,
        private Option $weight,
        private Option $weightUnitOfMeasure,
        private Option $shipmentContentsValue,
        private Option $shipmentContentsCurrencyCode,
        private Option $services,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $shipDate,
        string $shipTime,
        string $billType,
        string $residentialIndicator,
        string $destinationCountryName,
        string $destinationCountryCode,
        string $originCountryName,
        string $originCountryCode,
        bool $guaranteeSuspended,
        int $numberOfServices,
    ): EmsResponseBuilder {
        return new EmsResponseBuilder(
            $shipDate,
            $shipTime,
            $billType,
            $residentialIndicator,
            $destinationCountryName,
            $destinationCountryCode,
            $originCountryName,
            $originCountryCode,
            $guaranteeSuspended,
            $numberOfServices,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). This date may or may not be the UPS business date.
     *
     * Valid Format: YYYY-MM-DD
     */
    public function getShipDate(): string
    {
        return $this->shipDate;
    }

    /**
     * The time the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS).
     *
     * Valid Format: HH:MM:SS
     */
    public function getShipTime(): string
    {
        return $this->shipTime;
    }

    /**
     * Service Levels being returned.
     *
     * A = all service levels.
     *
     * Blank is the default for all Service Level values.
     *
     * @return Option<string>
     */
    public function getServiceLevel(): Option
    {
        return $this->serviceLevel;
    }

    /**
     * Represents the shipment type.
     *
     * Valid values: "02","03","04","07" 02 - Document 03 - Non-Document 04 - WWEF 07 - Pallet
     */
    public function getBillType(): string
    {
        return $this->billType;
    }

    /**
     * Populated with valid duty types for international transactions only.
     *
     * Valid Duty Types: "01","02","03","04","05","06","07","08","09" 01 - Dutiable 02 - Non
     * Dutiable 03 - Low Value 04 - Courier Remission 05 - Gift 06 - Military 07 - Exception 08 -
     * Line Release 09 - Low Value
     *
     * @return Option<string>
     */
    public function getDutyType(): Option
    {
        return $this->dutyType;
    }

    /**
     * residential Indicator that was sent in on the request.
     *
     * Valid values: "01","02"
     *
     * 01 - Residential 02 - Commercial
     */
    public function getResidentialIndicator(): string
    {
        return $this->residentialIndicator;
    }

    /**
     * Destination country name value.
     */
    public function getDestinationCountryName(): string
    {
        return $this->destinationCountryName;
    }

    /**
     * Destination country code, conforms to ISO-defined country codes.
     */
    public function getDestinationCountryCode(): string
    {
        return $this->destinationCountryCode;
    }

    /**
     * The shipment destination postal code. Required for US domestic requests.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getDestinationPostalCode(): Option
    {
        return $this->destinationPostalCode;
    }

    /**
     * The shipment destination postal code low range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getDestinationPostalCodeLow(): Option
    {
        return $this->destinationPostalCodeLow;
    }

    /**
     * The shipment destination postal code high range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getDestinationPostalCodeHigh(): Option
    {
        return $this->destinationPostalCodeHigh;
    }

    /**
     * The shipment destination state or province.
     *
     * For U.S. addresses, the value will be a valid 2-Character value (per U.S. Mail Standards).
     *
     * For non-U.S. addresses the full State or Province name will be returned.
     *
     * @return Option<string>
     */
    public function getDestinationStateProvince(): Option
    {
        return $this->destinationStateProvince;
    }

    /**
     * The shipment destination city.
     *
     * Required for International requests for those countries that do not utilize postal codes.
     *
     * @return Option<string>
     */
    public function getDestinationCityName(): Option
    {
        return $this->destinationCityName;
    }

    /**
     * Origin country name value.
     */
    public function getOriginCountryName(): string
    {
        return $this->originCountryName;
    }

    /**
     * Origin country code, conforms to ISO-defined country codes.
     */
    public function getOriginCountryCode(): string
    {
        return $this->originCountryCode;
    }

    /**
     * The shipment origin postal code. Required for US domestic requests.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getOriginPostalCode(): Option
    {
        return $this->originPostalCode;
    }

    /**
     * The shipment origin postal code low range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getOriginPostalCodeLow(): Option
    {
        return $this->originPostalCodeLow;
    }

    /**
     * The shipment origin postal code high range. Value may or may not differ from
     * destinationPostalCode.
     *
     * Either 5, or 9-digit US zip codes must be used for U.S. addresses. For non-US addresses, this
     * is recommended for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getOriginPostalCodeHigh(): Option
    {
        return $this->originPostalCodeHigh;
    }

    /**
     * The shipment origin state or province.
     *
     * For U.S. addresses, the value will be a valid 2-Character value (per U.S. Mail Standards).
     *
     * For non-U.S. addresses the full State or Province name will be returned.
     *
     * @return Option<string>
     */
    public function getOriginStateProvince(): Option
    {
        return $this->originStateProvince;
    }

    /**
     * The shipment origin city.
     *
     * Required for International requests for those countries that do not utilize postal codes.
     *
     * @return Option<string>
     */
    public function getOriginCityName(): Option
    {
        return $this->originCityName;
    }

    /**
     * Shipment weight. Value is only required for international shipment.
     *
     * Defaults to 0.0
     *
     * @return Option<string>
     */
    public function getWeight(): Option
    {
        return $this->weight;
    }

    /**
     * Returned on response when weight was present on the request.
     *
     * @return Option<string>
     */
    public function getWeightUnitOfMeasure(): Option
    {
        return $this->weightUnitOfMeasure;
    }

    /**
     * Shipment contents value. Value is only required for international shipment.
     *
     * Defaults to 0.0
     *
     * @return Option<string>
     */
    public function getShipmentContentsValue(): Option
    {
        return $this->shipmentContentsValue;
    }

    /**
     * Returned on response when shipmentContentsValue was present on the request.
     *
     * @return Option<string>
     */
    public function getShipmentContentsCurrencyCode(): Option
    {
        return $this->shipmentContentsCurrencyCode;
    }

    /**
     * Returns TRUE if the shipment dates fall within a defined peak date range. When the guarantee
     * is suspended, it is suspended for all services in the response.
     *
     *   The logic for determining if guarantees are suspended applies per origin country.
     *
     * The following will be used to determine if a shipment falls within a defined peak date range:
     * shipDate (from the response), deliveryDate (from the response), server Date.
     *
     * Defined peak date range (range for when guarantees are suspended) is inclusive of start and
     * end dates.
     */
    public function getGuaranteeSuspended(): bool
    {
        return $this->guaranteeSuspended;
    }

    /**
     * Number of services being returned in the services array.
     */
    public function getNumberOfServices(): int
    {
        return $this->numberOfServices;
    }

    /** @return Option<list<Services>> */
    public function getServices(): Option
    {
        return $this->services;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $shipDate = null;
        $shipTime = null;
        $serviceLevel = None::create();
        $billType = null;
        $dutyType = None::create();
        $residentialIndicator = null;
        $destinationCountryName = null;
        $destinationCountryCode = null;
        $destinationPostalCode = None::create();
        $destinationPostalCodeLow = None::create();
        $destinationPostalCodeHigh = None::create();
        $destinationStateProvince = None::create();
        $destinationCityName = None::create();
        $originCountryName = null;
        $originCountryCode = null;
        $originPostalCode = None::create();
        $originPostalCodeLow = None::create();
        $originPostalCodeHigh = None::create();
        $originStateProvince = None::create();
        $originCityName = None::create();
        $weight = None::create();
        $weightUnitOfMeasure = None::create();
        $shipmentContentsValue = None::create();
        $shipmentContentsCurrencyCode = None::create();
        $guaranteeSuspended = null;
        $numberOfServices = null;
        $services = None::create();
        if (array_key_exists('shipDate', $data)) {
            $shipDateRaw = $data['shipDate'];
            if (!is_string($shipDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipDate" must be string, got %s.', get_debug_type($shipDateRaw)),
                );
            }
            $shipDate = $shipDateRaw;
        }
        if (array_key_exists('shipTime', $data)) {
            $shipTimeRaw = $data['shipTime'];
            if (!is_string($shipTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipTime" must be string, got %s.', get_debug_type($shipTimeRaw)),
                );
            }
            $shipTime = $shipTimeRaw;
        }
        if (array_key_exists('serviceLevel', $data) && $data['serviceLevel'] !== null) {
            $serviceLevelRaw = $data['serviceLevel'];
            if (!is_string($serviceLevelRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceLevel" must be string, got %s.', get_debug_type($serviceLevelRaw)),
                );
            }
            $serviceLevel = Some::create($serviceLevelRaw);
        }
        if (array_key_exists('billType', $data)) {
            $billTypeRaw = $data['billType'];
            if (!is_string($billTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "billType" must be string, got %s.', get_debug_type($billTypeRaw)),
                );
            }
            $billType = $billTypeRaw;
        }
        if (array_key_exists('dutyType', $data) && $data['dutyType'] !== null) {
            $dutyTypeRaw = $data['dutyType'];
            if (!is_string($dutyTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "dutyType" must be string, got %s.', get_debug_type($dutyTypeRaw)),
                );
            }
            $dutyType = Some::create($dutyTypeRaw);
        }
        if (array_key_exists('residentialIndicator', $data)) {
            $residentialIndicatorRaw = $data['residentialIndicator'];
            if (!is_string($residentialIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "residentialIndicator" must be string, got %s.',
                        get_debug_type($residentialIndicatorRaw),
                    ),
                );
            }
            $residentialIndicator = $residentialIndicatorRaw;
        }
        if (array_key_exists('destinationCountryName', $data)) {
            $destinationCountryNameRaw = $data['destinationCountryName'];
            if (!is_string($destinationCountryNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationCountryName" must be string, got %s.',
                        get_debug_type($destinationCountryNameRaw),
                    ),
                );
            }
            $destinationCountryName = $destinationCountryNameRaw;
        }
        if (array_key_exists('destinationCountryCode', $data)) {
            $destinationCountryCodeRaw = $data['destinationCountryCode'];
            if (!is_string($destinationCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationCountryCode" must be string, got %s.',
                        get_debug_type($destinationCountryCodeRaw),
                    ),
                );
            }
            $destinationCountryCode = $destinationCountryCodeRaw;
        }
        if (array_key_exists('destinationPostalCode', $data) && $data['destinationPostalCode'] !== null) {
            $destinationPostalCodeRaw = $data['destinationPostalCode'];
            if (!is_string($destinationPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationPostalCode" must be string, got %s.',
                        get_debug_type($destinationPostalCodeRaw),
                    ),
                );
            }
            $destinationPostalCode = Some::create($destinationPostalCodeRaw);
        }
        if (array_key_exists('destinationPostalCodeLow', $data) && $data['destinationPostalCodeLow'] !== null) {
            $destinationPostalCodeLowRaw = $data['destinationPostalCodeLow'];
            if (!is_string($destinationPostalCodeLowRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationPostalCodeLow" must be string, got %s.',
                        get_debug_type($destinationPostalCodeLowRaw),
                    ),
                );
            }
            $destinationPostalCodeLow = Some::create($destinationPostalCodeLowRaw);
        }
        if (array_key_exists('destinationPostalCodeHigh', $data) && $data['destinationPostalCodeHigh'] !== null) {
            $destinationPostalCodeHighRaw = $data['destinationPostalCodeHigh'];
            if (!is_string($destinationPostalCodeHighRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationPostalCodeHigh" must be string, got %s.',
                        get_debug_type($destinationPostalCodeHighRaw),
                    ),
                );
            }
            $destinationPostalCodeHigh = Some::create($destinationPostalCodeHighRaw);
        }
        if (array_key_exists('destinationStateProvince', $data) && $data['destinationStateProvince'] !== null) {
            $destinationStateProvinceRaw = $data['destinationStateProvince'];
            if (!is_string($destinationStateProvinceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationStateProvince" must be string, got %s.',
                        get_debug_type($destinationStateProvinceRaw),
                    ),
                );
            }
            $destinationStateProvince = Some::create($destinationStateProvinceRaw);
        }
        if (array_key_exists('destinationCityName', $data) && $data['destinationCityName'] !== null) {
            $destinationCityNameRaw = $data['destinationCityName'];
            if (!is_string($destinationCityNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationCityName" must be string, got %s.',
                        get_debug_type($destinationCityNameRaw),
                    ),
                );
            }
            $destinationCityName = Some::create($destinationCityNameRaw);
        }
        if (array_key_exists('originCountryName', $data)) {
            $originCountryNameRaw = $data['originCountryName'];
            if (!is_string($originCountryNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originCountryName" must be string, got %s.',
                        get_debug_type($originCountryNameRaw),
                    ),
                );
            }
            $originCountryName = $originCountryNameRaw;
        }
        if (array_key_exists('originCountryCode', $data)) {
            $originCountryCodeRaw = $data['originCountryCode'];
            if (!is_string($originCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originCountryCode" must be string, got %s.',
                        get_debug_type($originCountryCodeRaw),
                    ),
                );
            }
            $originCountryCode = $originCountryCodeRaw;
        }
        if (array_key_exists('originPostalCode', $data) && $data['originPostalCode'] !== null) {
            $originPostalCodeRaw = $data['originPostalCode'];
            if (!is_string($originPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originPostalCode" must be string, got %s.',
                        get_debug_type($originPostalCodeRaw),
                    ),
                );
            }
            $originPostalCode = Some::create($originPostalCodeRaw);
        }
        if (array_key_exists('originPostalCodeLow', $data) && $data['originPostalCodeLow'] !== null) {
            $originPostalCodeLowRaw = $data['originPostalCodeLow'];
            if (!is_string($originPostalCodeLowRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originPostalCodeLow" must be string, got %s.',
                        get_debug_type($originPostalCodeLowRaw),
                    ),
                );
            }
            $originPostalCodeLow = Some::create($originPostalCodeLowRaw);
        }
        if (array_key_exists('originPostalCodeHigh', $data) && $data['originPostalCodeHigh'] !== null) {
            $originPostalCodeHighRaw = $data['originPostalCodeHigh'];
            if (!is_string($originPostalCodeHighRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originPostalCodeHigh" must be string, got %s.',
                        get_debug_type($originPostalCodeHighRaw),
                    ),
                );
            }
            $originPostalCodeHigh = Some::create($originPostalCodeHighRaw);
        }
        if (array_key_exists('originStateProvince', $data) && $data['originStateProvince'] !== null) {
            $originStateProvinceRaw = $data['originStateProvince'];
            if (!is_string($originStateProvinceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originStateProvince" must be string, got %s.',
                        get_debug_type($originStateProvinceRaw),
                    ),
                );
            }
            $originStateProvince = Some::create($originStateProvinceRaw);
        }
        if (array_key_exists('originCityName', $data) && $data['originCityName'] !== null) {
            $originCityNameRaw = $data['originCityName'];
            if (!is_string($originCityNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "originCityName" must be string, got %s.', get_debug_type($originCityNameRaw)),
                );
            }
            $originCityName = Some::create($originCityNameRaw);
        }
        if (array_key_exists('weight', $data) && $data['weight'] !== null) {
            $weightRaw = $data['weight'];
            if (!is_string($weightRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "weight" must be string, got %s.', get_debug_type($weightRaw)),
                );
            }
            $weight = Some::create($weightRaw);
        }
        if (array_key_exists('weightUnitOfMeasure', $data) && $data['weightUnitOfMeasure'] !== null) {
            $weightUnitOfMeasureRaw = $data['weightUnitOfMeasure'];
            if (!is_string($weightUnitOfMeasureRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "weightUnitOfMeasure" must be string, got %s.',
                        get_debug_type($weightUnitOfMeasureRaw),
                    ),
                );
            }
            $weightUnitOfMeasure = Some::create($weightUnitOfMeasureRaw);
        }
        if (array_key_exists('shipmentContentsValue', $data) && $data['shipmentContentsValue'] !== null) {
            $shipmentContentsValueRaw = $data['shipmentContentsValue'];
            if (!is_string($shipmentContentsValueRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipmentContentsValue" must be string, got %s.',
                        get_debug_type($shipmentContentsValueRaw),
                    ),
                );
            }
            $shipmentContentsValue = Some::create($shipmentContentsValueRaw);
        }
        if (array_key_exists('shipmentContentsCurrencyCode', $data) && $data['shipmentContentsCurrencyCode'] !== null) {
            $shipmentContentsCurrencyCodeRaw = $data['shipmentContentsCurrencyCode'];
            if (!is_string($shipmentContentsCurrencyCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipmentContentsCurrencyCode" must be string, got %s.',
                        get_debug_type($shipmentContentsCurrencyCodeRaw),
                    ),
                );
            }
            $shipmentContentsCurrencyCode = Some::create($shipmentContentsCurrencyCodeRaw);
        }
        if (array_key_exists('guaranteeSuspended', $data)) {
            $guaranteeSuspendedRaw = $data['guaranteeSuspended'];
            if (!is_bool($guaranteeSuspendedRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "guaranteeSuspended" must be bool, got %s.',
                        get_debug_type($guaranteeSuspendedRaw),
                    ),
                );
            }
            $guaranteeSuspended = $guaranteeSuspendedRaw;
        }
        if (array_key_exists('numberOfServices', $data)) {
            $numberOfServicesRaw = $data['numberOfServices'];
            if (!is_int($numberOfServicesRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "numberOfServices" must be int, got %s.', get_debug_type($numberOfServicesRaw)),
                );
            }
            $numberOfServices = $numberOfServicesRaw;
        }
        if (array_key_exists('services', $data) && $data['services'] !== null) {
            $servicesRaw = $data['services'];
            if (!(is_array($servicesRaw) && array_is_list($servicesRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "services" must be list, got %s.', get_debug_type($servicesRaw)),
                );
            }
            $services = Some::create(array_map(static function (mixed $value): Services {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return Services::fromArray($valueTyped);
            }, $servicesRaw));
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'shipDate' => true,
                'shipTime' => true,
                'serviceLevel' => true,
                'billType' => true,
                'dutyType' => true,
                'residentialIndicator' => true,
                'destinationCountryName' => true,
                'destinationCountryCode' => true,
                'destinationPostalCode' => true,
                'destinationPostalCodeLow' => true,
                'destinationPostalCodeHigh' => true,
                'destinationStateProvince' => true,
                'destinationCityName' => true,
                'originCountryName' => true,
                'originCountryCode' => true,
                'originPostalCode' => true,
                'originPostalCodeLow' => true,
                'originPostalCodeHigh' => true,
                'originStateProvince' => true,
                'originCityName' => true,
                'weight' => true,
                'weightUnitOfMeasure' => true,
                'shipmentContentsValue' => true,
                'shipmentContentsCurrencyCode' => true,
                'guaranteeSuspended' => true,
                'numberOfServices' => true,
                'services' => true,
            ],
        );
        if ($shipDate === null) {
            throw new MalformedDataException('Required property "shipDate" is missing from the document.');
        }
        if ($shipTime === null) {
            throw new MalformedDataException('Required property "shipTime" is missing from the document.');
        }
        if ($billType === null) {
            throw new MalformedDataException('Required property "billType" is missing from the document.');
        }
        if ($residentialIndicator === null) {
            throw new MalformedDataException('Required property "residentialIndicator" is missing from the document.');
        }
        if ($destinationCountryName === null) {
            throw new MalformedDataException(
                'Required property "destinationCountryName" is missing from the document.',
            );
        }
        if ($destinationCountryCode === null) {
            throw new MalformedDataException(
                'Required property "destinationCountryCode" is missing from the document.',
            );
        }
        if ($originCountryName === null) {
            throw new MalformedDataException('Required property "originCountryName" is missing from the document.');
        }
        if ($originCountryCode === null) {
            throw new MalformedDataException('Required property "originCountryCode" is missing from the document.');
        }
        if ($guaranteeSuspended === null) {
            throw new MalformedDataException('Required property "guaranteeSuspended" is missing from the document.');
        }
        if ($numberOfServices === null) {
            throw new MalformedDataException('Required property "numberOfServices" is missing from the document.');
        }

        return new self(
            $shipDate,
            $shipTime,
            $billType,
            $residentialIndicator,
            $destinationCountryName,
            $destinationCountryCode,
            $originCountryName,
            $originCountryCode,
            $guaranteeSuspended,
            $numberOfServices,
            $serviceLevel,
            $dutyType,
            $destinationPostalCode,
            $destinationPostalCodeLow,
            $destinationPostalCodeHigh,
            $destinationStateProvince,
            $destinationCityName,
            $originPostalCode,
            $originPostalCodeLow,
            $originPostalCodeHigh,
            $originStateProvince,
            $originCityName,
            $weight,
            $weightUnitOfMeasure,
            $shipmentContentsValue,
            $shipmentContentsCurrencyCode,
            $services,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['shipDate'] = $this->shipDate;
        $dataArray['shipTime'] = $this->shipTime;
        $serviceLevelOption = $this->serviceLevel;
        if ($serviceLevelOption->isDefined()) {
            $serviceLevel = $serviceLevelOption->get();
            $dataArray['serviceLevel'] = $serviceLevel;
        }
        $dataArray['billType'] = $this->billType;
        $dutyTypeOption = $this->dutyType;
        if ($dutyTypeOption->isDefined()) {
            $dutyType = $dutyTypeOption->get();
            $dataArray['dutyType'] = $dutyType;
        }
        $dataArray['residentialIndicator'] = $this->residentialIndicator;
        $dataArray['destinationCountryName'] = $this->destinationCountryName;
        $dataArray['destinationCountryCode'] = $this->destinationCountryCode;
        $destinationPostalCodeOption = $this->destinationPostalCode;
        if ($destinationPostalCodeOption->isDefined()) {
            $destinationPostalCode = $destinationPostalCodeOption->get();
            $dataArray['destinationPostalCode'] = $destinationPostalCode;
        }
        $destinationPostalCodeLowOption = $this->destinationPostalCodeLow;
        if ($destinationPostalCodeLowOption->isDefined()) {
            $destinationPostalCodeLow = $destinationPostalCodeLowOption->get();
            $dataArray['destinationPostalCodeLow'] = $destinationPostalCodeLow;
        }
        $destinationPostalCodeHighOption = $this->destinationPostalCodeHigh;
        if ($destinationPostalCodeHighOption->isDefined()) {
            $destinationPostalCodeHigh = $destinationPostalCodeHighOption->get();
            $dataArray['destinationPostalCodeHigh'] = $destinationPostalCodeHigh;
        }
        $destinationStateProvinceOption = $this->destinationStateProvince;
        if ($destinationStateProvinceOption->isDefined()) {
            $destinationStateProvince = $destinationStateProvinceOption->get();
            $dataArray['destinationStateProvince'] = $destinationStateProvince;
        }
        $destinationCityNameOption = $this->destinationCityName;
        if ($destinationCityNameOption->isDefined()) {
            $destinationCityName = $destinationCityNameOption->get();
            $dataArray['destinationCityName'] = $destinationCityName;
        }
        $dataArray['originCountryName'] = $this->originCountryName;
        $dataArray['originCountryCode'] = $this->originCountryCode;
        $originPostalCodeOption = $this->originPostalCode;
        if ($originPostalCodeOption->isDefined()) {
            $originPostalCode = $originPostalCodeOption->get();
            $dataArray['originPostalCode'] = $originPostalCode;
        }
        $originPostalCodeLowOption = $this->originPostalCodeLow;
        if ($originPostalCodeLowOption->isDefined()) {
            $originPostalCodeLow = $originPostalCodeLowOption->get();
            $dataArray['originPostalCodeLow'] = $originPostalCodeLow;
        }
        $originPostalCodeHighOption = $this->originPostalCodeHigh;
        if ($originPostalCodeHighOption->isDefined()) {
            $originPostalCodeHigh = $originPostalCodeHighOption->get();
            $dataArray['originPostalCodeHigh'] = $originPostalCodeHigh;
        }
        $originStateProvinceOption = $this->originStateProvince;
        if ($originStateProvinceOption->isDefined()) {
            $originStateProvince = $originStateProvinceOption->get();
            $dataArray['originStateProvince'] = $originStateProvince;
        }
        $originCityNameOption = $this->originCityName;
        if ($originCityNameOption->isDefined()) {
            $originCityName = $originCityNameOption->get();
            $dataArray['originCityName'] = $originCityName;
        }
        $weightOption = $this->weight;
        if ($weightOption->isDefined()) {
            $weight = $weightOption->get();
            $dataArray['weight'] = $weight;
        }
        $weightUnitOfMeasureOption = $this->weightUnitOfMeasure;
        if ($weightUnitOfMeasureOption->isDefined()) {
            $weightUnitOfMeasure = $weightUnitOfMeasureOption->get();
            $dataArray['weightUnitOfMeasure'] = $weightUnitOfMeasure;
        }
        $shipmentContentsValueOption = $this->shipmentContentsValue;
        if ($shipmentContentsValueOption->isDefined()) {
            $shipmentContentsValue = $shipmentContentsValueOption->get();
            $dataArray['shipmentContentsValue'] = $shipmentContentsValue;
        }
        $shipmentContentsCurrencyCodeOption = $this->shipmentContentsCurrencyCode;
        if ($shipmentContentsCurrencyCodeOption->isDefined()) {
            $shipmentContentsCurrencyCode = $shipmentContentsCurrencyCodeOption->get();
            $dataArray['shipmentContentsCurrencyCode'] = $shipmentContentsCurrencyCode;
        }
        $dataArray['guaranteeSuspended'] = $this->guaranteeSuspended;
        $dataArray['numberOfServices'] = $this->numberOfServices;
        $servicesOption = $this->services;
        if ($servicesOption->isDefined()) {
            $services = $servicesOption->get();
            $values = [];
            foreach ($services as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['services'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): EmsResponseBuilder
    {
        return new EmsResponseBuilder(
            $this->shipDate,
            $this->shipTime,
            $this->billType,
            $this->residentialIndicator,
            $this->destinationCountryName,
            $this->destinationCountryCode,
            $this->originCountryName,
            $this->originCountryCode,
            $this->guaranteeSuspended,
            $this->numberOfServices,
            $this->serviceLevel,
            $this->dutyType,
            $this->destinationPostalCode,
            $this->destinationPostalCodeLow,
            $this->destinationPostalCodeHigh,
            $this->destinationStateProvince,
            $this->destinationCityName,
            $this->originPostalCode,
            $this->originPostalCodeLow,
            $this->originPostalCodeHigh,
            $this->originStateProvince,
            $this->originCityName,
            $this->weight,
            $this->weightUnitOfMeasure,
            $this->shipmentContentsValue,
            $this->shipmentContentsCurrencyCode,
            $this->services,
            $this->additionalProperties,
        );
    }
}
