<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see ErrorResponse}.
 */
final class ErrorResponseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<Errors>>     $errors
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $errors, private array $additionalProperties)
    {
    }

    /** @param list<Errors> $errors */
    public function setErrors(array $errors): self
    {
        $this->errors = Some::create($errors);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ErrorResponse
    {
        return new ErrorResponse($this->errors, $this->additionalProperties);
    }
}
