<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see Errors}.
 */
final class ErrorsBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $code
     * @param Option<string>           $message
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $code, private Option $message, private array $additionalProperties)
    {
    }

    /**
     * Error code.
     */
    public function setCode(string $code): self
    {
        $this->code = Some::create($code);

        return $this;
    }

    /**
     * Error message.
     */
    public function setMessage(string $message): self
    {
        $this->message = Some::create($message);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Errors
    {
        return new Errors($this->code, $this->message, $this->additionalProperties);
    }
}
