<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_string;
use function sprintf;

final readonly class Errors implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $code
     * @param Option<string>           $message
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $code, private Option $message, private array $additionalProperties)
    {
    }

    public static function builder(): ErrorsBuilder
    {
        return new ErrorsBuilder(None::create(), None::create(), []);
    }

    /**
     * Error code.
     *
     * @return Option<string>
     */
    public function getCode(): Option
    {
        return $this->code;
    }

    /**
     * Error message.
     *
     * @return Option<string>
     */
    public function getMessage(): Option
    {
        return $this->message;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $code = None::create();
        $message = None::create();
        if (array_key_exists('code', $data) && $data['code'] !== null) {
            $codeRaw = $data['code'];
            if (!is_string($codeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "code" must be string, got %s.', get_debug_type($codeRaw)),
                );
            }
            $code = Some::create($codeRaw);
        }
        if (array_key_exists('message', $data) && $data['message'] !== null) {
            $messageRaw = $data['message'];
            if (!is_string($messageRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "message" must be string, got %s.', get_debug_type($messageRaw)),
                );
            }
            $message = Some::create($messageRaw);
        }
        $additionalProperties = array_diff_key($data, ['code' => true, 'message' => true]);

        return new self($code, $message, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $codeOption = $this->code;
        if ($codeOption->isDefined()) {
            $code = $codeOption->get();
            $dataArray['code'] = $code;
        }
        $messageOption = $this->message;
        if ($messageOption->isDefined()) {
            $message = $messageOption->get();
            $dataArray['message'] = $message;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ErrorsBuilder
    {
        return new ErrorsBuilder($this->code, $this->message, $this->additionalProperties);
    }
}
