<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class ErrorResponse implements SelfNormalizingModel
{
    /**
     * @param Option<list<Errors>>     $errors
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(private Option $errors, private array $additionalProperties)
    {
    }

    public static function builder(): ErrorResponseBuilder
    {
        return new ErrorResponseBuilder(None::create(), []);
    }

    /** @return Option<list<Errors>> */
    public function getErrors(): Option
    {
        return $this->errors;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $errors = None::create();
        if (array_key_exists('errors', $data) && $data['errors'] !== null) {
            $errorsRaw = $data['errors'];
            if (!(is_array($errorsRaw) && array_is_list($errorsRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "errors" must be list, got %s.', get_debug_type($errorsRaw)),
                );
            }
            $errors = Some::create(array_map(static function (mixed $value): Errors {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return Errors::fromArray($valueTyped);
            }, $errorsRaw));
        }
        $additionalProperties = array_diff_key($data, ['errors' => true]);

        return new self($errors, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $errorsOption = $this->errors;
        if ($errorsOption->isDefined()) {
            $errors = $errorsOption->get();
            $values = [];
            foreach ($errors as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['errors'] = $values;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): ErrorResponseBuilder
    {
        return new ErrorResponseBuilder($this->errors, $this->additionalProperties);
    }
}
