<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

/**
 * What a model is normalized into: a PHP array, or a JSON document.
 *
 * The two differ in one place only — a JSON object that happens to be empty. PHP has one array for
 * both lists and dictionaries, and `json_encode([])` writes `[]`: a model none of whose properties
 * is set, or a map with no entries, would go out as an empty *array* where the description asks for
 * an object, and a server checking types rejects it. A `stdClass` encodes as `{}`, empty or not.
 *
 * Every other value is the same either way, so each generated model has a single `normalize()`
 * body, and the positions that hold an object ask this which form to write. `toArray()` keeps
 * answering the plain array that `fromArray()` reads back and the validator checks;
 * `jsonSerialize()` answers the JSON document.
 *
 * The limit of that, said plainly because it is a property of this package and not an oversight:
 * this works wherever the *description* says the position holds an object, because then there is
 * something to ask. Where it says nothing — a free-form value, the bucket a model keeps unknown
 * properties in — the value is a PHP array and nothing else is known about it, so `{}` read from a
 * response goes back out as `[]`, and so does the legal object `{"0":"a"}`. The information is
 * already gone by then: `json_decode($body, true)` maps both JSON objects and JSON arrays onto the
 * one array type PHP has, and no later step can tell which it was.
 *
 * Keeping it would mean handing consumers a `stdClass` wherever the description is silent, which is
 * the worse trade: it would put an object in the middle of an otherwise array-shaped value for the
 * sake of a distinction that the server, on the receiving end, almost never makes. A consumer who
 * does need the exact bytes back has them — the raw body is what the package was handed.
 */
enum NormalizationTarget
{
    case PhpArray;
    case Json;

    /**
     * A nested model, in this target's form.
     *
     * @return array<int|string, mixed>|object
     */
    public function model(SelfNormalizingModel $model): array|object
    {
        return match ($this) {
            self::PhpArray => $model->toArray(),
            self::Json => $model->jsonSerialize(),
        };
    }

    /**
     * A JSON object held as a PHP array — a map, `additionalProperties`, a free-form object — in
     * this target's form.
     *
     * The cast is also what keeps a map with numeric keys an object: `['0' => 'a']` is the list
     * `["a"]` to `json_encode()`, but `{"0":"a"}` once it is a `stdClass`.
     *
     * @param array<int|string, mixed> $map
     *
     * @return array<int|string, mixed>|object
     */
    public function map(array $map): array|object
    {
        return match ($this) {
            self::PhpArray => $map,
            self::Json => (object) $map,
        };
    }
}
