<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_int;
use function is_string;
use function sprintf;

final readonly class Services implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $saturdayDeliveryDate
     * @param Option<string>           $saturdayDeliveryTime
     * @param Option<string>           $serviceRemarksText
     * @param Option<string>           $poddate
     * @param Option<int>              $poddays
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $serviceLevel,
        private string $serviceLevelDescription,
        private string $shipDate,
        private string $deliveryDate,
        private string $commitTime,
        private string $deliveryTime,
        private string $deliveryDayOfWeek,
        private string $nextDayPickupIndicator,
        private string $saturdayPickupIndicator,
        private string $guaranteeIndicator,
        private int $totalTransitDays,
        private int $businessTransitDays,
        private int $restDaysCount,
        private int $holidayCount,
        private int $delayCount,
        private string $pickupDate,
        private string $pickupTime,
        private string $cstccutoffTime,
        private Option $saturdayDeliveryDate,
        private Option $saturdayDeliveryTime,
        private Option $serviceRemarksText,
        private Option $poddate,
        private Option $poddays,
        private array $additionalProperties,
    ) {
    }

    public static function builder(
        string $serviceLevel,
        string $serviceLevelDescription,
        string $shipDate,
        string $deliveryDate,
        string $commitTime,
        string $deliveryTime,
        string $deliveryDayOfWeek,
        string $nextDayPickupIndicator,
        string $saturdayPickupIndicator,
        string $guaranteeIndicator,
        int $totalTransitDays,
        int $businessTransitDays,
        int $restDaysCount,
        int $holidayCount,
        int $delayCount,
        string $pickupDate,
        string $pickupTime,
        string $cstccutoffTime,
    ): ServicesBuilder {
        return new ServicesBuilder(
            $serviceLevel,
            $serviceLevelDescription,
            $shipDate,
            $deliveryDate,
            $commitTime,
            $deliveryTime,
            $deliveryDayOfWeek,
            $nextDayPickupIndicator,
            $saturdayPickupIndicator,
            $guaranteeIndicator,
            $totalTransitDays,
            $businessTransitDays,
            $restDaysCount,
            $holidayCount,
            $delayCount,
            $pickupDate,
            $pickupTime,
            $cstccutoffTime,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * Service level code.
     *
     * Valid domestic service codes: "1DMS","1DAS","1DM","1DA","1DP","2DM","2DA","3DS","GND".
     *
     *   Valid International service codes (not a complete list) ,"01","02","03","05","08","09","10","11","18","19","20","21","22","23","24","25","26","28","29","33","68".
     */
    public function getServiceLevel(): string
    {
        return $this->serviceLevel;
    }

    /**
     * Service name. Examples are: UPS Next Day Air, UPS Ground, UPS Expedited, UPS Worldwide
     * Express Freight.
     */
    public function getServiceLevelDescription(): string
    {
        return $this->serviceLevelDescription;
    }

    /**
     * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). This date may or may not be the UPS business date.
     *
     * Valid Format: YYYY-MM-DD
     */
    public function getShipDate(): string
    {
        return $this->shipDate;
    }

    /**
     * Scheduled delivery date.
     *
     * Valid format: YYYY-MM-DD
     */
    public function getDeliveryDate(): string
    {
        return $this->deliveryDate;
    }

    /**
     * Scheduled commit time.
     *
     * For international shipments the value always come back from SE (OPSYS data) but for domestic,
     * value may be used from NRF commit time.
     *
     * Valid format: HH:MM:SS
     */
    public function getCommitTime(): string
    {
        return $this->commitTime;
    }

    /**
     * Scheduled Delivery Time, value may be later then commit time.
     *
     * Valid format: HH:MM:SS
     */
    public function getDeliveryTime(): string
    {
        return $this->deliveryTime;
    }

    /**
     * Three character scheduled delivery day of week.
     *
     * Valid values: "MON","TUE","WED","THU","FRI", "SAT"
     */
    public function getDeliveryDayOfWeek(): string
    {
        return $this->deliveryDayOfWeek;
    }

    /**
     * Returns a "1" if the requested shipped on date was changed. This data is available only for
     * international transactions.
     *
     * When this flag is set, WWDTDisclaimer.getNextDayDisclaimer method could be called to return
     * the next day disclaimer message.
     */
    public function getNextDayPickupIndicator(): string
    {
        return $this->nextDayPickupIndicator;
    }

    /**
     * Returns "1" if Saturday Pickup is available for an extra charge otherwise it will return "0".
     *
     * When this flag is set, WWDTDisclaimer.getSaturdayPickupDisclaimer method could be called to
     * return the Saturday pickup extra charge message
     */
    public function getSaturdayPickupIndicator(): string
    {
        return $this->saturdayPickupIndicator;
    }

    /**
     * Delivery date of Saturday Delivery.
     *
     * Valid Format: YYYY-MM-DD
     *
     * @return Option<string>
     */
    public function getSaturdayDeliveryDate(): Option
    {
        return $this->saturdayDeliveryDate;
    }

    /**
     * Delivery time of Saturday deliver.
     *
     * Valid format: HH:MM:SS
     *
     * @return Option<string>
     */
    public function getSaturdayDeliveryTime(): Option
    {
        return $this->saturdayDeliveryTime;
    }

    /**
     * Service remarks text. The contents of this field will represent text that the back end
     * application/function needs to display to clarify the time in transit calculation.
     *
     * @return Option<string>
     */
    public function getServiceRemarksText(): Option
    {
        return $this->serviceRemarksText;
    }

    /**
     * Return "1" Guaranteed, or "0" Not Guaranteed based on below conditions:
     *
     * If the ship date, delivery date, and system date are not within a defined peak date range,
     * and a value for service guarantee is available in SE (OPSYS data) that will be returned.
     *
     * If the ship date or delivery date or system date are within a defined peak date range and the
     * service is within the list of services to remove guarantees for, "0" wil be returned.
     */
    public function getGuaranteeIndicator(): string
    {
        return $this->guaranteeIndicator;
    }

    /**
     * Available for International requests. Number of calendar days from origin location to
     * destination location. TotalTransitDays = BusinessTransitDays + RestDaysCount + HolidayCount.
     *
     * Defaults to 0.
     */
    public function getTotalTransitDays(): int
    {
        return $this->totalTransitDays;
    }

    /**
     * Returns the number of UPS business days from origin location to destination location.
     */
    public function getBusinessTransitDays(): int
    {
        return $this->businessTransitDays;
    }

    /**
     * Returns the number of rest days encountered at the origin location. this data is available
     * only for international transactions.
     *
     * Defaults to 0.
     */
    public function getRestDaysCount(): int
    {
        return $this->restDaysCount;
    }

    /**
     * Returns the number of holidays encountered at the origin and destination location, if it
     * effects the time and transit. This data is available only for international transactions.
     *
     * Defaults to 0.
     */
    public function getHolidayCount(): int
    {
        return $this->holidayCount;
    }

    /**
     * Returns the number of delay needed for customs encounter at the origin or destination
     * location. This data is available only for international transactions.
     *
     * Defaults to 0.
     */
    public function getDelayCount(): int
    {
        return $this->delayCount;
    }

    /**
     * Planned pickup date.
     *
     * Note: This value may not equal the shipped on value requested. This could happen when the
     * requested shipped on date is a holiday or for locations needing 24 hour notice before a
     * pickup could be made.
     */
    public function getPickupDate(): string
    {
        return $this->pickupDate;
    }

    /**
     * Latest possible pickup time. This data is available only for international transactions. If
     * the package was not actually picked by UPS before this time, the services will not meet the
     * guarantee commitment.
     */
    public function getPickupTime(): string
    {
        return $this->pickupTime;
    }

    /**
     * Latest time a customer can contact UPS CST to be notified for requesting a pickup. This data
     * is available only for international transactions. If customer does not notify UPS for a
     * pickup before this time, the services will not meet the guarantee commitment.
     */
    public function getCstccutoffTime(): string
    {
        return $this->cstccutoffTime;
    }

    /**
     * Returns the date proof of delivery information would be available. This data is available
     * only for international transactions.
     *
     * @return Option<string>
     */
    public function getPoddate(): Option
    {
        return $this->poddate;
    }

    /**
     * Returns the number of days proof of delivery information will be available. This data is
     * available only for international transactions.
     *
     * @return Option<int>
     */
    public function getPoddays(): Option
    {
        return $this->poddays;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $serviceLevel = null;
        $serviceLevelDescription = null;
        $shipDate = null;
        $deliveryDate = null;
        $commitTime = null;
        $deliveryTime = null;
        $deliveryDayOfWeek = null;
        $nextDayPickupIndicator = null;
        $saturdayPickupIndicator = null;
        $saturdayDeliveryDate = None::create();
        $saturdayDeliveryTime = None::create();
        $serviceRemarksText = None::create();
        $guaranteeIndicator = null;
        $totalTransitDays = null;
        $businessTransitDays = null;
        $restDaysCount = null;
        $holidayCount = null;
        $delayCount = null;
        $pickupDate = null;
        $pickupTime = null;
        $cstccutoffTime = null;
        $poddate = None::create();
        $poddays = None::create();
        if (array_key_exists('serviceLevel', $data)) {
            $serviceLevelRaw = $data['serviceLevel'];
            if (!is_string($serviceLevelRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "serviceLevel" must be string, got %s.', get_debug_type($serviceLevelRaw)),
                );
            }
            $serviceLevel = $serviceLevelRaw;
        }
        if (array_key_exists('serviceLevelDescription', $data)) {
            $serviceLevelDescriptionRaw = $data['serviceLevelDescription'];
            if (!is_string($serviceLevelDescriptionRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "serviceLevelDescription" must be string, got %s.',
                        get_debug_type($serviceLevelDescriptionRaw),
                    ),
                );
            }
            $serviceLevelDescription = $serviceLevelDescriptionRaw;
        }
        if (array_key_exists('shipDate', $data)) {
            $shipDateRaw = $data['shipDate'];
            if (!is_string($shipDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipDate" must be string, got %s.', get_debug_type($shipDateRaw)),
                );
            }
            $shipDate = $shipDateRaw;
        }
        if (array_key_exists('deliveryDate', $data)) {
            $deliveryDateRaw = $data['deliveryDate'];
            if (!is_string($deliveryDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deliveryDate" must be string, got %s.', get_debug_type($deliveryDateRaw)),
                );
            }
            $deliveryDate = $deliveryDateRaw;
        }
        if (array_key_exists('commitTime', $data)) {
            $commitTimeRaw = $data['commitTime'];
            if (!is_string($commitTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "commitTime" must be string, got %s.', get_debug_type($commitTimeRaw)),
                );
            }
            $commitTime = $commitTimeRaw;
        }
        if (array_key_exists('deliveryTime', $data)) {
            $deliveryTimeRaw = $data['deliveryTime'];
            if (!is_string($deliveryTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "deliveryTime" must be string, got %s.', get_debug_type($deliveryTimeRaw)),
                );
            }
            $deliveryTime = $deliveryTimeRaw;
        }
        if (array_key_exists('deliveryDayOfWeek', $data)) {
            $deliveryDayOfWeekRaw = $data['deliveryDayOfWeek'];
            if (!is_string($deliveryDayOfWeekRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "deliveryDayOfWeek" must be string, got %s.',
                        get_debug_type($deliveryDayOfWeekRaw),
                    ),
                );
            }
            $deliveryDayOfWeek = $deliveryDayOfWeekRaw;
        }
        if (array_key_exists('nextDayPickupIndicator', $data)) {
            $nextDayPickupIndicatorRaw = $data['nextDayPickupIndicator'];
            if (!is_string($nextDayPickupIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "nextDayPickupIndicator" must be string, got %s.',
                        get_debug_type($nextDayPickupIndicatorRaw),
                    ),
                );
            }
            $nextDayPickupIndicator = $nextDayPickupIndicatorRaw;
        }
        if (array_key_exists('saturdayPickupIndicator', $data)) {
            $saturdayPickupIndicatorRaw = $data['saturdayPickupIndicator'];
            if (!is_string($saturdayPickupIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "saturdayPickupIndicator" must be string, got %s.',
                        get_debug_type($saturdayPickupIndicatorRaw),
                    ),
                );
            }
            $saturdayPickupIndicator = $saturdayPickupIndicatorRaw;
        }
        if (array_key_exists('saturdayDeliveryDate', $data) && $data['saturdayDeliveryDate'] !== null) {
            $saturdayDeliveryDateRaw = $data['saturdayDeliveryDate'];
            if (!is_string($saturdayDeliveryDateRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "saturdayDeliveryDate" must be string, got %s.',
                        get_debug_type($saturdayDeliveryDateRaw),
                    ),
                );
            }
            $saturdayDeliveryDate = Some::create($saturdayDeliveryDateRaw);
        }
        if (array_key_exists('saturdayDeliveryTime', $data) && $data['saturdayDeliveryTime'] !== null) {
            $saturdayDeliveryTimeRaw = $data['saturdayDeliveryTime'];
            if (!is_string($saturdayDeliveryTimeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "saturdayDeliveryTime" must be string, got %s.',
                        get_debug_type($saturdayDeliveryTimeRaw),
                    ),
                );
            }
            $saturdayDeliveryTime = Some::create($saturdayDeliveryTimeRaw);
        }
        if (array_key_exists('serviceRemarksText', $data) && $data['serviceRemarksText'] !== null) {
            $serviceRemarksTextRaw = $data['serviceRemarksText'];
            if (!is_string($serviceRemarksTextRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "serviceRemarksText" must be string, got %s.',
                        get_debug_type($serviceRemarksTextRaw),
                    ),
                );
            }
            $serviceRemarksText = Some::create($serviceRemarksTextRaw);
        }
        if (array_key_exists('guaranteeIndicator', $data)) {
            $guaranteeIndicatorRaw = $data['guaranteeIndicator'];
            if (!is_string($guaranteeIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "guaranteeIndicator" must be string, got %s.',
                        get_debug_type($guaranteeIndicatorRaw),
                    ),
                );
            }
            $guaranteeIndicator = $guaranteeIndicatorRaw;
        }
        if (array_key_exists('totalTransitDays', $data)) {
            $totalTransitDaysRaw = $data['totalTransitDays'];
            if (!is_int($totalTransitDaysRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "totalTransitDays" must be int, got %s.', get_debug_type($totalTransitDaysRaw)),
                );
            }
            $totalTransitDays = $totalTransitDaysRaw;
        }
        if (array_key_exists('businessTransitDays', $data)) {
            $businessTransitDaysRaw = $data['businessTransitDays'];
            if (!is_int($businessTransitDaysRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "businessTransitDays" must be int, got %s.',
                        get_debug_type($businessTransitDaysRaw),
                    ),
                );
            }
            $businessTransitDays = $businessTransitDaysRaw;
        }
        if (array_key_exists('restDaysCount', $data)) {
            $restDaysCountRaw = $data['restDaysCount'];
            if (!is_int($restDaysCountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "restDaysCount" must be int, got %s.', get_debug_type($restDaysCountRaw)),
                );
            }
            $restDaysCount = $restDaysCountRaw;
        }
        if (array_key_exists('holidayCount', $data)) {
            $holidayCountRaw = $data['holidayCount'];
            if (!is_int($holidayCountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "holidayCount" must be int, got %s.', get_debug_type($holidayCountRaw)),
                );
            }
            $holidayCount = $holidayCountRaw;
        }
        if (array_key_exists('delayCount', $data)) {
            $delayCountRaw = $data['delayCount'];
            if (!is_int($delayCountRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "delayCount" must be int, got %s.', get_debug_type($delayCountRaw)),
                );
            }
            $delayCount = $delayCountRaw;
        }
        if (array_key_exists('pickupDate', $data)) {
            $pickupDateRaw = $data['pickupDate'];
            if (!is_string($pickupDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "pickupDate" must be string, got %s.', get_debug_type($pickupDateRaw)),
                );
            }
            $pickupDate = $pickupDateRaw;
        }
        if (array_key_exists('pickupTime', $data)) {
            $pickupTimeRaw = $data['pickupTime'];
            if (!is_string($pickupTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "pickupTime" must be string, got %s.', get_debug_type($pickupTimeRaw)),
                );
            }
            $pickupTime = $pickupTimeRaw;
        }
        if (array_key_exists('cstccutoffTime', $data)) {
            $cstccutoffTimeRaw = $data['cstccutoffTime'];
            if (!is_string($cstccutoffTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "cstccutoffTime" must be string, got %s.', get_debug_type($cstccutoffTimeRaw)),
                );
            }
            $cstccutoffTime = $cstccutoffTimeRaw;
        }
        if (array_key_exists('poddate', $data) && $data['poddate'] !== null) {
            $poddateRaw = $data['poddate'];
            if (!is_string($poddateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "poddate" must be string, got %s.', get_debug_type($poddateRaw)),
                );
            }
            $poddate = Some::create($poddateRaw);
        }
        if (array_key_exists('poddays', $data) && $data['poddays'] !== null) {
            $poddaysRaw = $data['poddays'];
            if (!is_int($poddaysRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "poddays" must be int, got %s.', get_debug_type($poddaysRaw)),
                );
            }
            $poddays = Some::create($poddaysRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'serviceLevel' => true,
                'serviceLevelDescription' => true,
                'shipDate' => true,
                'deliveryDate' => true,
                'commitTime' => true,
                'deliveryTime' => true,
                'deliveryDayOfWeek' => true,
                'nextDayPickupIndicator' => true,
                'saturdayPickupIndicator' => true,
                'saturdayDeliveryDate' => true,
                'saturdayDeliveryTime' => true,
                'serviceRemarksText' => true,
                'guaranteeIndicator' => true,
                'totalTransitDays' => true,
                'businessTransitDays' => true,
                'restDaysCount' => true,
                'holidayCount' => true,
                'delayCount' => true,
                'pickupDate' => true,
                'pickupTime' => true,
                'cstccutoffTime' => true,
                'poddate' => true,
                'poddays' => true,
            ],
        );
        if ($serviceLevel === null) {
            throw new MalformedDataException('Required property "serviceLevel" is missing from the document.');
        }
        if ($serviceLevelDescription === null) {
            throw new MalformedDataException(
                'Required property "serviceLevelDescription" is missing from the document.',
            );
        }
        if ($shipDate === null) {
            throw new MalformedDataException('Required property "shipDate" is missing from the document.');
        }
        if ($deliveryDate === null) {
            throw new MalformedDataException('Required property "deliveryDate" is missing from the document.');
        }
        if ($commitTime === null) {
            throw new MalformedDataException('Required property "commitTime" is missing from the document.');
        }
        if ($deliveryTime === null) {
            throw new MalformedDataException('Required property "deliveryTime" is missing from the document.');
        }
        if ($deliveryDayOfWeek === null) {
            throw new MalformedDataException('Required property "deliveryDayOfWeek" is missing from the document.');
        }
        if ($nextDayPickupIndicator === null) {
            throw new MalformedDataException(
                'Required property "nextDayPickupIndicator" is missing from the document.',
            );
        }
        if ($saturdayPickupIndicator === null) {
            throw new MalformedDataException(
                'Required property "saturdayPickupIndicator" is missing from the document.',
            );
        }
        if ($guaranteeIndicator === null) {
            throw new MalformedDataException('Required property "guaranteeIndicator" is missing from the document.');
        }
        if ($totalTransitDays === null) {
            throw new MalformedDataException('Required property "totalTransitDays" is missing from the document.');
        }
        if ($businessTransitDays === null) {
            throw new MalformedDataException('Required property "businessTransitDays" is missing from the document.');
        }
        if ($restDaysCount === null) {
            throw new MalformedDataException('Required property "restDaysCount" is missing from the document.');
        }
        if ($holidayCount === null) {
            throw new MalformedDataException('Required property "holidayCount" is missing from the document.');
        }
        if ($delayCount === null) {
            throw new MalformedDataException('Required property "delayCount" is missing from the document.');
        }
        if ($pickupDate === null) {
            throw new MalformedDataException('Required property "pickupDate" is missing from the document.');
        }
        if ($pickupTime === null) {
            throw new MalformedDataException('Required property "pickupTime" is missing from the document.');
        }
        if ($cstccutoffTime === null) {
            throw new MalformedDataException('Required property "cstccutoffTime" is missing from the document.');
        }

        return new self(
            $serviceLevel,
            $serviceLevelDescription,
            $shipDate,
            $deliveryDate,
            $commitTime,
            $deliveryTime,
            $deliveryDayOfWeek,
            $nextDayPickupIndicator,
            $saturdayPickupIndicator,
            $guaranteeIndicator,
            $totalTransitDays,
            $businessTransitDays,
            $restDaysCount,
            $holidayCount,
            $delayCount,
            $pickupDate,
            $pickupTime,
            $cstccutoffTime,
            $saturdayDeliveryDate,
            $saturdayDeliveryTime,
            $serviceRemarksText,
            $poddate,
            $poddays,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['serviceLevel'] = $this->serviceLevel;
        $dataArray['serviceLevelDescription'] = $this->serviceLevelDescription;
        $dataArray['shipDate'] = $this->shipDate;
        $dataArray['deliveryDate'] = $this->deliveryDate;
        $dataArray['commitTime'] = $this->commitTime;
        $dataArray['deliveryTime'] = $this->deliveryTime;
        $dataArray['deliveryDayOfWeek'] = $this->deliveryDayOfWeek;
        $dataArray['nextDayPickupIndicator'] = $this->nextDayPickupIndicator;
        $dataArray['saturdayPickupIndicator'] = $this->saturdayPickupIndicator;
        $saturdayDeliveryDateOption = $this->saturdayDeliveryDate;
        if ($saturdayDeliveryDateOption->isDefined()) {
            $saturdayDeliveryDate = $saturdayDeliveryDateOption->get();
            $dataArray['saturdayDeliveryDate'] = $saturdayDeliveryDate;
        }
        $saturdayDeliveryTimeOption = $this->saturdayDeliveryTime;
        if ($saturdayDeliveryTimeOption->isDefined()) {
            $saturdayDeliveryTime = $saturdayDeliveryTimeOption->get();
            $dataArray['saturdayDeliveryTime'] = $saturdayDeliveryTime;
        }
        $serviceRemarksTextOption = $this->serviceRemarksText;
        if ($serviceRemarksTextOption->isDefined()) {
            $serviceRemarksText = $serviceRemarksTextOption->get();
            $dataArray['serviceRemarksText'] = $serviceRemarksText;
        }
        $dataArray['guaranteeIndicator'] = $this->guaranteeIndicator;
        $dataArray['totalTransitDays'] = $this->totalTransitDays;
        $dataArray['businessTransitDays'] = $this->businessTransitDays;
        $dataArray['restDaysCount'] = $this->restDaysCount;
        $dataArray['holidayCount'] = $this->holidayCount;
        $dataArray['delayCount'] = $this->delayCount;
        $dataArray['pickupDate'] = $this->pickupDate;
        $dataArray['pickupTime'] = $this->pickupTime;
        $dataArray['cstccutoffTime'] = $this->cstccutoffTime;
        $poddateOption = $this->poddate;
        if ($poddateOption->isDefined()) {
            $poddate = $poddateOption->get();
            $dataArray['poddate'] = $poddate;
        }
        $poddaysOption = $this->poddays;
        if ($poddaysOption->isDefined()) {
            $poddays = $poddaysOption->get();
            $dataArray['poddays'] = $poddays;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ServicesBuilder
    {
        return new ServicesBuilder(
            $this->serviceLevel,
            $this->serviceLevelDescription,
            $this->shipDate,
            $this->deliveryDate,
            $this->commitTime,
            $this->deliveryTime,
            $this->deliveryDayOfWeek,
            $this->nextDayPickupIndicator,
            $this->saturdayPickupIndicator,
            $this->guaranteeIndicator,
            $this->totalTransitDays,
            $this->businessTransitDays,
            $this->restDaysCount,
            $this->holidayCount,
            $this->delayCount,
            $this->pickupDate,
            $this->pickupTime,
            $this->cstccutoffTime,
            $this->saturdayDeliveryDate,
            $this->saturdayDeliveryTime,
            $this->serviceRemarksText,
            $this->poddate,
            $this->poddays,
            $this->additionalProperties,
        );
    }
}
