<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see Services}.
 */
final class ServicesBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $saturdayDeliveryDate
     * @param Option<string>           $saturdayDeliveryTime
     * @param Option<string>           $serviceRemarksText
     * @param Option<string>           $poddate
     * @param Option<int>              $poddays
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $serviceLevel,
        private string $serviceLevelDescription,
        private string $shipDate,
        private string $deliveryDate,
        private string $commitTime,
        private string $deliveryTime,
        private string $deliveryDayOfWeek,
        private string $nextDayPickupIndicator,
        private string $saturdayPickupIndicator,
        private string $guaranteeIndicator,
        private int $totalTransitDays,
        private int $businessTransitDays,
        private int $restDaysCount,
        private int $holidayCount,
        private int $delayCount,
        private string $pickupDate,
        private string $pickupTime,
        private string $cstccutoffTime,
        private Option $saturdayDeliveryDate,
        private Option $saturdayDeliveryTime,
        private Option $serviceRemarksText,
        private Option $poddate,
        private Option $poddays,
        private array $additionalProperties,
    ) {
    }

    /**
     * Service level code.
     *
     * Valid domestic service codes: "1DMS","1DAS","1DM","1DA","1DP","2DM","2DA","3DS","GND".
     *
     *   Valid International service codes (not a complete list) ,"01","02","03","05","08","09","10","11","18","19","20","21","22","23","24","25","26","28","29","33","68".
     */
    public function setServiceLevel(string $serviceLevel): self
    {
        $this->serviceLevel = $serviceLevel;

        return $this;
    }

    /**
     * Service name. Examples are: UPS Next Day Air, UPS Ground, UPS Expedited, UPS Worldwide
     * Express Freight.
     */
    public function setServiceLevelDescription(string $serviceLevelDescription): self
    {
        $this->serviceLevelDescription = $serviceLevelDescription;

        return $this;
    }

    /**
     * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). This date may or may not be the UPS business date.
     *
     * Valid Format: YYYY-MM-DD
     */
    public function setShipDate(string $shipDate): self
    {
        $this->shipDate = $shipDate;

        return $this;
    }

    /**
     * Scheduled delivery date.
     *
     * Valid format: YYYY-MM-DD
     */
    public function setDeliveryDate(string $deliveryDate): self
    {
        $this->deliveryDate = $deliveryDate;

        return $this;
    }

    /**
     * Scheduled commit time.
     *
     * For international shipments the value always come back from SE (OPSYS data) but for domestic,
     * value may be used from NRF commit time.
     *
     * Valid format: HH:MM:SS
     */
    public function setCommitTime(string $commitTime): self
    {
        $this->commitTime = $commitTime;

        return $this;
    }

    /**
     * Scheduled Delivery Time, value may be later then commit time.
     *
     * Valid format: HH:MM:SS
     */
    public function setDeliveryTime(string $deliveryTime): self
    {
        $this->deliveryTime = $deliveryTime;

        return $this;
    }

    /**
     * Three character scheduled delivery day of week.
     *
     * Valid values: "MON","TUE","WED","THU","FRI", "SAT"
     */
    public function setDeliveryDayOfWeek(string $deliveryDayOfWeek): self
    {
        $this->deliveryDayOfWeek = $deliveryDayOfWeek;

        return $this;
    }

    /**
     * Returns a "1" if the requested shipped on date was changed. This data is available only for
     * international transactions.
     *
     * When this flag is set, WWDTDisclaimer.getNextDayDisclaimer method could be called to return
     * the next day disclaimer message.
     */
    public function setNextDayPickupIndicator(string $nextDayPickupIndicator): self
    {
        $this->nextDayPickupIndicator = $nextDayPickupIndicator;

        return $this;
    }

    /**
     * Returns "1" if Saturday Pickup is available for an extra charge otherwise it will return "0".
     *
     * When this flag is set, WWDTDisclaimer.getSaturdayPickupDisclaimer method could be called to
     * return the Saturday pickup extra charge message
     */
    public function setSaturdayPickupIndicator(string $saturdayPickupIndicator): self
    {
        $this->saturdayPickupIndicator = $saturdayPickupIndicator;

        return $this;
    }

    /**
     * Return "1" Guaranteed, or "0" Not Guaranteed based on below conditions:
     *
     * If the ship date, delivery date, and system date are not within a defined peak date range,
     * and a value for service guarantee is available in SE (OPSYS data) that will be returned.
     *
     * If the ship date or delivery date or system date are within a defined peak date range and the
     * service is within the list of services to remove guarantees for, "0" wil be returned.
     */
    public function setGuaranteeIndicator(string $guaranteeIndicator): self
    {
        $this->guaranteeIndicator = $guaranteeIndicator;

        return $this;
    }

    /**
     * Available for International requests. Number of calendar days from origin location to
     * destination location. TotalTransitDays = BusinessTransitDays + RestDaysCount + HolidayCount.
     *
     * Defaults to 0.
     */
    public function setTotalTransitDays(int $totalTransitDays): self
    {
        $this->totalTransitDays = $totalTransitDays;

        return $this;
    }

    /**
     * Returns the number of UPS business days from origin location to destination location.
     */
    public function setBusinessTransitDays(int $businessTransitDays): self
    {
        $this->businessTransitDays = $businessTransitDays;

        return $this;
    }

    /**
     * Returns the number of rest days encountered at the origin location. this data is available
     * only for international transactions.
     *
     * Defaults to 0.
     */
    public function setRestDaysCount(int $restDaysCount): self
    {
        $this->restDaysCount = $restDaysCount;

        return $this;
    }

    /**
     * Returns the number of holidays encountered at the origin and destination location, if it
     * effects the time and transit. This data is available only for international transactions.
     *
     * Defaults to 0.
     */
    public function setHolidayCount(int $holidayCount): self
    {
        $this->holidayCount = $holidayCount;

        return $this;
    }

    /**
     * Returns the number of delay needed for customs encounter at the origin or destination
     * location. This data is available only for international transactions.
     *
     * Defaults to 0.
     */
    public function setDelayCount(int $delayCount): self
    {
        $this->delayCount = $delayCount;

        return $this;
    }

    /**
     * Planned pickup date.
     *
     * Note: This value may not equal the shipped on value requested. This could happen when the
     * requested shipped on date is a holiday or for locations needing 24 hour notice before a
     * pickup could be made.
     */
    public function setPickupDate(string $pickupDate): self
    {
        $this->pickupDate = $pickupDate;

        return $this;
    }

    /**
     * Latest possible pickup time. This data is available only for international transactions. If
     * the package was not actually picked by UPS before this time, the services will not meet the
     * guarantee commitment.
     */
    public function setPickupTime(string $pickupTime): self
    {
        $this->pickupTime = $pickupTime;

        return $this;
    }

    /**
     * Latest time a customer can contact UPS CST to be notified for requesting a pickup. This data
     * is available only for international transactions. If customer does not notify UPS for a
     * pickup before this time, the services will not meet the guarantee commitment.
     */
    public function setCstccutoffTime(string $cstccutoffTime): self
    {
        $this->cstccutoffTime = $cstccutoffTime;

        return $this;
    }

    /**
     * Delivery date of Saturday Delivery.
     *
     * Valid Format: YYYY-MM-DD
     */
    public function setSaturdayDeliveryDate(string $saturdayDeliveryDate): self
    {
        $this->saturdayDeliveryDate = Some::create($saturdayDeliveryDate);

        return $this;
    }

    /**
     * Delivery time of Saturday deliver.
     *
     * Valid format: HH:MM:SS
     */
    public function setSaturdayDeliveryTime(string $saturdayDeliveryTime): self
    {
        $this->saturdayDeliveryTime = Some::create($saturdayDeliveryTime);

        return $this;
    }

    /**
     * Service remarks text. The contents of this field will represent text that the back end
     * application/function needs to display to clarify the time in transit calculation.
     */
    public function setServiceRemarksText(string $serviceRemarksText): self
    {
        $this->serviceRemarksText = Some::create($serviceRemarksText);

        return $this;
    }

    /**
     * Returns the date proof of delivery information would be available. This data is available
     * only for international transactions.
     */
    public function setPoddate(string $poddate): self
    {
        $this->poddate = Some::create($poddate);

        return $this;
    }

    /**
     * Returns the number of days proof of delivery information will be available. This data is
     * available only for international transactions.
     */
    public function setPoddays(int $poddays): self
    {
        $this->poddays = Some::create($poddays);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): Services
    {
        return new Services(
            $this->serviceLevel,
            $this->serviceLevelDescription,
            $this->shipDate,
            $this->deliveryDate,
            $this->commitTime,
            $this->deliveryTime,
            $this->deliveryDayOfWeek,
            $this->nextDayPickupIndicator,
            $this->saturdayPickupIndicator,
            $this->guaranteeIndicator,
            $this->totalTransitDays,
            $this->businessTransitDays,
            $this->restDaysCount,
            $this->holidayCount,
            $this->delayCount,
            $this->pickupDate,
            $this->pickupTime,
            $this->cstccutoffTime,
            $this->saturdayDeliveryDate,
            $this->saturdayDeliveryTime,
            $this->serviceRemarksText,
            $this->poddate,
            $this->poddays,
            $this->additionalProperties,
        );
    }
}
