<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see TimeInTransitResponse}.
 */
final class TimeInTransitResponseBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<ValidationList>         $validationList
     * @param Option<list<CandidateAddress>> $destinationPickList
     * @param Option<list<CandidateAddress>> $originPickList
     * @param Option<EmsResponse>            $emsResponse
     * @param array<int|string, mixed>       $additionalProperties
     */
    public function __construct(
        private Option $validationList,
        private Option $destinationPickList,
        private Option $originPickList,
        private Option $emsResponse,
        private array $additionalProperties,
    ) {
    }

    public function setValidationList(ValidationList $validationList): self
    {
        $this->validationList = Some::create($validationList);

        return $this;
    }

    /** @param list<CandidateAddress> $destinationPickList */
    public function setDestinationPickList(array $destinationPickList): self
    {
        $this->destinationPickList = Some::create($destinationPickList);

        return $this;
    }

    /** @param list<CandidateAddress> $originPickList */
    public function setOriginPickList(array $originPickList): self
    {
        $this->originPickList = Some::create($originPickList);

        return $this;
    }

    public function setEmsResponse(EmsResponse $emsResponse): self
    {
        $this->emsResponse = Some::create($emsResponse);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TimeInTransitResponse
    {
        return new TimeInTransitResponse(
            $this->validationList,
            $this->destinationPickList,
            $this->originPickList,
            $this->emsResponse,
            $this->additionalProperties,
        );
    }
}
