<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see TimeInTransitRequest}.
 */
final class TimeInTransitRequestBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<string>           $originStateProvince
     * @param Option<string>           $originCityName
     * @param Option<string>           $originTownName
     * @param Option<string>           $originPostalCode
     * @param Option<string>           $destinationCountryCode
     * @param Option<string>           $destinationStateProvince
     * @param Option<string>           $destinationCityName
     * @param Option<string>           $destinationTownName
     * @param Option<string>           $destinationPostalCode
     * @param Option<string>           $residentialIndicator
     * @param Option<string>           $shipDate
     * @param Option<string>           $shipTime
     * @param Option<float>            $weight
     * @param Option<string>           $weightUnitOfMeasure
     * @param Option<float>            $shipmentContentsValue
     * @param Option<string>           $shipmentContentsCurrencyCode
     * @param Option<string>           $billType
     * @param Option<bool>             $avvFlag
     * @param Option<int>              $numberOfPackages
     * @param Option<int>              $dropOffAtFacilityIndicator
     * @param Option<int>              $holdForPickupIndicator
     * @param Option<bool>             $returnUnfilterdServices
     * @param Option<int>              $maxList
     * @param Option<string>           $premierIndicator
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $originCountryCode,
        private Option $originStateProvince,
        private Option $originCityName,
        private Option $originTownName,
        private Option $originPostalCode,
        private Option $destinationCountryCode,
        private Option $destinationStateProvince,
        private Option $destinationCityName,
        private Option $destinationTownName,
        private Option $destinationPostalCode,
        private Option $residentialIndicator,
        private Option $shipDate,
        private Option $shipTime,
        private Option $weight,
        private Option $weightUnitOfMeasure,
        private Option $shipmentContentsValue,
        private Option $shipmentContentsCurrencyCode,
        private Option $billType,
        private Option $avvFlag,
        private Option $numberOfPackages,
        private Option $dropOffAtFacilityIndicator,
        private Option $holdForPickupIndicator,
        private Option $returnUnfilterdServices,
        private Option $maxList,
        private Option $premierIndicator,
        private array $additionalProperties,
    ) {
    }

    /**
     * The country code of the origin shipment. Valid Values: Must conform to the ISO-defined,
     * two-letter country or territory codes. Refer to Country or Territory Codes in the Appendix
     * above for valid values.
     */
    public function setOriginCountryCode(string $originCountryCode): self
    {
        $this->originCountryCode = $originCountryCode;

        return $this;
    }

    /**
     * The shipment origin state or province. For U.S. addresses, the value must be a valid
     * 2-character value (per U.S. Mail standards) For non-U.S. addresses the full State or Province
     * name should be provided.
     */
    public function setOriginStateProvince(string $originStateProvince): self
    {
        $this->originStateProvince = Some::create($originStateProvince);

        return $this;
    }

    /**
     * The shipment origin city. Required for International requests for those countries that do not
     * utilize postal codes.
     */
    public function setOriginCityName(string $originCityName): self
    {
        $this->originCityName = Some::create($originCityName);

        return $this;
    }

    /**
     * The shipment origin town. Town is a subdivision of city.
     */
    public function setOriginTownName(string $originTownName): self
    {
        $this->originTownName = Some::create($originTownName);

        return $this;
    }

    /**
     * Required for Domestic requests. The shipment origin postal code. Either the 5, or 9-digit US
     * zip codes must be used for U.S. addresses. For non-U.S. addresses, this is recommended for
     * all countries that utilize postal codes.
     */
    public function setOriginPostalCode(string $originPostalCode): self
    {
        $this->originPostalCode = Some::create($originPostalCode);

        return $this;
    }

    /**
     * The country code of the destination. Valid values: Must conform to ISO-defined country codes.
     */
    public function setDestinationCountryCode(string $destinationCountryCode): self
    {
        $this->destinationCountryCode = Some::create($destinationCountryCode);

        return $this;
    }

    /**
     * The shipment destination state or province. For U.S. addresses, the value must be a valid
     * 2-character value (per U.S. Mail standards). For non-U.S. addresses the full State or
     * Province name should be provided.
     */
    public function setDestinationStateProvince(string $destinationStateProvince): self
    {
        $this->destinationStateProvince = Some::create($destinationStateProvince);

        return $this;
    }

    /**
     * The shipment destination city. Required for International Requests for those countries that
     * do not utilize postal codes.
     */
    public function setDestinationCityName(string $destinationCityName): self
    {
        $this->destinationCityName = Some::create($destinationCityName);

        return $this;
    }

    /**
     * The shipment destination town. Town is a subdivision of city.
     */
    public function setDestinationTownName(string $destinationTownName): self
    {
        $this->destinationTownName = Some::create($destinationTownName);

        return $this;
    }

    /**
     * The shipment destination postal code. Required for Domestic requests. Either 5, or 9-digit
     * U.S. zip codes must be used for U.S. addresses. For non-U.S. addresses, this is recommended
     * for all countries that utilize postal codes.
     */
    public function setDestinationPostalCode(string $destinationPostalCode): self
    {
        $this->destinationPostalCode = Some::create($destinationPostalCode);

        return $this;
    }

    /**
     * Indicates if address is residential or commercial. Required for Domestic requests.
     *
     * Valid values: "01", "02"
     *
     * 01 = Residential 02 = Commercial
     *
     * Defaults to commercial for International Requests.
     */
    public function setResidentialIndicator(string $residentialIndicator): self
    {
        $this->residentialIndicator = Some::create($residentialIndicator);

        return $this;
    }

    /**
     * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). Allowed range is up to 60 days in future and 35 days in past. This date may or may
     * not be the UPS business date.
     *
     * Format is YYYY-MM-DD.
     *
     * YYYY = 4 digit year;
     *
     * MM = 2 digit month, valid values 01-12;
     *
     * DD = 2 digit day of month, valid values 01-31 If no value is provided, defaults to current
     * system date.
     */
    public function setShipDate(string $shipDate): self
    {
        $this->shipDate = Some::create($shipDate);

        return $this;
    }

    /**
     * The time the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). Format is HH:MM:SS.
     *
     * Defaults to current time if not provided.
     */
    public function setShipTime(string $shipTime): self
    {
        $this->shipTime = Some::create($shipTime);

        return $this;
    }

    /**
     * The weight of the shipment. Required for International requests.
     *
     * Note: If decimal values are used, valid values will be rounded to the tenths.
     *
     * Note: Maximum value is 70 kilograms or 150 pounds.
     */
    public function setWeight(float $weight): self
    {
        $this->weight = Some::create($weight);

        return $this;
    }

    /**
     * Required for International requests and when weight value is provided.
     *
     * Valid Values: "LBS", "KGS"
     */
    public function setWeightUnitOfMeasure(string $weightUnitOfMeasure): self
    {
        $this->weightUnitOfMeasure = Some::create($weightUnitOfMeasure);

        return $this;
    }

    /**
     * The monetary value of shipment contents.
     *
     * Required when origin country does not equal destination country and BillType is 03
     * (non-documented) or 04 (WWEF)
     *
     * Required when origin country does not equal destination country, and destination country =
     * CA, and BillType = 02 (document).
     *
     * Note: If decimal values are used, valid values will be rounded to the tenths.
     */
    public function setShipmentContentsValue(float $shipmentContentsValue): self
    {
        $this->shipmentContentsValue = Some::create($shipmentContentsValue);

        return $this;
    }

    /**
     * The unit of currency used for values. Required if ShipmentContentsValue is populated. Valid
     * value: must conform to ISO standards.
     */
    public function setShipmentContentsCurrencyCode(string $shipmentContentsCurrencyCode): self
    {
        $this->shipmentContentsCurrencyCode = Some::create($shipmentContentsCurrencyCode);

        return $this;
    }

    /**
     * Required for International Requests. Valid values: "02","03","04" 02 - Document 03 - Non
     * Document 04 - WWEF (Pallet).
     */
    public function setBillType(string $billType): self
    {
        $this->billType = Some::create($billType);

        return $this;
    }

    /**
     * Used to bypass address validation when the address has already been validated by the calling
     * application.
     *
     * Valid values: true, false
     *
     * Defaults to true Note: not to be exposed to external customers.
     */
    public function setAvvFlag(bool $avvFlag): self
    {
        $this->avvFlag = Some::create($avvFlag);

        return $this;
    }

    /**
     * Sets the number of packages in shipment. Default value is 1.
     */
    public function setNumberOfPackages(int $numberOfPackages): self
    {
        $this->numberOfPackages = Some::create($numberOfPackages);

        return $this;
    }

    /**
     * Sets the indicator for an international Freight Pallet shipment that is going to be dropped
     * off by shipper to a UPS facility. The indicator is used when the Bill Type is "04".
     *
     * Valid values: "0", "1".
     *
     * 0 = WWDTProcessIF.PICKUP_BY_UPS 1 = WWDTProcessIf.DROPOFF_BY_SHIPPER
     *
     * The default value is "0"
     */
    public function setDropOffAtFacilityIndicator(int $dropOffAtFacilityIndicator): self
    {
        $this->dropOffAtFacilityIndicator = Some::create($dropOffAtFacilityIndicator);

        return $this;
    }

    /**
     * Sets the indicator for an international Freight Pallet shipment that is going to be pick-up
     * by consignee in a destination facility. The indicator is used when the Bill Type is "04".
     *
     * Valid values: "0", "1".
     *
     * 0 = WWDTProcessIF.DELIVERY_BY_UPS 1 = WWDTProcessIf.PICKUP_BY_CONSIGNEE
     *
     * The default value is "0"
     */
    public function setHoldForPickupIndicator(int $holdForPickupIndicator): self
    {
        $this->holdForPickupIndicator = Some::create($holdForPickupIndicator);

        return $this;
    }

    /**
     * Used to get back a full list of services - bypassing current WWDT business rules to remove
     * services from the list being returned to clients for US domestic that are slower than UPS
     * Ground.
     *
     * Default value is false.
     */
    public function setReturnUnfilterdServices(bool $returnUnfilterdServices): self
    {
        $this->returnUnfilterdServices = Some::create($returnUnfilterdServices);

        return $this;
    }

    /**
     * Sets the limit for the number of candidates returned in candidate list.
     *
     * Default value is 200.
     */
    public function setMaxList(int $maxList): self
    {
        $this->maxList = Some::create($maxList);

        return $this;
    }

    /**
     * Sets the indicator for premier time in transit when the shipment contains a premier package.
     *
     * Valid values: “00”, “01”.
     *
     * 00 = Non-premier time in transit.
     *
     * 01 = Premier time in transit.
     *
     * The default value is “00”.
     */
    public function setPremierIndicator(string $premierIndicator): self
    {
        $this->premierIndicator = Some::create($premierIndicator);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): TimeInTransitRequest
    {
        return new TimeInTransitRequest(
            $this->originCountryCode,
            $this->originStateProvince,
            $this->originCityName,
            $this->originTownName,
            $this->originPostalCode,
            $this->destinationCountryCode,
            $this->destinationStateProvince,
            $this->destinationCityName,
            $this->destinationTownName,
            $this->destinationPostalCode,
            $this->residentialIndicator,
            $this->shipDate,
            $this->shipTime,
            $this->weight,
            $this->weightUnitOfMeasure,
            $this->shipmentContentsValue,
            $this->shipmentContentsCurrencyCode,
            $this->billType,
            $this->avvFlag,
            $this->numberOfPackages,
            $this->dropOffAtFacilityIndicator,
            $this->holdForPickupIndicator,
            $this->returnUnfilterdServices,
            $this->maxList,
            $this->premierIndicator,
            $this->additionalProperties,
        );
    }
}
