<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function sprintf;

final readonly class TimeInTransitResponse implements SelfNormalizingModel
{
    /**
     * @param Option<ValidationList>         $validationList
     * @param Option<list<CandidateAddress>> $destinationPickList
     * @param Option<list<CandidateAddress>> $originPickList
     * @param Option<EmsResponse>            $emsResponse
     * @param array<int|string, mixed>       $additionalProperties
     */
    public function __construct(
        private Option $validationList,
        private Option $destinationPickList,
        private Option $originPickList,
        private Option $emsResponse,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): TimeInTransitResponseBuilder
    {
        return new TimeInTransitResponseBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /** @return Option<ValidationList> */
    public function getValidationList(): Option
    {
        return $this->validationList;
    }

    /** @return Option<list<CandidateAddress>> */
    public function getDestinationPickList(): Option
    {
        return $this->destinationPickList;
    }

    /** @return Option<list<CandidateAddress>> */
    public function getOriginPickList(): Option
    {
        return $this->originPickList;
    }

    /** @return Option<EmsResponse> */
    public function getEmsResponse(): Option
    {
        return $this->emsResponse;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $validationList = None::create();
        $destinationPickList = None::create();
        $originPickList = None::create();
        $emsResponse = None::create();
        if (array_key_exists('validationList', $data) && $data['validationList'] !== null) {
            $validationListRaw = $data['validationList'];
            if (!is_array($validationListRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "validationList" must be object, got %s.', get_debug_type($validationListRaw)),
                );
            }
            /** @var array<string, mixed> $validationListRawTyped */
            $validationListRawTyped = $validationListRaw;
            $validationList = Some::create(ValidationList::fromArray($validationListRawTyped));
        }
        if (array_key_exists('destinationPickList', $data) && $data['destinationPickList'] !== null) {
            $destinationPickListRaw = $data['destinationPickList'];
            if (!(is_array($destinationPickListRaw) && array_is_list($destinationPickListRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationPickList" must be list, got %s.',
                        get_debug_type($destinationPickListRaw),
                    ),
                );
            }
            $destinationPickList = Some::create(array_map(static function (mixed $value): CandidateAddress {
                if (!is_array($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value)),
                    );
                }
                /** @var non-empty-array<string, mixed> $valueTyped */
                $valueTyped = $value;

                return CandidateAddress::fromArray($valueTyped);
            }, $destinationPickListRaw));
        }
        if (array_key_exists('originPickList', $data) && $data['originPickList'] !== null) {
            $originPickListRaw = $data['originPickList'];
            if (!(is_array($originPickListRaw) && array_is_list($originPickListRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "originPickList" must be list, got %s.', get_debug_type($originPickListRaw)),
                );
            }
            $originPickList = Some::create(array_map(static function (mixed $value_1): CandidateAddress {
                if (!is_array($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be object, got %s.', get_debug_type($value_1)),
                    );
                }
                /** @var non-empty-array<string, mixed> $value_1Typed */
                $value_1Typed = $value_1;

                return CandidateAddress::fromArray($value_1Typed);
            }, $originPickListRaw));
        }
        if (array_key_exists('emsResponse', $data) && $data['emsResponse'] !== null) {
            $emsResponseRaw = $data['emsResponse'];
            if (!is_array($emsResponseRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "emsResponse" must be object, got %s.', get_debug_type($emsResponseRaw)),
                );
            }
            /** @var non-empty-array<string, mixed> $emsResponseRawTyped */
            $emsResponseRawTyped = $emsResponseRaw;
            $emsResponse = Some::create(EmsResponse::fromArray($emsResponseRawTyped));
        }
        $additionalProperties = array_diff_key(
            $data,
            ['validationList' => true, 'destinationPickList' => true, 'originPickList' => true, 'emsResponse' => true],
        );

        return new self($validationList, $destinationPickList, $originPickList, $emsResponse, $additionalProperties);
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        return $this->normalize(NormalizationTarget::PhpArray);
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->normalize(NormalizationTarget::Json);
    }

    /** @return array<int|string, mixed> */
    private function normalize(NormalizationTarget $normalizationTarget): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $validationListOption = $this->validationList;
        if ($validationListOption->isDefined()) {
            $validationList = $validationListOption->get();
            $dataArray['validationList'] = $normalizationTarget->model($validationList);
        }
        $destinationPickListOption = $this->destinationPickList;
        if ($destinationPickListOption->isDefined()) {
            $destinationPickList = $destinationPickListOption->get();
            $values = [];
            foreach ($destinationPickList as $value) {
                $values[] = $normalizationTarget->model($value);
            }
            $dataArray['destinationPickList'] = $values;
        }
        $originPickListOption = $this->originPickList;
        if ($originPickListOption->isDefined()) {
            $originPickList = $originPickListOption->get();
            $values_1 = [];
            foreach ($originPickList as $value_1) {
                $values_1[] = $normalizationTarget->model($value_1);
            }
            $dataArray['originPickList'] = $values_1;
        }
        $emsResponseOption = $this->emsResponse;
        if ($emsResponseOption->isDefined()) {
            $emsResponse = $emsResponseOption->get();
            $dataArray['emsResponse'] = $normalizationTarget->model($emsResponse);
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    public function toBuilder(): TimeInTransitResponseBuilder
    {
        return new TimeInTransitResponseBuilder(
            $this->validationList,
            $this->destinationPickList,
            $this->originPickList,
            $this->emsResponse,
            $this->additionalProperties,
        );
    }
}
