<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_key_exists;
use function get_debug_type;
use function is_bool;
use function is_float;
use function is_int;
use function is_string;
use function sprintf;

final readonly class TimeInTransitRequest implements SelfNormalizingModel
{
    /**
     * @param Option<string>           $originStateProvince
     * @param Option<string>           $originCityName
     * @param Option<string>           $originTownName
     * @param Option<string>           $originPostalCode
     * @param Option<string>           $destinationCountryCode
     * @param Option<string>           $destinationStateProvince
     * @param Option<string>           $destinationCityName
     * @param Option<string>           $destinationTownName
     * @param Option<string>           $destinationPostalCode
     * @param Option<string>           $residentialIndicator
     * @param Option<string>           $shipDate
     * @param Option<string>           $shipTime
     * @param Option<float>            $weight
     * @param Option<string>           $weightUnitOfMeasure
     * @param Option<float>            $shipmentContentsValue
     * @param Option<string>           $shipmentContentsCurrencyCode
     * @param Option<string>           $billType
     * @param Option<bool>             $avvFlag
     * @param Option<int>              $numberOfPackages
     * @param Option<int>              $dropOffAtFacilityIndicator
     * @param Option<int>              $holdForPickupIndicator
     * @param Option<bool>             $returnUnfilterdServices
     * @param Option<int>              $maxList
     * @param Option<string>           $premierIndicator
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private string $originCountryCode,
        private Option $originStateProvince,
        private Option $originCityName,
        private Option $originTownName,
        private Option $originPostalCode,
        private Option $destinationCountryCode,
        private Option $destinationStateProvince,
        private Option $destinationCityName,
        private Option $destinationTownName,
        private Option $destinationPostalCode,
        private Option $residentialIndicator,
        private Option $shipDate,
        private Option $shipTime,
        private Option $weight,
        private Option $weightUnitOfMeasure,
        private Option $shipmentContentsValue,
        private Option $shipmentContentsCurrencyCode,
        private Option $billType,
        private Option $avvFlag,
        private Option $numberOfPackages,
        private Option $dropOffAtFacilityIndicator,
        private Option $holdForPickupIndicator,
        private Option $returnUnfilterdServices,
        private Option $maxList,
        private Option $premierIndicator,
        private array $additionalProperties,
    ) {
    }

    public static function builder(string $originCountryCode): TimeInTransitRequestBuilder
    {
        return new TimeInTransitRequestBuilder(
            $originCountryCode,
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            None::create(),
            [],
        );
    }

    /**
     * The country code of the origin shipment. Valid Values: Must conform to the ISO-defined,
     * two-letter country or territory codes. Refer to Country or Territory Codes in the Appendix
     * above for valid values.
     */
    public function getOriginCountryCode(): string
    {
        return $this->originCountryCode;
    }

    /**
     * The shipment origin state or province. For U.S. addresses, the value must be a valid
     * 2-character value (per U.S. Mail standards) For non-U.S. addresses the full State or Province
     * name should be provided.
     *
     * @return Option<string>
     */
    public function getOriginStateProvince(): Option
    {
        return $this->originStateProvince;
    }

    /**
     * The shipment origin city. Required for International requests for those countries that do not
     * utilize postal codes.
     *
     * @return Option<string>
     */
    public function getOriginCityName(): Option
    {
        return $this->originCityName;
    }

    /**
     * The shipment origin town. Town is a subdivision of city.
     *
     * @return Option<string>
     */
    public function getOriginTownName(): Option
    {
        return $this->originTownName;
    }

    /**
     * Required for Domestic requests. The shipment origin postal code. Either the 5, or 9-digit US
     * zip codes must be used for U.S. addresses. For non-U.S. addresses, this is recommended for
     * all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getOriginPostalCode(): Option
    {
        return $this->originPostalCode;
    }

    /**
     * The country code of the destination. Valid values: Must conform to ISO-defined country codes.
     *
     * @return Option<string>
     */
    public function getDestinationCountryCode(): Option
    {
        return $this->destinationCountryCode;
    }

    /**
     * The shipment destination state or province. For U.S. addresses, the value must be a valid
     * 2-character value (per U.S. Mail standards). For non-U.S. addresses the full State or
     * Province name should be provided.
     *
     * @return Option<string>
     */
    public function getDestinationStateProvince(): Option
    {
        return $this->destinationStateProvince;
    }

    /**
     * The shipment destination city. Required for International Requests for those countries that
     * do not utilize postal codes.
     *
     * @return Option<string>
     */
    public function getDestinationCityName(): Option
    {
        return $this->destinationCityName;
    }

    /**
     * The shipment destination town. Town is a subdivision of city.
     *
     * @return Option<string>
     */
    public function getDestinationTownName(): Option
    {
        return $this->destinationTownName;
    }

    /**
     * The shipment destination postal code. Required for Domestic requests. Either 5, or 9-digit
     * U.S. zip codes must be used for U.S. addresses. For non-U.S. addresses, this is recommended
     * for all countries that utilize postal codes.
     *
     * @return Option<string>
     */
    public function getDestinationPostalCode(): Option
    {
        return $this->destinationPostalCode;
    }

    /**
     * Indicates if address is residential or commercial. Required for Domestic requests.
     *
     * Valid values: "01", "02"
     *
     * 01 = Residential 02 = Commercial
     *
     * Defaults to commercial for International Requests.
     *
     * @return Option<string>
     */
    public function getResidentialIndicator(): Option
    {
        return $this->residentialIndicator;
    }

    /**
     * The date the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). Allowed range is up to 60 days in future and 35 days in past. This date may or may
     * not be the UPS business date.
     *
     * Format is YYYY-MM-DD.
     *
     * YYYY = 4 digit year;
     *
     * MM = 2 digit month, valid values 01-12;
     *
     * DD = 2 digit day of month, valid values 01-31 If no value is provided, defaults to current
     * system date.
     *
     * @return Option<string>
     */
    public function getShipDate(): Option
    {
        return $this->shipDate;
    }

    /**
     * The time the shipment is tendered to UPS for shipping (can be dropped off at UPS or picked up
     * by UPS). Format is HH:MM:SS.
     *
     * Defaults to current time if not provided.
     *
     * @return Option<string>
     */
    public function getShipTime(): Option
    {
        return $this->shipTime;
    }

    /**
     * The weight of the shipment. Required for International requests.
     *
     * Note: If decimal values are used, valid values will be rounded to the tenths.
     *
     * Note: Maximum value is 70 kilograms or 150 pounds.
     *
     * @return Option<float>
     */
    public function getWeight(): Option
    {
        return $this->weight;
    }

    /**
     * Required for International requests and when weight value is provided.
     *
     * Valid Values: "LBS", "KGS"
     *
     * @return Option<string>
     */
    public function getWeightUnitOfMeasure(): Option
    {
        return $this->weightUnitOfMeasure;
    }

    /**
     * The monetary value of shipment contents.
     *
     * Required when origin country does not equal destination country and BillType is 03
     * (non-documented) or 04 (WWEF)
     *
     * Required when origin country does not equal destination country, and destination country =
     * CA, and BillType = 02 (document).
     *
     * Note: If decimal values are used, valid values will be rounded to the tenths.
     *
     * @return Option<float>
     */
    public function getShipmentContentsValue(): Option
    {
        return $this->shipmentContentsValue;
    }

    /**
     * The unit of currency used for values. Required if ShipmentContentsValue is populated. Valid
     * value: must conform to ISO standards.
     *
     * @return Option<string>
     */
    public function getShipmentContentsCurrencyCode(): Option
    {
        return $this->shipmentContentsCurrencyCode;
    }

    /**
     * Required for International Requests. Valid values: "02","03","04" 02 - Document 03 - Non
     * Document 04 - WWEF (Pallet).
     *
     * @return Option<string>
     */
    public function getBillType(): Option
    {
        return $this->billType;
    }

    /**
     * Used to bypass address validation when the address has already been validated by the calling
     * application.
     *
     * Valid values: true, false
     *
     * Defaults to true Note: not to be exposed to external customers.
     *
     * @return Option<bool>
     */
    public function getAvvFlag(): Option
    {
        return $this->avvFlag;
    }

    /**
     * Sets the number of packages in shipment. Default value is 1.
     *
     * @return Option<int>
     */
    public function getNumberOfPackages(): Option
    {
        return $this->numberOfPackages;
    }

    /**
     * Sets the indicator for an international Freight Pallet shipment that is going to be dropped
     * off by shipper to a UPS facility. The indicator is used when the Bill Type is "04".
     *
     * Valid values: "0", "1".
     *
     * 0 = WWDTProcessIF.PICKUP_BY_UPS 1 = WWDTProcessIf.DROPOFF_BY_SHIPPER
     *
     * The default value is "0"
     *
     * @return Option<int>
     */
    public function getDropOffAtFacilityIndicator(): Option
    {
        return $this->dropOffAtFacilityIndicator;
    }

    /**
     * Sets the indicator for an international Freight Pallet shipment that is going to be pick-up
     * by consignee in a destination facility. The indicator is used when the Bill Type is "04".
     *
     * Valid values: "0", "1".
     *
     * 0 = WWDTProcessIF.DELIVERY_BY_UPS 1 = WWDTProcessIf.PICKUP_BY_CONSIGNEE
     *
     * The default value is "0"
     *
     * @return Option<int>
     */
    public function getHoldForPickupIndicator(): Option
    {
        return $this->holdForPickupIndicator;
    }

    /**
     * Used to get back a full list of services - bypassing current WWDT business rules to remove
     * services from the list being returned to clients for US domestic that are slower than UPS
     * Ground.
     *
     * Default value is false.
     *
     * @return Option<bool>
     */
    public function getReturnUnfilterdServices(): Option
    {
        return $this->returnUnfilterdServices;
    }

    /**
     * Sets the limit for the number of candidates returned in candidate list.
     *
     * Default value is 200.
     *
     * @return Option<int>
     */
    public function getMaxList(): Option
    {
        return $this->maxList;
    }

    /**
     * Sets the indicator for premier time in transit when the shipment contains a premier package.
     *
     * Valid values: “00”, “01”.
     *
     * 00 = Non-premier time in transit.
     *
     * 01 = Premier time in transit.
     *
     * The default value is “00”.
     *
     * @return Option<string>
     */
    public function getPremierIndicator(): Option
    {
        return $this->premierIndicator;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $originCountryCode = null;
        $originStateProvince = None::create();
        $originCityName = None::create();
        $originTownName = None::create();
        $originPostalCode = None::create();
        $destinationCountryCode = None::create();
        $destinationStateProvince = None::create();
        $destinationCityName = None::create();
        $destinationTownName = None::create();
        $destinationPostalCode = None::create();
        $residentialIndicator = None::create();
        $shipDate = None::create();
        $shipTime = None::create();
        $weight = None::create();
        $weightUnitOfMeasure = None::create();
        $shipmentContentsValue = None::create();
        $shipmentContentsCurrencyCode = None::create();
        $billType = None::create();
        $avvFlag = None::create();
        $numberOfPackages = None::create();
        $dropOffAtFacilityIndicator = None::create();
        $holdForPickupIndicator = None::create();
        $returnUnfilterdServices = None::create();
        $maxList = None::create();
        $premierIndicator = None::create();
        if (array_key_exists('weight', $data) && is_int($data['weight'])) {
            $data['weight'] = (float) $data['weight'];
        }
        if (array_key_exists('shipmentContentsValue', $data) && is_int($data['shipmentContentsValue'])) {
            $data['shipmentContentsValue'] = (float) $data['shipmentContentsValue'];
        }
        if (array_key_exists('originCountryCode', $data)) {
            $originCountryCodeRaw = $data['originCountryCode'];
            if (!is_string($originCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originCountryCode" must be string, got %s.',
                        get_debug_type($originCountryCodeRaw),
                    ),
                );
            }
            $originCountryCode = $originCountryCodeRaw;
        }
        if (array_key_exists('originStateProvince', $data) && $data['originStateProvince'] !== null) {
            $originStateProvinceRaw = $data['originStateProvince'];
            if (!is_string($originStateProvinceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originStateProvince" must be string, got %s.',
                        get_debug_type($originStateProvinceRaw),
                    ),
                );
            }
            $originStateProvince = Some::create($originStateProvinceRaw);
        }
        if (array_key_exists('originCityName', $data) && $data['originCityName'] !== null) {
            $originCityNameRaw = $data['originCityName'];
            if (!is_string($originCityNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "originCityName" must be string, got %s.', get_debug_type($originCityNameRaw)),
                );
            }
            $originCityName = Some::create($originCityNameRaw);
        }
        if (array_key_exists('originTownName', $data) && $data['originTownName'] !== null) {
            $originTownNameRaw = $data['originTownName'];
            if (!is_string($originTownNameRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "originTownName" must be string, got %s.', get_debug_type($originTownNameRaw)),
                );
            }
            $originTownName = Some::create($originTownNameRaw);
        }
        if (array_key_exists('originPostalCode', $data) && $data['originPostalCode'] !== null) {
            $originPostalCodeRaw = $data['originPostalCode'];
            if (!is_string($originPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "originPostalCode" must be string, got %s.',
                        get_debug_type($originPostalCodeRaw),
                    ),
                );
            }
            $originPostalCode = Some::create($originPostalCodeRaw);
        }
        if (array_key_exists('destinationCountryCode', $data) && $data['destinationCountryCode'] !== null) {
            $destinationCountryCodeRaw = $data['destinationCountryCode'];
            if (!is_string($destinationCountryCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationCountryCode" must be string, got %s.',
                        get_debug_type($destinationCountryCodeRaw),
                    ),
                );
            }
            $destinationCountryCode = Some::create($destinationCountryCodeRaw);
        }
        if (array_key_exists('destinationStateProvince', $data) && $data['destinationStateProvince'] !== null) {
            $destinationStateProvinceRaw = $data['destinationStateProvince'];
            if (!is_string($destinationStateProvinceRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationStateProvince" must be string, got %s.',
                        get_debug_type($destinationStateProvinceRaw),
                    ),
                );
            }
            $destinationStateProvince = Some::create($destinationStateProvinceRaw);
        }
        if (array_key_exists('destinationCityName', $data) && $data['destinationCityName'] !== null) {
            $destinationCityNameRaw = $data['destinationCityName'];
            if (!is_string($destinationCityNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationCityName" must be string, got %s.',
                        get_debug_type($destinationCityNameRaw),
                    ),
                );
            }
            $destinationCityName = Some::create($destinationCityNameRaw);
        }
        if (array_key_exists('destinationTownName', $data) && $data['destinationTownName'] !== null) {
            $destinationTownNameRaw = $data['destinationTownName'];
            if (!is_string($destinationTownNameRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationTownName" must be string, got %s.',
                        get_debug_type($destinationTownNameRaw),
                    ),
                );
            }
            $destinationTownName = Some::create($destinationTownNameRaw);
        }
        if (array_key_exists('destinationPostalCode', $data) && $data['destinationPostalCode'] !== null) {
            $destinationPostalCodeRaw = $data['destinationPostalCode'];
            if (!is_string($destinationPostalCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationPostalCode" must be string, got %s.',
                        get_debug_type($destinationPostalCodeRaw),
                    ),
                );
            }
            $destinationPostalCode = Some::create($destinationPostalCodeRaw);
        }
        if (array_key_exists('residentialIndicator', $data) && $data['residentialIndicator'] !== null) {
            $residentialIndicatorRaw = $data['residentialIndicator'];
            if (!is_string($residentialIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "residentialIndicator" must be string, got %s.',
                        get_debug_type($residentialIndicatorRaw),
                    ),
                );
            }
            $residentialIndicator = Some::create($residentialIndicatorRaw);
        }
        if (array_key_exists('shipDate', $data) && $data['shipDate'] !== null) {
            $shipDateRaw = $data['shipDate'];
            if (!is_string($shipDateRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipDate" must be string, got %s.', get_debug_type($shipDateRaw)),
                );
            }
            $shipDate = Some::create($shipDateRaw);
        }
        if (array_key_exists('shipTime', $data) && $data['shipTime'] !== null) {
            $shipTimeRaw = $data['shipTime'];
            if (!is_string($shipTimeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "shipTime" must be string, got %s.', get_debug_type($shipTimeRaw)),
                );
            }
            $shipTime = Some::create($shipTimeRaw);
        }
        if (array_key_exists('weight', $data) && $data['weight'] !== null) {
            $weightRaw = $data['weight'];
            if (!(is_float($weightRaw) || is_int($weightRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "weight" must be number, got %s.', get_debug_type($weightRaw)),
                );
            }
            $weight = Some::create((float) $weightRaw);
        }
        if (array_key_exists('weightUnitOfMeasure', $data) && $data['weightUnitOfMeasure'] !== null) {
            $weightUnitOfMeasureRaw = $data['weightUnitOfMeasure'];
            if (!is_string($weightUnitOfMeasureRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "weightUnitOfMeasure" must be string, got %s.',
                        get_debug_type($weightUnitOfMeasureRaw),
                    ),
                );
            }
            $weightUnitOfMeasure = Some::create($weightUnitOfMeasureRaw);
        }
        if (array_key_exists('shipmentContentsValue', $data) && $data['shipmentContentsValue'] !== null) {
            $shipmentContentsValueRaw = $data['shipmentContentsValue'];
            if (!(is_float($shipmentContentsValueRaw) || is_int($shipmentContentsValueRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipmentContentsValue" must be number, got %s.',
                        get_debug_type($shipmentContentsValueRaw),
                    ),
                );
            }
            $shipmentContentsValue = Some::create((float) $shipmentContentsValueRaw);
        }
        if (array_key_exists('shipmentContentsCurrencyCode', $data) && $data['shipmentContentsCurrencyCode'] !== null) {
            $shipmentContentsCurrencyCodeRaw = $data['shipmentContentsCurrencyCode'];
            if (!is_string($shipmentContentsCurrencyCodeRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "shipmentContentsCurrencyCode" must be string, got %s.',
                        get_debug_type($shipmentContentsCurrencyCodeRaw),
                    ),
                );
            }
            $shipmentContentsCurrencyCode = Some::create($shipmentContentsCurrencyCodeRaw);
        }
        if (array_key_exists('billType', $data) && $data['billType'] !== null) {
            $billTypeRaw = $data['billType'];
            if (!is_string($billTypeRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "billType" must be string, got %s.', get_debug_type($billTypeRaw)),
                );
            }
            $billType = Some::create($billTypeRaw);
        }
        if (array_key_exists('avvFlag', $data) && $data['avvFlag'] !== null) {
            $avvFlagRaw = $data['avvFlag'];
            if (!is_bool($avvFlagRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "avvFlag" must be bool, got %s.', get_debug_type($avvFlagRaw)),
                );
            }
            $avvFlag = Some::create($avvFlagRaw);
        }
        if (array_key_exists('numberOfPackages', $data) && $data['numberOfPackages'] !== null) {
            $numberOfPackagesRaw = $data['numberOfPackages'];
            if (!is_int($numberOfPackagesRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "numberOfPackages" must be int, got %s.', get_debug_type($numberOfPackagesRaw)),
                );
            }
            $numberOfPackages = Some::create($numberOfPackagesRaw);
        }
        if (array_key_exists('dropOffAtFacilityIndicator', $data) && $data['dropOffAtFacilityIndicator'] !== null) {
            $dropOffAtFacilityIndicatorRaw = $data['dropOffAtFacilityIndicator'];
            if (!is_int($dropOffAtFacilityIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "dropOffAtFacilityIndicator" must be int, got %s.',
                        get_debug_type($dropOffAtFacilityIndicatorRaw),
                    ),
                );
            }
            $dropOffAtFacilityIndicator = Some::create($dropOffAtFacilityIndicatorRaw);
        }
        if (array_key_exists('holdForPickupIndicator', $data) && $data['holdForPickupIndicator'] !== null) {
            $holdForPickupIndicatorRaw = $data['holdForPickupIndicator'];
            if (!is_int($holdForPickupIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "holdForPickupIndicator" must be int, got %s.',
                        get_debug_type($holdForPickupIndicatorRaw),
                    ),
                );
            }
            $holdForPickupIndicator = Some::create($holdForPickupIndicatorRaw);
        }
        if (array_key_exists('returnUnfilterdServices', $data) && $data['returnUnfilterdServices'] !== null) {
            $returnUnfilterdServicesRaw = $data['returnUnfilterdServices'];
            if (!is_bool($returnUnfilterdServicesRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "returnUnfilterdServices" must be bool, got %s.',
                        get_debug_type($returnUnfilterdServicesRaw),
                    ),
                );
            }
            $returnUnfilterdServices = Some::create($returnUnfilterdServicesRaw);
        }
        if (array_key_exists('maxList', $data) && $data['maxList'] !== null) {
            $maxListRaw = $data['maxList'];
            if (!is_int($maxListRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "maxList" must be int, got %s.', get_debug_type($maxListRaw)),
                );
            }
            $maxList = Some::create($maxListRaw);
        }
        if (array_key_exists('premierIndicator', $data) && $data['premierIndicator'] !== null) {
            $premierIndicatorRaw = $data['premierIndicator'];
            if (!is_string($premierIndicatorRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "premierIndicator" must be string, got %s.',
                        get_debug_type($premierIndicatorRaw),
                    ),
                );
            }
            $premierIndicator = Some::create($premierIndicatorRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'originCountryCode' => true,
                'originStateProvince' => true,
                'originCityName' => true,
                'originTownName' => true,
                'originPostalCode' => true,
                'destinationCountryCode' => true,
                'destinationStateProvince' => true,
                'destinationCityName' => true,
                'destinationTownName' => true,
                'destinationPostalCode' => true,
                'residentialIndicator' => true,
                'shipDate' => true,
                'shipTime' => true,
                'weight' => true,
                'weightUnitOfMeasure' => true,
                'shipmentContentsValue' => true,
                'shipmentContentsCurrencyCode' => true,
                'billType' => true,
                'avvFlag' => true,
                'numberOfPackages' => true,
                'dropOffAtFacilityIndicator' => true,
                'holdForPickupIndicator' => true,
                'returnUnfilterdServices' => true,
                'maxList' => true,
                'premierIndicator' => true,
            ],
        );
        if ($originCountryCode === null) {
            throw new MalformedDataException('Required property "originCountryCode" is missing from the document.');
        }

        return new self(
            $originCountryCode,
            $originStateProvince,
            $originCityName,
            $originTownName,
            $originPostalCode,
            $destinationCountryCode,
            $destinationStateProvince,
            $destinationCityName,
            $destinationTownName,
            $destinationPostalCode,
            $residentialIndicator,
            $shipDate,
            $shipTime,
            $weight,
            $weightUnitOfMeasure,
            $shipmentContentsValue,
            $shipmentContentsCurrencyCode,
            $billType,
            $avvFlag,
            $numberOfPackages,
            $dropOffAtFacilityIndicator,
            $holdForPickupIndicator,
            $returnUnfilterdServices,
            $maxList,
            $premierIndicator,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $dataArray['originCountryCode'] = $this->originCountryCode;
        $originStateProvinceOption = $this->originStateProvince;
        if ($originStateProvinceOption->isDefined()) {
            $originStateProvince = $originStateProvinceOption->get();
            $dataArray['originStateProvince'] = $originStateProvince;
        }
        $originCityNameOption = $this->originCityName;
        if ($originCityNameOption->isDefined()) {
            $originCityName = $originCityNameOption->get();
            $dataArray['originCityName'] = $originCityName;
        }
        $originTownNameOption = $this->originTownName;
        if ($originTownNameOption->isDefined()) {
            $originTownName = $originTownNameOption->get();
            $dataArray['originTownName'] = $originTownName;
        }
        $originPostalCodeOption = $this->originPostalCode;
        if ($originPostalCodeOption->isDefined()) {
            $originPostalCode = $originPostalCodeOption->get();
            $dataArray['originPostalCode'] = $originPostalCode;
        }
        $destinationCountryCodeOption = $this->destinationCountryCode;
        if ($destinationCountryCodeOption->isDefined()) {
            $destinationCountryCode = $destinationCountryCodeOption->get();
            $dataArray['destinationCountryCode'] = $destinationCountryCode;
        }
        $destinationStateProvinceOption = $this->destinationStateProvince;
        if ($destinationStateProvinceOption->isDefined()) {
            $destinationStateProvince = $destinationStateProvinceOption->get();
            $dataArray['destinationStateProvince'] = $destinationStateProvince;
        }
        $destinationCityNameOption = $this->destinationCityName;
        if ($destinationCityNameOption->isDefined()) {
            $destinationCityName = $destinationCityNameOption->get();
            $dataArray['destinationCityName'] = $destinationCityName;
        }
        $destinationTownNameOption = $this->destinationTownName;
        if ($destinationTownNameOption->isDefined()) {
            $destinationTownName = $destinationTownNameOption->get();
            $dataArray['destinationTownName'] = $destinationTownName;
        }
        $destinationPostalCodeOption = $this->destinationPostalCode;
        if ($destinationPostalCodeOption->isDefined()) {
            $destinationPostalCode = $destinationPostalCodeOption->get();
            $dataArray['destinationPostalCode'] = $destinationPostalCode;
        }
        $residentialIndicatorOption = $this->residentialIndicator;
        if ($residentialIndicatorOption->isDefined()) {
            $residentialIndicator = $residentialIndicatorOption->get();
            $dataArray['residentialIndicator'] = $residentialIndicator;
        }
        $shipDateOption = $this->shipDate;
        if ($shipDateOption->isDefined()) {
            $shipDate = $shipDateOption->get();
            $dataArray['shipDate'] = $shipDate;
        }
        $shipTimeOption = $this->shipTime;
        if ($shipTimeOption->isDefined()) {
            $shipTime = $shipTimeOption->get();
            $dataArray['shipTime'] = $shipTime;
        }
        $weightOption = $this->weight;
        if ($weightOption->isDefined()) {
            $weight = $weightOption->get();
            $dataArray['weight'] = $weight;
        }
        $weightUnitOfMeasureOption = $this->weightUnitOfMeasure;
        if ($weightUnitOfMeasureOption->isDefined()) {
            $weightUnitOfMeasure = $weightUnitOfMeasureOption->get();
            $dataArray['weightUnitOfMeasure'] = $weightUnitOfMeasure;
        }
        $shipmentContentsValueOption = $this->shipmentContentsValue;
        if ($shipmentContentsValueOption->isDefined()) {
            $shipmentContentsValue = $shipmentContentsValueOption->get();
            $dataArray['shipmentContentsValue'] = $shipmentContentsValue;
        }
        $shipmentContentsCurrencyCodeOption = $this->shipmentContentsCurrencyCode;
        if ($shipmentContentsCurrencyCodeOption->isDefined()) {
            $shipmentContentsCurrencyCode = $shipmentContentsCurrencyCodeOption->get();
            $dataArray['shipmentContentsCurrencyCode'] = $shipmentContentsCurrencyCode;
        }
        $billTypeOption = $this->billType;
        if ($billTypeOption->isDefined()) {
            $billType = $billTypeOption->get();
            $dataArray['billType'] = $billType;
        }
        $avvFlagOption = $this->avvFlag;
        if ($avvFlagOption->isDefined()) {
            $avvFlag = $avvFlagOption->get();
            $dataArray['avvFlag'] = $avvFlag;
        }
        $numberOfPackagesOption = $this->numberOfPackages;
        if ($numberOfPackagesOption->isDefined()) {
            $numberOfPackages = $numberOfPackagesOption->get();
            $dataArray['numberOfPackages'] = $numberOfPackages;
        }
        $dropOffAtFacilityIndicatorOption = $this->dropOffAtFacilityIndicator;
        if ($dropOffAtFacilityIndicatorOption->isDefined()) {
            $dropOffAtFacilityIndicator = $dropOffAtFacilityIndicatorOption->get();
            $dataArray['dropOffAtFacilityIndicator'] = $dropOffAtFacilityIndicator;
        }
        $holdForPickupIndicatorOption = $this->holdForPickupIndicator;
        if ($holdForPickupIndicatorOption->isDefined()) {
            $holdForPickupIndicator = $holdForPickupIndicatorOption->get();
            $dataArray['holdForPickupIndicator'] = $holdForPickupIndicator;
        }
        $returnUnfilterdServicesOption = $this->returnUnfilterdServices;
        if ($returnUnfilterdServicesOption->isDefined()) {
            $returnUnfilterdServices = $returnUnfilterdServicesOption->get();
            $dataArray['returnUnfilterdServices'] = $returnUnfilterdServices;
        }
        $maxListOption = $this->maxList;
        if ($maxListOption->isDefined()) {
            $maxList = $maxListOption->get();
            $dataArray['maxList'] = $maxList;
        }
        $premierIndicatorOption = $this->premierIndicator;
        if ($premierIndicatorOption->isDefined()) {
            $premierIndicator = $premierIndicatorOption->get();
            $dataArray['premierIndicator'] = $premierIndicator;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): TimeInTransitRequestBuilder
    {
        return new TimeInTransitRequestBuilder(
            $this->originCountryCode,
            $this->originStateProvince,
            $this->originCityName,
            $this->originTownName,
            $this->originPostalCode,
            $this->destinationCountryCode,
            $this->destinationStateProvince,
            $this->destinationCityName,
            $this->destinationTownName,
            $this->destinationPostalCode,
            $this->residentialIndicator,
            $this->shipDate,
            $this->shipTime,
            $this->weight,
            $this->weightUnitOfMeasure,
            $this->shipmentContentsValue,
            $this->shipmentContentsCurrencyCode,
            $this->billType,
            $this->avvFlag,
            $this->numberOfPackages,
            $this->dropOffAtFacilityIndicator,
            $this->holdForPickupIndicator,
            $this->returnUnfilterdServices,
            $this->maxList,
            $this->premierIndicator,
            $this->additionalProperties,
        );
    }
}
