<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_diff_key;
use function array_is_list;
use function array_key_exists;
use function array_map;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_string;
use function sprintf;

final readonly class ValidationList implements SelfNormalizingModel
{
    /**
     * @param Option<list<string>>     $invalidFieldList
     * @param Option<list<string>>     $invalidFieldListCodes
     * @param Option<bool>             $destinationAmbiguous
     * @param Option<bool>             $originAmbiguous
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $invalidFieldList,
        private Option $invalidFieldListCodes,
        private Option $destinationAmbiguous,
        private Option $originAmbiguous,
        private array $additionalProperties,
    ) {
    }

    public static function builder(): ValidationListBuilder
    {
        return new ValidationListBuilder(None::create(), None::create(), None::create(), None::create(), []);
    }

    /** @return Option<list<string>> */
    public function getInvalidFieldList(): Option
    {
        return $this->invalidFieldList;
    }

    /** @return Option<list<string>> */
    public function getInvalidFieldListCodes(): Option
    {
        return $this->invalidFieldListCodes;
    }

    /**
     * Returned as true when destination address has a candidate list.
     *
     * @return Option<bool>
     */
    public function getDestinationAmbiguous(): Option
    {
        return $this->destinationAmbiguous;
    }

    /**
     * Returned as true when original address has a candidate list.
     *
     * @return Option<bool>
     */
    public function getOriginAmbiguous(): Option
    {
        return $this->originAmbiguous;
    }

    /** @return array<int|string, mixed> */
    public function getAdditionalProperties(): array
    {
        return $this->additionalProperties;
    }

    /**
     * @param array<int|string, mixed> $data
     *
     * @throws MalformedDataException
     */
    public static function fromArray(array $data): self
    {
        $invalidFieldList = None::create();
        $invalidFieldListCodes = None::create();
        $destinationAmbiguous = None::create();
        $originAmbiguous = None::create();
        if (array_key_exists('invalidFieldList', $data) && $data['invalidFieldList'] !== null) {
            $invalidFieldListRaw = $data['invalidFieldList'];
            if (!(is_array($invalidFieldListRaw) && array_is_list($invalidFieldListRaw))) {
                throw new MalformedDataException(
                    sprintf('Property "invalidFieldList" must be list, got %s.', get_debug_type($invalidFieldListRaw)),
                );
            }
            $invalidFieldList = Some::create(array_map(static function (mixed $value): string {
                if (!is_string($value)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value)),
                    );
                }

                return $value;
            }, $invalidFieldListRaw));
        }
        if (array_key_exists('invalidFieldListCodes', $data) && $data['invalidFieldListCodes'] !== null) {
            $invalidFieldListCodesRaw = $data['invalidFieldListCodes'];
            if (!(is_array($invalidFieldListCodesRaw) && array_is_list($invalidFieldListCodesRaw))) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "invalidFieldListCodes" must be list, got %s.',
                        get_debug_type($invalidFieldListCodesRaw),
                    ),
                );
            }
            $invalidFieldListCodes = Some::create(array_map(static function (mixed $value_1): string {
                if (!is_string($value_1)) {
                    throw new MalformedDataException(
                        sprintf('Array item must be string, got %s.', get_debug_type($value_1)),
                    );
                }

                return $value_1;
            }, $invalidFieldListCodesRaw));
        }
        if (array_key_exists('destinationAmbiguous', $data) && $data['destinationAmbiguous'] !== null) {
            $destinationAmbiguousRaw = $data['destinationAmbiguous'];
            if (!is_bool($destinationAmbiguousRaw)) {
                throw new MalformedDataException(
                    sprintf(
                        'Property "destinationAmbiguous" must be bool, got %s.',
                        get_debug_type($destinationAmbiguousRaw),
                    ),
                );
            }
            $destinationAmbiguous = Some::create($destinationAmbiguousRaw);
        }
        if (array_key_exists('originAmbiguous', $data) && $data['originAmbiguous'] !== null) {
            $originAmbiguousRaw = $data['originAmbiguous'];
            if (!is_bool($originAmbiguousRaw)) {
                throw new MalformedDataException(
                    sprintf('Property "originAmbiguous" must be bool, got %s.', get_debug_type($originAmbiguousRaw)),
                );
            }
            $originAmbiguous = Some::create($originAmbiguousRaw);
        }
        $additionalProperties = array_diff_key(
            $data,
            [
                'invalidFieldList' => true,
                'invalidFieldListCodes' => true,
                'destinationAmbiguous' => true,
                'originAmbiguous' => true,
            ],
        );

        return new self(
            $invalidFieldList,
            $invalidFieldListCodes,
            $destinationAmbiguous,
            $originAmbiguous,
            $additionalProperties,
        );
    }

    /** @return array<int|string, mixed> */
    #[Override]
    public function toArray(): array
    {
        /** @var array<int|string, mixed> $dataArray */
        $dataArray = [];
        $invalidFieldListOption = $this->invalidFieldList;
        if ($invalidFieldListOption->isDefined()) {
            $invalidFieldList = $invalidFieldListOption->get();
            $values = [];
            foreach ($invalidFieldList as $value) {
                $values[] = $value;
            }
            $dataArray['invalidFieldList'] = $values;
        }
        $invalidFieldListCodesOption = $this->invalidFieldListCodes;
        if ($invalidFieldListCodesOption->isDefined()) {
            $invalidFieldListCodes = $invalidFieldListCodesOption->get();
            $values_1 = [];
            foreach ($invalidFieldListCodes as $value_1) {
                $values_1[] = $value_1;
            }
            $dataArray['invalidFieldListCodes'] = $values_1;
        }
        $destinationAmbiguousOption = $this->destinationAmbiguous;
        if ($destinationAmbiguousOption->isDefined()) {
            $destinationAmbiguous = $destinationAmbiguousOption->get();
            $dataArray['destinationAmbiguous'] = $destinationAmbiguous;
        }
        $originAmbiguousOption = $this->originAmbiguous;
        if ($originAmbiguousOption->isDefined()) {
            $originAmbiguous = $originAmbiguousOption->get();
            $dataArray['originAmbiguous'] = $originAmbiguous;
        }
        $dataArray += $this->getAdditionalProperties();

        return $dataArray;
    }

    #[Override]
    public function jsonSerialize(): object
    {
        return (object) $this->toArray();
    }

    public function toBuilder(): ValidationListBuilder
    {
        return new ValidationListBuilder(
            $this->invalidFieldList,
            $this->invalidFieldListCodes,
            $this->destinationAmbiguous,
            $this->originAmbiguous,
            $this->additionalProperties,
        );
    }
}
