<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Model;

use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

/**
 * Builds a {@see ValidationList}.
 */
final class ValidationListBuilder
{
    /**
     * @internal obtained from the model's `builder()` or `toBuilder()`
     *
     * @param Option<list<string>>     $invalidFieldList
     * @param Option<list<string>>     $invalidFieldListCodes
     * @param Option<bool>             $destinationAmbiguous
     * @param Option<bool>             $originAmbiguous
     * @param array<int|string, mixed> $additionalProperties
     */
    public function __construct(
        private Option $invalidFieldList,
        private Option $invalidFieldListCodes,
        private Option $destinationAmbiguous,
        private Option $originAmbiguous,
        private array $additionalProperties,
    ) {
    }

    /** @param list<string> $invalidFieldList */
    public function setInvalidFieldList(array $invalidFieldList): self
    {
        $this->invalidFieldList = Some::create($invalidFieldList);

        return $this;
    }

    /** @param list<string> $invalidFieldListCodes */
    public function setInvalidFieldListCodes(array $invalidFieldListCodes): self
    {
        $this->invalidFieldListCodes = Some::create($invalidFieldListCodes);

        return $this;
    }

    /**
     * Returned as true when destination address has a candidate list.
     */
    public function setDestinationAmbiguous(bool $destinationAmbiguous): self
    {
        $this->destinationAmbiguous = Some::create($destinationAmbiguous);

        return $this;
    }

    /**
     * Returned as true when original address has a candidate list.
     */
    public function setOriginAmbiguous(bool $originAmbiguous): self
    {
        $this->originAmbiguous = Some::create($originAmbiguous);

        return $this;
    }

    /** @param array<int|string, mixed> $additionalProperties */
    public function setAdditionalProperties(array $additionalProperties): self
    {
        $this->additionalProperties = $additionalProperties;

        return $this;
    }

    public function build(): ValidationList
    {
        return new ValidationList(
            $this->invalidFieldList,
            $this->invalidFieldListCodes,
            $this->destinationAmbiguous,
            $this->originAmbiguous,
            $this->additionalProperties,
        );
    }
}
