<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Operation;

use Override;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedResponseException;
use Prefabcortex\UpsTimeInTransit\Exception\ResponseValidationException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitBadRequestException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitForbiddenException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitTooManyRequestsException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitUnauthorizedException;
use Prefabcortex\UpsTimeInTransit\Exception\UnexpectedContentTypeException;
use Prefabcortex\UpsTimeInTransit\Exception\UnexpectedStatusCodeException;
use Prefabcortex\UpsTimeInTransit\Http\BaseOperationTrait;
use Prefabcortex\UpsTimeInTransit\Http\ContentType;
use Prefabcortex\UpsTimeInTransit\Http\HeaderParameters;
use Prefabcortex\UpsTimeInTransit\Http\JsonBody;
use Prefabcortex\UpsTimeInTransit\Http\Operation;
use Prefabcortex\UpsTimeInTransit\Http\OperationTrait;
use Prefabcortex\UpsTimeInTransit\Http\Payload;
use Prefabcortex\UpsTimeInTransit\Http\ValidationMode;
use Prefabcortex\UpsTimeInTransit\Model\ErrorResponse;
use Prefabcortex\UpsTimeInTransit\Model\TimeInTransitRequest;
use Prefabcortex\UpsTimeInTransit\Model\TimeInTransitResponse;
use Prefabcortex\UpsTimeInTransit\Parameter\TimeInTransitHeaderParameters;
use Prefabcortex\UpsTimeInTransit\Validation\ValidationException;
use Prefabcortex\UpsTimeInTransit\Validation\ValidatorTrait;
use Prefabcortex\UpsTimeInTransit\Validator\ErrorResponseConstraint;
use Prefabcortex\UpsTimeInTransit\Validator\TimeInTransitRequestConstraint;
use Prefabcortex\UpsTimeInTransit\Validator\TimeInTransitResponseConstraint;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;

use function in_array;
use function str_replace;

/**
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 *
 * @implements Operation<TimeInTransitResponse>
 */
final class TimeInTransit implements Operation
{
    use BaseOperationTrait;
    use OperationTrait;
    use ValidatorTrait;
    private readonly string $version;
    private readonly TimeInTransitRequest $body;
    private readonly TimeInTransitHeaderParameters $headerParameters;

    /** @param string $version API Version */
    public function __construct(
        string $version,
        TimeInTransitRequest $requestBody,
        TimeInTransitHeaderParameters $headerParameters,
    ) {
        $this->version = $version;
        $this->body = $requestBody;
        $this->headerParameters = $headerParameters;
    }

    #[Override]
    public function getMethod(): string
    {
        return 'POST';
    }

    #[Override]
    public function getUri(): string
    {
        return str_replace(['{version}'], [self::pathValue($this->version)], '/shipments/{version}/transittimes');
    }

    /**
     * @throws MalformedDataException
     * @throws ValidationException
     */
    #[Override]
    public function getPayload(StreamFactoryInterface $streamFactory, ValidationMode $validation): Payload
    {
        if (ValidationMode::Strict === $validation) {
            $this->validate($this->body->toArray(), TimeInTransitRequestConstraint::constraints());
        }

        return new Payload(['Content-Type' => ['application/json']], JsonBody::encode($this->body));
    }

    /** @return array<string, list<string>> */
    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getHeaderParameters(): HeaderParameters
    {
        return $this->headerParameters->toHeaderParameters();
    }

    /**
     * {@inheritdoc}.
     *
     * @throws ValidationException
     * @throws MalformedDataException
     * @throws TimeInTransitBadRequestException
     * @throws TimeInTransitUnauthorizedException
     * @throws TimeInTransitForbiddenException
     * @throws TimeInTransitTooManyRequestsException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    #[Override]
    protected function transformResponseBody(
        ResponseInterface $response,
        ContentType $contentType,
        string $body,
        ValidationMode $validation,
    ): TimeInTransitResponse {
        $status = $response->getStatusCode();
        // 200: successful operation
        // 206: Partial content - candidate list (validationList / destinationPickList)
        if (in_array($status, [200, 206], true) && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, TimeInTransitResponseConstraint::constraints());
            }

            return TimeInTransitResponse::fromArray($typedData);
        }
        if (400 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new TimeInTransitBadRequestException(ErrorResponse::fromArray($typedData), $response, $body);
        }
        if (401 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new TimeInTransitUnauthorizedException(ErrorResponse::fromArray($typedData), $response, $body);
        }
        if (403 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new TimeInTransitForbiddenException(ErrorResponse::fromArray($typedData), $response, $body);
        }
        if (429 === $status && $contentType->is('application/json')) {
            $typedData = JsonBody::toArray($body);
            if (ValidationMode::Strict === $validation) {
                $this->validate($typedData, ErrorResponseConstraint::constraints());
            }
            throw new TimeInTransitTooManyRequestsException(ErrorResponse::fromArray($typedData), $response, $body);
        }
        if (in_array($status, [200, 206, 400, 401, 403, 429], true)) {
            throw new UnexpectedContentTypeException($response, $body);
        }
        throw UnexpectedStatusCodeException::of($response, $body);
    }

    /**
     * @throws ResponseValidationException
     * @throws MalformedResponseException
     * @throws TimeInTransitBadRequestException
     * @throws TimeInTransitUnauthorizedException
     * @throws TimeInTransitForbiddenException
     * @throws TimeInTransitTooManyRequestsException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    #[Override]
    public function parseResponse(ResponseInterface $response, ValidationMode $validation): TimeInTransitResponse
    {
        $contentType = ContentType::fromHeader($response->getHeader('Content-Type')[0] ?? '');
        $body = self::readBody($response);
        try {
            return $this->transformResponseBody($response, $contentType, $body, $validation);
        } catch (ValidationException $exception) {
            if ($response->getStatusCode() >= 400) {
                throw UnexpectedStatusCodeException::ofUnreadableBody($response, $body, $exception);
            }
            throw new ResponseValidationException($exception, $response, $body);
        } catch (MalformedDataException $exception) {
            if ($response->getStatusCode() >= 400) {
                throw UnexpectedStatusCodeException::ofUnreadableBody($response, $body, $exception);
            }
            throw new MalformedResponseException($exception, $response, $body);
        }
    }

    /** @return list<list<string>> */
    #[Override]
    public function getSecurityRequirements(): array
    {
        return [['OAuth2']];
    }
}
