<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use RuntimeException;

use function array_map;
use function array_merge;
use function implode;
use function is_array;
use function is_bool;
use function rawurlencode;

/**
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
trait BaseOperationTrait
{
    abstract public function getMethod(): string;

    abstract public function getPayload(StreamFactoryInterface $streamFactory, ValidationMode $validation): Payload;

    abstract public function getUri(): string;

    /** @return list<list<string>> */
    abstract public function getSecurityRequirements(): array;

    /**
     * Transforms the raw HTTP response body into this operation's declared return type. Generated
     * overrides always emit an inheritdoc tag here, so this description must stay non-empty.
     *
     * `$body` is the response body as text, read once by `parseResponse()`: the exception that
     * carries a response which could not be read needs the bytes, and a stream that cannot seek
     * would hand them over only the first time.
     */
    abstract protected function transformResponseBody(
        ResponseInterface $response,
        ContentType $contentType,
        string $body,
        ValidationMode $validation,
    ): mixed;

    /** @return array<string, list<string>> */
    protected function getExtraHeaders(): array
    {
        return [];
    }

    /**
     * The document's own servers. An operation that brings `servers` of its own, or whose path
     * does, answers with the key of that set instead.
     */
    public function getServerSet(): string
    {
        return ServerSelection::ROOT;
    }

    /**
     * The operation's query parameters. Overridden by operations that have any, returning the
     * collection their typed parameter object builds from its own properties — which is why nothing
     * here has to inspect a value to find out what it is.
     */
    protected function getQueryParameters(): QueryParameters
    {
        return QueryParameters::none();
    }

    /**
     * The operation's header parameters; see {@see getQueryParameters()}.
     */
    protected function getHeaderParameters(): HeaderParameters
    {
        return HeaderParameters::none();
    }

    final public function getQueryString(): string
    {
        return $this->transformQueryParameters($this->getQueryParameters())->encode();
    }

    /**
     * @param array<string, list<string>> $baseHeaders
     *
     * @return array<string, list<string>>
     */
    final public function getHeaders(array $baseHeaders = []): array
    {
        return array_merge($this->getExtraHeaders(), $baseHeaders, $this->getHeaderParameters()->toHeaderMap());
    }

    /**
     * A path parameter as it goes into the path — OpenAPI's `simple` style, percent-encoded.
     *
     * Every character outside RFC 3986's unreserved set is encoded, so a `/` in an identifier adds
     * no path segment, a `?` starts no query string and `../` does not climb out of the resource
     * the operation addresses. A list is joined with commas, each element encoded on its own, and a
     * boolean is written as the word.
     *
     * @param string|int|float|bool|array<array-key, string|int|float|bool> $value
     */
    final protected static function pathValue(string|int|float|bool|array $value): string
    {
        if (is_array($value)) {
            return implode(
                ',',
                array_map(static fn (string|int|float|bool $item): string => self::pathValue($item), $value),
            );
        }

        return rawurlencode(self::textValue($value));
    }

    /**
     * A scalar as the text of a request body — the same rendering a path parameter gets, without
     * the percent-encoding a path needs and a body does not.
     *
     * A description that says `text/plain` and `type: integer` hands the operation an `int`, and
     * `Payload` carries a string or a stream; this is what lies between the two. A boolean is
     * written as the word rather than as PHP's `"1"` and `""`, where the second is
     * indistinguishable from no body at all.
     */
    final protected static function textValue(string|int|float|bool $value): string
    {
        return is_bool($value) ? $value ? 'true' : 'false' : (string) $value;
    }

    /**
     * The response body as text, with the stream put back at its start where it can be.
     *
     * `parseResponse()` reads the body once and hands the text to every exception it raises, as
     * `getRawResponse()`. Rewinding afterwards keeps the response those exceptions return from
     * `getResponse()` readable with `getContents()`. A stream that cannot seek is left as it is:
     * its bytes exist only in the text returned here.
     */
    final protected static function readBody(ResponseInterface $response): string
    {
        $stream = $response->getBody();
        $body = (string) $stream;
        if (!$stream->isSeekable()) {
            return $body;
        }
        try {
            $stream->rewind();
        } catch (RuntimeException) {
        }

        return $body;
    }

    /**
     * Applies the transformers this operation has for its query parameters. No-op unless overridden
     * — only operations with a transformer for one of their query parameters override this.
     */
    protected function transformQueryParameters(QueryParameters $queryParameters): QueryParameters
    {
        return $queryParameters;
    }
}
