<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use InvalidArgumentException;
use Prefabcortex\UpsTimeInTransit\Authentication\AuthenticatorRegistry;
use Prefabcortex\UpsTimeInTransit\Exception\ApiException;
use Prefabcortex\UpsTimeInTransit\Exception\NetworkException;
use Prefabcortex\UpsTimeInTransit\Exception\RequestException;
use Prefabcortex\UpsTimeInTransit\Exception\TransportException;
use Prefabcortex\UpsTimeInTransit\Exception\TransportFailedException;
use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Client\NetworkExceptionInterface;
use Psr\Http\Client\RequestExceptionInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\StreamInterface;

use function sprintf;
use function str_contains;

/**
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
trait ClientTrait
{
    /**
     * Which server each operation goes to; its base URL is what the operation's path is appended
     * to.
     */
    protected ServerSelection $servers;
    protected ClientInterface $httpClient;
    protected RequestFactoryInterface $requestFactory;
    protected StreamFactoryInterface $streamFactory;
    protected AuthenticatorRegistry $authenticatorRegistry;
    protected ValidationMode $validation;

    /**
     * @param ServerSelection $servers    where the described API lives: the server chosen for
     *                                    each of the package's server sets
     * @param ValidationMode  $validation how closely requests and responses are held to the
     *                                    description, handed to each operation as it builds
     *                                    its request and reads its response
     *
     * @throws UnsupportedValueException when a chosen server cannot address one — no scheme and host,
     *                                   a relative URL without an origin, a variable without a value
     */
    protected function __construct(
        ServerSelection $servers,
        ClientInterface $httpClient,
        RequestFactoryInterface $requestFactory,
        StreamFactoryInterface $streamFactory,
        AuthenticatorRegistry $authenticatorRegistry,
        ValidationMode $validation,
    ) {
        // Checked once here rather than per request: a server that names no host produces a
        // relative request URI, and a PSR-18 client answers that with an exception naming the
        // request instead of the configuration that caused it.
        $servers->check();
        $this->servers = $servers;
        $this->httpClient = $httpClient;
        $this->requestFactory = $requestFactory;
        $this->streamFactory = $streamFactory;
        $this->authenticatorRegistry = $authenticatorRegistry;
        $this->validation = $validation;
    }

    /**
     * Public because the generated tag facades call it from another namespace, and PHP has no
     * package-private visibility to say otherwise. The annotation has to be repeated here rather
     * than left on the trait: reflection copies a trait method's own docblock into the using class,
     * never the trait's, so this is the only place a tool reading `Client::executeOperation()`
     * looks.
     *
     * @internal plumbing of the generated package, not part of its public contract: only the
     *                    generated operations and client touch this, and it may change in any release
     *
     * @template TReturn
     *
     * @param Operation<TReturn> $operation
     *
     * @return TReturn
     *
     * @throws ApiException
     * @throws TransportException
     * @throws UnsupportedValueException
     */
    final public function executeOperation(Operation $operation): mixed
    {
        return $operation->parseResponse($this->processOperation($operation), $this->validation);
    }

    /**
     * @internal plumbing of the generated package, not part of its public contract: only the
     *                    generated operations and client touch this, and it may change in any release
     *
     * @param Operation<mixed> $operation
     *
     * @throws ApiException
     * @throws TransportException
     * @throws UnsupportedValueException
     */
    final public function executeRawOperation(Operation $operation): ResponseInterface
    {
        return $this->processOperation($operation);
    }

    /**
     * @param Operation<mixed> $operation
     *
     * @throws ApiException
     * @throws TransportException
     * @throws UnsupportedValueException
     */
    private function processOperation(Operation $operation): ResponseInterface
    {
        $payload = $operation->getPayload($this->streamFactory, $this->validation);
        $queryString = $operation->getQueryString();
        $uriGlue = !str_contains($operation->getUri(), '?') ? '?' : '&';
        $uri = $queryString !== '' ? $operation->getUri() . $uriGlue . $queryString : $operation->getUri();
        // Assembling the message is the one stretch that raises PSR-7's bare
        // `InvalidArgumentException` — `withHeader()` with a value the implementation will not take
        // is the case that actually happens. PSR-7 declares no interface for it, so it can only be
        // recognised by where it is caught, and that is what makes this span the right one: it holds
        // no throw site of ours, so everything caught here came from the PSR implementation.
        // `UnsupportedValueException` is listed first regardless — it extends the same SPL class,
        // and a third-party `Authenticator` raising one would otherwise be re-wrapped in itself.
        try {
            // Concatenation, not RFC 3986 resolution. OpenAPI defines a request URL as the Server
            // Object's URL followed by the Path Item's key, and `Operation::getUri()` answers with
            // such a key — always rooted at `/`. Resolving the two the way RFC 3986 resolves a
            // reference would replace the base path instead of extending it: `/pets` against
            // `https://host/v2` would address `https://host/pets`, a path the server does not serve.
            $request = $this->requestFactory->createRequest(
                $operation->getMethod(),
                $this->servers->baseUrl($operation->getServerSet()) . $uri,
            );
            $content = $payload->content;
            $body = $content instanceof StreamInterface ? $content : $this->streamFactory->createStream($content);
            $request = $request->withBody($body);
            foreach ($operation->getHeaders($payload->headers) as $name => $value) {
                $request = $request->withHeader($name, $value);
            }
            $request = $this->authenticatorRegistry->authenticate($request, $operation->getSecurityRequirements());
        } catch (UnsupportedValueException $exception) {
            throw $exception;
        } catch (InvalidArgumentException $exception) {
            throw new UnsupportedValueException(
                sprintf('The request could not be assembled: %s', $exception->getMessage()),
                0,
                $exception,
            );
        }
        // The order is load-bearing: both finer interfaces extend `ClientExceptionInterface`, so a
        // catch of the general one first would swallow the classification the client just made.
        try {
            return $this->httpClient->sendRequest($request);
        } catch (NetworkExceptionInterface $exception) {
            throw new NetworkException($exception->getRequest(), $exception);
        } catch (RequestExceptionInterface $exception) {
            throw new RequestException($exception->getRequest(), $exception);
        } catch (ClientExceptionInterface $exception) {
            throw new TransportFailedException($request, $exception);
        }
    }
}
