<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use function explode;
use function str_ends_with;
use function str_starts_with;
use function strtolower;
use function substr;
use function trim;

/**
 * The media type of a message body, reduced to what identifies it.
 *
 * A `Content-Type` header carries parameters — `application/json; charset=utf-8` — which say
 * nothing about *which* type it is. This drops them once, at the edge, so every comparison
 * afterwards is an exact one against the essence.
 *
 * That exactness is the point. Matching the header as a substring would also accept
 * `application/json-seq` for `application/json`, and any type whose parameter value happens to
 * contain the needle. Carrying the normalized value as a type rather than a bare string keeps a
 * caller from comparing against the raw header by accident.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class ContentType
{
    /**
     * The `content` key that covers every media type there is.
     */
    private const string ANY = '*/*';
    /**
     * The tail of a `content` key that covers every subtype of one type, as in `text/*`.
     */
    private const string ANY_SUBTYPE = '/*';
    public const string JSON = 'application/json';
    public const string FORM_URLENCODED = 'application/x-www-form-urlencoded';
    public const string MULTIPART_FORM_DATA = 'multipart/form-data';

    /** @param string $essence lowercased type/subtype, without parameters */
    private function __construct(public string $essence)
    {
    }

    /**
     * Reads a `Content-Type` header value. An absent header — the empty string — yields a content
     * type that matches nothing, which is what "the server did not say" should mean.
     */
    public static function fromHeader(string $header): self
    {
        return new self(strtolower(trim(explode(';', $header, 2)[0])));
    }

    /**
     * Whether the body's media type is the one a description names.
     *
     * The argument comes from the description and may be a *range*: OpenAPI allows one as a key
     * under `content` — {@see self::ANY} for any type there is, and a type followed by {@see
     * self::ANY_SUBTYPE} for any subtype of it. Both mean there what they mean in an `Accept`
     * header, so a range matches every type it covers rather than only a server that answers with
     * the range itself as its header.
     *
     * A body the server named no type for matches nothing, ranges included. An absent header is not
     * the statement "any type" — it is no statement, and a range is still a claim about what the
     * server said.
     */
    public function is(string $mediaType): bool
    {
        if ('' === $this->essence) {
            return false;
        }
        $named = strtolower(trim($mediaType));
        if (self::ANY === $named) {
            return true;
        }
        if (str_ends_with($named, self::ANY_SUBTYPE)) {
            return str_starts_with($this->essence, substr($named, 0, -1));
        }

        return $this->essence === $named;
    }

    /**
     * Whether this is any of several media types the operation handles the same way.
     *
     * A status served under `application/json` and `application/problem+json` with one schema is
     * read by one branch, not by one per media type.
     *
     * @param list<string> $mediaTypes
     */
    public function isAnyOf(array $mediaTypes): bool
    {
        foreach ($mediaTypes as $mediaType) {
            if ($this->is($mediaType)) {
                return true;
            }
        }

        return false;
    }
}
