<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use function array_is_list;
use function array_key_exists;
use function array_keys;
use function is_array;
use function is_string;
use function json_decode;
use function preg_match;
use function preg_replace;
use function strlen;
use function substr;

/**
 * Turns an error response body into the message its exception carries.
 *
 * APIs put the human-readable part of an error under one of a handful of names — RFC 7807 calls it
 * `detail` with `title` as the summary, plenty of others just say `message` — and not always at the
 * top of the body. The nearest of those that actually holds text wins; a body that is not JSON, or
 * holds none of them, leaves the status description standing on its own.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final class ErrorMessage
{
    /**
     * What a status code means, or the empty string for a code this does not name.
     *
     * Error statuses only. A success status reaching {@see describeStatus()} means no response
     * declared it, and answering "OK" to that would be the one misleading thing to say.
     *
     * Wording follows IANA's HTTP Status Code Registry, which is also where the RFC behind any one
     * of these codes is to be looked up. A `match` rather than a constant array on purpose: this
     * file is copied into every generated package and reprinted there, and reprinting puts an array
     * literal on a single line — forty entries and fifteen hundred characters of it.
     */
    public static function statusText(int $status): string
    {
        return match ($status) {
            400 => 'Bad Request',
            401 => 'Unauthorized',
            402 => 'Payment Required',
            403 => 'Forbidden',
            404 => 'Not Found',
            405 => 'Method Not Allowed',
            406 => 'Not Acceptable',
            407 => 'Proxy Authentication Required',
            408 => 'Request Timeout',
            409 => 'Conflict',
            410 => 'Gone',
            411 => 'Length Required',
            412 => 'Precondition Failed',
            413 => 'Content Too Large',
            414 => 'URI Too Long',
            415 => 'Unsupported Media Type',
            416 => 'Range Not Satisfiable',
            417 => 'Expectation Failed',
            418 => 'I\'m a teapot',
            421 => 'Misdirected Request',
            422 => 'Unprocessable Content',
            423 => 'Locked',
            424 => 'Failed Dependency',
            425 => 'Too Early',
            426 => 'Upgrade Required',
            428 => 'Precondition Required',
            429 => 'Too Many Requests',
            431 => 'Request Header Fields Too Large',
            451 => 'Unavailable For Legal Reasons',
            500 => 'Internal Server Error',
            501 => 'Not Implemented',
            502 => 'Bad Gateway',
            503 => 'Service Unavailable',
            504 => 'Gateway Timeout',
            505 => 'HTTP Version Not Supported',
            506 => 'Variant Also Negotiates',
            507 => 'Insufficient Storage',
            508 => 'Loop Detected',
            510 => 'Not Extended',
            511 => 'Network Authentication Required',
            default => '',
        };
    }

    /**
     * In precedence order: the most specific first. RFC 7807's `detail` explains this occurrence,
     * the informal `message` usually does too, and `title` is by definition the summary that stays
     * the same for every occurrence of the problem type.
     */
    private const array DETAIL_KEYS = ['detail', 'message', 'title'];
    /**
     * How many levels below the top a detail field is still looked for.
     */
    private const int DETAIL_DEPTH = 2;
    /**
     * How much of a detail field reaches the message, in bytes. It is API-controlled text on its
     * way into a log line and a stack trace, so it gets a ceiling; the description in front of it
     * is ours and is always short, which is why the cap sits on the detail and not on the result.
     */
    private const int DETAIL_LIMIT = 512;

    /**
     * @param string $rawResponse the response body, JSON or not
     * @param string $description what the status code means, e.g. "Bad Request"
     */
    public static function describe(string $rawResponse, string $description): string
    {
        $detail = self::detailOf($rawResponse);

        return '' === $detail ? $description : $description . ': ' . $detail;
    }

    /**
     * The same, for the one exception thrown at a status no response declared and which therefore
     * has no description of its own to go by.
     *
     * Deliberately not the response's reason phrase: HTTP/2 dropped it, so it is routinely empty,
     * and where it is present it is text an upstream proxy chose — one more thing being written
     * into a log line unread.
     *
     * @param string $rawResponse the response body, JSON or not
     */
    public static function describeStatus(string $rawResponse, int $status): string
    {
        $text = self::statusText($status);

        return self::describe($rawResponse, '' === $text ? 'HTTP ' . $status : $text);
    }

    /**
     * The same, for a response whose status is declared but whose content type is not: the status
     * says what went wrong, the content type why no branch took it — "Bad Request served as
     * text/html" for a proxy's error page in front of an API that answers 400 in JSON.
     *
     * The header is text the server chose, so it gets the same treatment as a detail field.
     *
     * @param string $rawResponse the response body, JSON or not
     * @param string $contentType the `Content-Type` header as it arrived, possibly empty
     */
    public static function describeContentType(string $rawResponse, int $status, string $contentType): string
    {
        $text = self::statusText($status);
        $servedAs = '' === $contentType ? 'without a content type' : 'served as ' . self::readable($contentType);

        return self::describe($rawResponse, ('' === $text ? 'HTTP ' . $status : $text) . ' ' . $servedAs);
    }

    /**
     * The nearest detail field holding text, or the empty string if there is none.
     *
     * Not every API puts it at the top: some wrap RFC 9457's fields in another object, some list
     * them under `errors`, some nest that list once more — and a message that says only "Bad
     * Request" while the body names the offending field is the one thing an exception should not
     * do. So the search goes level by level, into every object and into the first element of every
     * list, down to {@see self::DETAIL_DEPTH}. Breadth before depth, and within one level the key
     * precedence before the position, so a `title` in some metadata object never beats the
     * `message` of an error beside it. The depth is bounded because the body is API-controlled: a
     * field five wrappers down is more likely an echo of the request than a sentence about it.
     */
    private static function detailOf(string $rawResponse): string
    {
        $decoded = json_decode($rawResponse, true);
        if (!is_array($decoded)) {
            return '';
        }
        $level = [$decoded];
        for ($depth = 0; $depth <= self::DETAIL_DEPTH && [] !== $level; ++$depth) {
            foreach (self::DETAIL_KEYS as $key) {
                foreach ($level as $node) {
                    if (array_key_exists($key, $node) && is_string($node[$key]) && '' !== $node[$key]) {
                        return self::readable($node[$key]);
                    }
                }
            }
            $level = self::childrenOf($level);
        }

        return '';
    }

    /**
     * The objects one level below the given ones: every object value, and the first element of
     * every list, where that is an object. A list stands for its errors, and the first is the one a
     * single-line message can name.
     *
     * @param list<array<array-key, mixed>> $nodes
     *
     * @return list<array<array-key, mixed>>
     */
    private static function childrenOf(array $nodes): array
    {
        $children = [];
        foreach ($nodes as $node) {
            // Read through the key rather than bound to a loop variable: the decoded body is
            // `mixed` all the way down, and only an access expression narrows under is_array().
            foreach (array_keys($node) as $key) {
                if (!is_array($node[$key])) {
                    continue;
                }
                if (!array_is_list($node[$key])) {
                    $children[] = $node[$key];
                } elseif (array_key_exists(0, $node[$key]) && is_array($node[$key][0])) {
                    $children[] = $node[$key][0];
                }
            }
        }

        return $children;
    }

    /**
     * A detail field as one line of log, bounded: control characters out, length capped, and the
     * omitted byte count named so the reader knows the message is not the whole answer.
     */
    private static function readable(string $detail): string
    {
        // JSON escapes these, so they survive decoding as real bytes — a newline would split the
        // one line this is meant to be, and a NUL byte is not text at all.
        $detail = (string) preg_replace('/[\x00-\x1F\x7F]+/', ' ', $detail);
        if (strlen($detail) <= self::DETAIL_LIMIT) {
            return $detail;
        }
        // The cap counts bytes, so it can land inside a multi-byte character and leave a lead byte
        // standing alone. Give back the fragment rather than an invalid string — at most three
        // steps. mb_substr would say this in one call, and would put an ext-mbstring requirement
        // into every generated package for the sake of it.
        $kept = substr($detail, 0, self::DETAIL_LIMIT);
        while ('' !== $kept && 1 !== preg_match('//u', $kept)) {
            $kept = substr($kept, 0, -1);
        }

        return $kept . '… (+' . (strlen($detail) - strlen($kept)) . ' more bytes, see getRawResponse())';
    }
}
