<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use function array_key_exists;
use function array_values;

/**
 * The header parameters of one operation, in spec order.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class HeaderParameters
{
    /** @var list<HeaderParameter> */
    public array $parameters;

    /**
     * Variadic for the same reason as {@see QueryParameters::__construct()}.
     */
    public function __construct(HeaderParameter ...$parameters)
    {
        $this->parameters = array_values($parameters);
    }

    public static function none(): self
    {
        return new self();
    }

    /**
     * Collapses the parameters into the PSR-7 header shape.
     *
     * A name that appears more than once accumulates its values rather than overwriting, which is
     * what repeating a header means on the wire.
     *
     * @return array<string, list<string>>
     */
    public function toHeaderMap(): array
    {
        $headers = [];
        foreach ($this->parameters as $parameter) {
            $values = array_key_exists($parameter->name, $headers) ? $headers[$parameter->name] : [];
            foreach ($parameter->value->toHeaderValues() as $headerValue) {
                $values[] = $headerValue;
            }
            $headers[$parameter->name] = $values;
        }

        return $headers;
    }
}
