<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\NoHttpClientException;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\ResponseFactoryInterface;
use Psr\Http\Message\StreamFactoryInterface;
use ReflectionClass;
use ReflectionException;
use ReflectionMethod;

use function array_keys;
use function class_exists;
use function is_a;
use function iterator_to_array;
use function strrpos;
use function substr;

/**
 * Names the PSR-18 client the package will send its requests through.
 *
 * This is deliberately a lookup by name and not a search. The package requires the virtual
 * `psr/http-client-implementation`, which Composer refuses to resolve unless some installed package
 * claims to provide it — so by the time this class runs, *an* implementation exists and the only
 * open question is which one.
 *
 * That requirement is also why `php-http/discovery` is not used here, despite doing the same job
 * better. Discovery declares `provide: {"psr/http-client-implementation": "*"}`, which satisfies
 * the requirement on paper while installing nothing; the package that really installs an
 * implementation is its Composer *plugin*, and that runs only where the consuming project
 * allowlisted it under `config.allow-plugins` — never under `--no-interaction`, so never in CI.
 * With discovery in the dependency graph the requirement is silently always met and the failure
 * moves to the first request; without it, Composer refuses the install and lists the packages to
 * pick from. Keeping this list is the price of that error message, and it is worth paying.
 *
 * A client outside the list is not a failure of the package: it is handed over directly through
 * `ClientConfig::withHttpClient()`, which is what {@see NoHttpClientException} points at.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final class HttpClientResolver
{
    /**
     * cURL's option numbers, written out: `CURLOPT_*` exist only where ext-curl is loaded, and this
     * file is loaded everywhere.
     */
    private const int CURLOPT_TIMEOUT_MS = 155;
    private const int CURLOPT_CONNECTTIMEOUT_MS = 156;
    private const string SYMFONY = 'symfony';
    private const string GUZZLE = 'guzzle';
    private const string GUZZLE_ADAPTER = 'guzzle-adapter';
    private const string CURL = 'curl';
    private const string BUZZ = 'buzz';

    /**
     * The factories are passed to the candidates that cannot build a response on their own; the
     * ones that can take no arguments at all. Each is built with the timeout set in the options its
     * library knows, since none of them has a PSR-level way to be told.
     *
     * @throws NoHttpClientException when no known implementation is installed
     */
    public static function resolve(
        ResponseFactoryInterface $responseFactory,
        StreamFactoryInterface $streamFactory,
        Timeout $timeout,
    ): ClientInterface {
        foreach (self::candidates() as $className => $construction) {
            // Both halves are load-bearing, and the second is not paranoia about the impossible:
            // `GuzzleHttp\Client` exists in Guzzle 6 as well, where it predates PSR-18 and does
            // not implement it. Such a project satisfies the composer requirement through
            // `php-http/guzzle6-adapter` — a different class, further down this list — so
            // skipping to the next candidate is exactly right, and constructing first only to
            // discard the result would be the wasteful way to find that out.
            if (!class_exists($className) || !is_a($className, ClientInterface::class, true)) {
                continue;
            }
            try {
                $client = self::instantiate($className, $construction, $responseFactory, $streamFactory, $timeout);
            } catch (ReflectionException) {
                // A library whose shape is not the one this list expects is not one it can build.
                continue;
            }
            if ([] !== $client) {
                return $client[0];
            }
        }
        throw NoHttpClientException::noneOf(self::names());
    }

    /**
     * Builds one candidate the way its library is built, with the timeout where that library reads
     * it.
     *
     * A method of its own so that what the guards in {@see resolve()} established can be *declared*
     * rather than re-asserted inline: a parameter type holds for the whole body, where a narrowing
     * `@var` in the middle of a loop is honoured by one analyser and skipped by the next.
     *
     * - Symfony takes a configured `HttpClient`, the factory beside its PSR-18 class: `timeout`
     *   is its idle limit and `max_duration` the whole request; the idle limit covers connecting
     *   too.
     * - Guzzle, directly or behind the HTTPlug adapter, reads `connect_timeout` and `timeout`.
     * - The cURL client passes cURL options through, in milliseconds.
     * - Buzz knows one `timeout` for the whole request.
     *
     * @param class-string<ClientInterface> $className
     * @param string                        $construction one of the kinds {@see candidates()} names
     *
     * @return list<ClientInterface> the client, or nothing when a class it is built from is missing
     *
     * @throws ReflectionException when the library's factory is not where its version puts it
     */
    private static function instantiate(
        string $className,
        string $construction,
        ResponseFactoryInterface $responseFactory,
        StreamFactoryInterface $streamFactory,
        Timeout $timeout,
    ): array {
        $guzzleOptions = ['connect_timeout' => $timeout->connectSeconds, 'timeout' => $timeout->totalSeconds];
        if (self::SYMFONY === $construction) {
            // The factory next to the PSR-18 class picks the best transport installed, as a plain
            // `new Psr18Client()` would; it is reached by reflection because its name is data here.
            $factory = self::existing(substr($className, 0, (int) strrpos($className, '\\')) . '\HttpClient');

            return [] === $factory ? [] : [
                new $className(
                    new ReflectionMethod($factory[0], 'create')->invoke(
                        null,
                        ['timeout' => $timeout->totalSeconds, 'max_duration' => $timeout->totalSeconds],
                    ),
                ),
            ];
        }
        if (self::GUZZLE_ADAPTER === $construction) {
            // The adapter wraps a Guzzle client, and takes a configured one. That client is the
            // one class here that is no PSR-18 client: the adapter exists because it is not.
            $guzzle = self::classBuiltAs(self::GUZZLE);

            return [] === $guzzle ? [] : [new $className(new ReflectionClass($guzzle[0])->newInstance($guzzleOptions))];
        }

        return [match ($construction) {
            self::CURL => new $className(
                $responseFactory,
                $streamFactory,
                [
                    self::CURLOPT_CONNECTTIMEOUT_MS => (int) ($timeout->connectSeconds * 1000.0),
                    self::CURLOPT_TIMEOUT_MS => (int) ($timeout->totalSeconds * 1000.0),
                ],
            ),
            self::BUZZ => new $className($responseFactory, ['timeout' => $timeout->totalSeconds]),
            default => new $className($guzzleOptions),
        }];
    }

    /**
     * The installed class the list names for the given way of building, or nothing — whether or not
     * it is a PSR-18 client itself.
     *
     * @return list<class-string>
     */
    private static function classBuiltAs(string $construction): array
    {
        foreach (self::candidates() as $className => $candidateConstruction) {
            if ($construction === $candidateConstruction) {
                return self::existing($className);
            }
        }

        return [];
    }

    /** @return list<class-string> the class, or nothing when it does not exist */
    private static function existing(string $className): array
    {
        return class_exists($className) ? [$className] : [];
    }

    /**
     * Known PSR-18 implementations, most common first, each mapped to how it is constructed.
     *
     * A generator rather than a `const array`, and that is load-bearing rather than a matter of
     * taste. Out of a constant these names stay *literals* all the way to their use, and a static
     * analyser then resolves `class_exists()` against its own autoloader and folds the loop down to
     * whichever single client the analysed project happens to have installed — reporting "match arm
     * always false" and "instanceof always true" in one consumer's project and nothing in
     * another's. Behind a declared `iterable<string, string>` the names are what they actually are
     * here: data, not references to classes this package depends on. The same holds for the
     * construction: it is keyed by a kind, never by a class name.
     *
     * @return iterable<string, string>
     */
    private static function candidates(): iterable
    {
        yield 'Symfony\Component\HttpClient\Psr18Client' => self::SYMFONY;
        yield 'GuzzleHttp\Client' => self::GUZZLE;
        // Guzzle 6 is not PSR-18 itself; its HTTPlug adapter is. (Guzzle 7's adapter never needed an
        // entry: Guzzle 7 is PSR-18 and the line above takes it first.)
        yield 'Http\Adapter\Guzzle6\Client' => self::GUZZLE_ADAPTER;
        yield 'Http\Client\Curl\Client' => self::CURL;
        yield 'Buzz\Client\FileGetContents' => self::BUZZ;
    }

    /**
     * The candidate class names on their own, for the failure message.
     *
     * @return list<string>
     */
    private static function names(): array
    {
        return array_keys(iterator_to_array(self::candidates(), true));
    }
}
