<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use BackedEnum;
use JsonException;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;

use function array_is_list;
use function get_debug_type;
use function is_array;
use function is_bool;
use function is_float;
use function is_int;
use function is_string;
use function json_decode;
use function json_encode;
use function ltrim;
use function sprintf;
use function str_starts_with;
use function strlen;
use function substr;
use function trim;

use const JSON_THROW_ON_ERROR;

/**
 * The one place where a JSON response body crosses from untyped into typed territory.
 *
 * `json_decode()` returns `mixed`. Narrowing happens here, so callers receive a typed array and the
 * `mixed` never leaves this file.
 *
 * Every check throws {@see MalformedDataException}, which is the `UnexpectedValueException` each
 * generated `parseResponse()` and `transformResponseBody()` declares plus the marker that puts it
 * under the package's own `ApiException` — a body that is not the JSON the description promised is
 * the likeliest way a call fails, and the documented single catch covers it. The checks are thrown
 * rather than `assert()`ed: `php.ini-production` ships `zend.assertions=-1`, which drops assertions
 * at compile time, and this boundary has to hold in the configuration the package is actually
 * deployed under.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final class JsonBody
{
    /**
     * How much of an unreadable body the exception carries.
     *
     * Enough to recognise an HTML error page, a proxy notice or a truncated document at a glance,
     * short enough that the message stays a message. The body itself is not lost either way — the
     * generated exceptions hand it back through `getRawResponse()`.
     */
    private const int EXCERPT_LENGTH = 120;

    /**
     * Reads a JSON object body into the shape every generated `fromArray()` expects.
     *
     * @return array<string, mixed>
     *
     * @throws MalformedDataException
     */
    public static function toArray(string $json): array
    {
        $decoded = self::decode($json, 'a JSON object');
        // A JSON array decodes to a PHP array as well, and so does `{"0":"a","1":"b"}` — a legal
        // object that becomes a list. The decoded value cannot tell the two apart; the text can: an
        // array starts with `[`. Let through, `[1,2]` would read as an object with no properties,
        // which a model whose properties are all optional accepts as an empty result.
        if (!is_array($decoded) || str_starts_with(ltrim($json), '[')) {
            throw self::mismatch('a JSON object', $decoded, $json);
        }
        // The key type is the one thing no runtime check can establish for an empty or huge
        // array without walking it; a JSON object always decodes to string keys.
        /** @var array<string, mixed> $typed */
        $typed = $decoded;

        return $typed;
    }

    /**
     * Reads a JSON array body — a response whose top level is a list of objects.
     *
     * @return list<array<string, mixed>>
     *
     * @throws MalformedDataException
     */
    public static function toArrayList(string $json): array
    {
        $decoded = self::decode($json, 'a JSON array');
        if (!is_array($decoded) || !array_is_list($decoded)) {
            throw self::mismatch('a JSON array', $decoded, $json);
        }
        /** @var list<array<string, mixed>> $typed */
        $typed = $decoded;

        return $typed;
    }

    /**
     * Reads a JSON array body whose elements are not objects — `type: array` over scalars, or over
     * a schema no model was built for.
     *
     * @return list<mixed>
     *
     * @throws MalformedDataException
     */
    public static function toList(string $json): array
    {
        $decoded = self::decode($json, 'a JSON array');
        if (!is_array($decoded) || !array_is_list($decoded)) {
            throw self::mismatch('a JSON array', $decoded, $json);
        }
        /** @var list<mixed> $typed */
        $typed = $decoded;

        return $typed;
    }

    /**
     * Reads a JSON array of strings — `type: array` whose `items` say `type: string`.
     *
     * The element type is checked here, not left to the caller: the operation declares `string[]`,
     * and {@see self::toList()} alone would hand it whatever the array held.
     *
     * @return list<string>
     *
     * @throws MalformedDataException
     */
    public static function toStringList(string $json): array
    {
        $strings = [];
        foreach (self::toList($json) as $element) {
            if (!is_string($element)) {
                throw self::elementMismatch('strings', $element, $json);
            }
            $strings[] = $element;
        }

        return $strings;
    }

    /**
     * Reads a JSON array of integers.
     *
     * @return list<int>
     *
     * @throws MalformedDataException
     */
    public static function toIntList(string $json): array
    {
        $integers = [];
        foreach (self::toList($json) as $element) {
            if (!is_int($element)) {
                throw self::elementMismatch('integers', $element, $json);
            }
            $integers[] = $element;
        }

        return $integers;
    }

    /**
     * Reads a JSON array of numbers, widening each integer the way {@see self::toFloat()} does.
     *
     * @return list<float>
     *
     * @throws MalformedDataException
     */
    public static function toFloatList(string $json): array
    {
        $numbers = [];
        foreach (self::toList($json) as $element) {
            if (!is_float($element) && !is_int($element)) {
                throw self::elementMismatch('numbers', $element, $json);
            }
            $numbers[] = (float) $element;
        }

        return $numbers;
    }

    /**
     * Reads a JSON array of booleans.
     *
     * @return list<bool>
     *
     * @throws MalformedDataException
     */
    public static function toBoolList(string $json): array
    {
        $booleans = [];
        foreach (self::toList($json) as $element) {
            if (!is_bool($element)) {
                throw self::elementMismatch('booleans', $element, $json);
            }
            $booleans[] = $element;
        }

        return $booleans;
    }

    /**
     * Reads a body that is one case of a string-backed enum.
     *
     * An enum schema is generated as a backed enum, not as a model — there is no `fromArray()` to
     * hand it to.
     *
     * @template T of BackedEnum
     *
     * @param class-string<T> $enum
     *
     * @return T
     *
     * @throws MalformedDataException
     */
    public static function toStringEnum(string $json, string $enum): BackedEnum
    {
        return self::caseOf($enum, self::toString($json), $json);
    }

    /**
     * Reads a body that is one case of an int-backed enum.
     *
     * @template T of BackedEnum
     *
     * @param class-string<T> $enum
     *
     * @return T
     *
     * @throws MalformedDataException
     */
    public static function toIntEnum(string $json, string $enum): BackedEnum
    {
        return self::caseOf($enum, self::toInt($json), $json);
    }

    /**
     * Reads a JSON array whose elements are cases of a string-backed enum.
     *
     * @template T of BackedEnum
     *
     * @param class-string<T> $enum
     *
     * @return list<T>
     *
     * @throws MalformedDataException
     */
    public static function toStringEnumList(string $json, string $enum): array
    {
        $cases = [];
        foreach (self::toStringList($json) as $value) {
            $cases[] = self::caseOf($enum, $value, $json);
        }

        return $cases;
    }

    /**
     * Reads a JSON array whose elements are cases of an int-backed enum.
     *
     * @template T of BackedEnum
     *
     * @param class-string<T> $enum
     *
     * @return list<T>
     *
     * @throws MalformedDataException
     */
    public static function toIntEnumList(string $json, string $enum): array
    {
        $cases = [];
        foreach (self::toIntList($json) as $value) {
            $cases[] = self::caseOf($enum, $value, $json);
        }

        return $cases;
    }

    /**
     * Whether the body is the JSON literal `null`.
     *
     * Every reader here rejects it — see {@see self::decode()} — because for most schemas `null` is
     * not a value. A schema that allows it (`nullable: true`, `type: [integer, null]`) asks this
     * first, so the one answer it has in addition is not reported as a malformed body.
     *
     * Only JSON's own four whitespace characters are trimmed: `trim()`'s default set also strips
     * NUL and vertical tab, and a body padded with those is not JSON.
     */
    public static function isNull(string $json): bool
    {
        return 'null' === trim($json, " \t\n\r");
    }

    /**
     * Reads a `type: string` body: JSON's own quoting, undone.
     *
     * @throws MalformedDataException
     */
    public static function toString(string $json): string
    {
        $decoded = self::decode($json, 'a JSON string');
        if (!is_string($decoded)) {
            throw self::mismatch('a JSON string', $decoded, $json);
        }

        return $decoded;
    }

    /**
     * Reads a `type: integer` body.
     *
     * @throws MalformedDataException
     */
    public static function toInt(string $json): int
    {
        $decoded = self::decode($json, 'a JSON integer');
        if (!is_int($decoded)) {
            throw self::mismatch('a JSON integer', $decoded, $json);
        }

        return $decoded;
    }

    /**
     * Reads a `type: number` body.
     *
     * JSON does not distinguish integers from floats, and `json_decode()` follows the text: `1.0`
     * arrives as a float, `1` as an int. A schema that says `number` accepts both spellings of the
     * same value, so both are read and the result is widened rather than rejected.
     *
     * @throws MalformedDataException
     */
    public static function toFloat(string $json): float
    {
        $decoded = self::decode($json, 'a JSON number');
        if (!is_float($decoded) && !is_int($decoded)) {
            throw self::mismatch('a JSON number', $decoded, $json);
        }

        return (float) $decoded;
    }

    /**
     * Reads a `type: boolean` body.
     *
     * @throws MalformedDataException
     */
    public static function toBool(string $json): bool
    {
        $decoded = self::decode($json, 'a JSON boolean');
        if (!is_bool($decoded)) {
            throw self::mismatch('a JSON boolean', $decoded, $json);
        }

        return $decoded;
    }

    /**
     * Reads a body whose schema states no type at all — the whole JSON value domain.
     *
     * `null` is not part of it, for the same reason the generator leaves it out of the type it
     * guesses for an untyped schema: a response body of the four bytes `null` is a document saying
     * "no value", and the operations that have one say so in their schema instead. Ruling it out is
     * what {@see self::decode()} does for every reader, so there is nothing left to check here.
     *
     * @return string|int|float|bool|array<int|string, mixed>
     *
     * @throws MalformedDataException
     */
    public static function toJsonValue(string $json): string|int|float|bool|array
    {
        return self::decode($json, 'a JSON value');
    }

    /**
     * Writes the value an operation assembled for its request body back out as JSON.
     *
     * The other direction, and here for the same reason. Encoding fails on ordinary data: one
     * string field holding bytes that are not valid UTF-8, a name read out of a Latin-1 source, is
     * enough. It comes back out as {@see MalformedDataException} because that is what it is — data
     * that cannot cross the boundary — and because a `JsonException` answers to nothing a consumer
     * was told to catch.
     *
     * A model is handed over as itself rather than as its `toArray()`: `json_encode()` asks it for
     * its JSON form, which writes an empty object as `{}` where the array would be `[]`. An enum
     * encodes as its value, a map cast to an object as an object, empty or not.
     *
     * Any value, because a body whose schema the description leaves open is any value — an empty
     * schema, or a `oneOf` with one among its branches. `json_encode()` writes everything JSON has
     * a form for; what it has none for, a resource, fails like invalid UTF-8 does and comes back
     * out the same way.
     *
     * @throws MalformedDataException
     */
    public static function encode(mixed $value): string
    {
        try {
            // Positional, as everywhere else here: named arguments are out project-wide.
            return json_encode($value, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new MalformedDataException(
                sprintf('The request body cannot be written as JSON: %s.', $exception->getMessage()),
                0,
                $exception,
            );
        }
    }

    /**
     * Parses the body into the JSON value domain, minus `null`.
     *
     * Rejecting a syntax error here rather than at each reader's type check is what makes the two
     * failures tell themselves apart: unreadable bytes are reported as unreadable, not as "expected
     * an object, got null", which would point at the schema when the document is the problem.
     *
     * @return string|int|float|bool|array<int|string, mixed>
     *
     * @throws MalformedDataException
     */
    private static function decode(string $json, string $expected): string|int|float|bool|array
    {
        try {
            /** @var string|int|float|bool|array<int|string, mixed>|null $decoded */
            // Positional, not `flags:` — named arguments are out project-wide, and the generated
            // packages inherit that rule with the file. 512 is json_decode()'s own default depth.
            $decoded = json_decode($json, true, 512, JSON_THROW_ON_ERROR);
        } catch (JsonException $exception) {
            throw new MalformedDataException(
                sprintf(
                    'Expected %s in the response body, but it is not valid JSON (%s): %s',
                    $expected,
                    $exception->getMessage(),
                    self::excerpt($json),
                ),
                0,
                $exception,
            );
        }
        if (null === $decoded) {
            throw self::mismatch($expected, null, $json);
        }

        return $decoded;
    }

    /**
     * Says what was expected, what arrived, and enough of the body to tell which is at fault.
     */
    private static function mismatch(string $expected, mixed $decoded, string $json): MalformedDataException
    {
        return new MalformedDataException(
            sprintf(
                'Expected %s in the response body, got %s: %s',
                $expected,
                get_debug_type($decoded),
                self::excerpt($json),
            ),
        );
    }

    /**
     * The list arrived, one of its elements is the wrong type.
     */
    private static function elementMismatch(
        string $expectedElements,
        mixed $element,
        string $json,
    ): MalformedDataException {
        return new MalformedDataException(
            sprintf(
                'Expected a JSON array of %s in the response body, got an element of type %s: %s',
                $expectedElements,
                get_debug_type($element),
                self::excerpt($json),
            ),
        );
    }

    /**
     * The case of `$enum` that `$value` names.
     *
     * @template T of BackedEnum
     *
     * @param class-string<T> $enum
     *
     * @return T
     *
     * @throws MalformedDataException
     */
    private static function caseOf(string $enum, string|int $value, string $json): BackedEnum
    {
        return $enum::tryFrom($value)
            ?? throw new MalformedDataException(
                sprintf(
                    'Expected a case of %s in the response body, got %s: %s',
                    $enum,
                    is_string($value) ? '"' . $value . '"' : (string) $value,
                    self::excerpt($json),
                ),
            );
    }

    /**
     * The opening bytes of the body, cut to length.
     *
     * Deliberately byte-based: `mb_substr()` would add an `ext-mbstring` requirement to every
     * generated package for a diagnostic string, and a body this call is looking at is by
     * definition one whose encoding cannot be trusted anyway.
     */
    private static function excerpt(string $json): string
    {
        return strlen($json) > self::EXCERPT_LENGTH ? substr($json, 0, self::EXCERPT_LENGTH) . '…' : $json;
    }
}
