<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Psr\Http\Message\ResponseInterface;

/**
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
trait OperationTrait
{
    abstract protected function transformResponseBody(
        ResponseInterface $response,
        ContentType $contentType,
        string $body,
        ValidationMode $validation,
    ): mixed;

    // Generated per operation (not implemented here) so its @throws tag can list
    // the exact exceptions that operation's transformResponseBody() throws.
    abstract public function parseResponse(ResponseInterface $response, ValidationMode $validation): mixed;
}
