<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\MalformedDataException;
use Prefabcortex\UpsTimeInTransit\Exception\ResponseException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_key_exists;
use function is_int;
use function is_string;

/**
 * The problem document of an error response served as `application/problem+json` (RFC 9457) —
 * whether or not the description declares the status it came with.
 *
 * Only the members RFC 9457 §3.1 defines are read. A member of the wrong type is ignored, as the
 * RFC has a consumer do; extension members stay in `getRawResponse()`.
 */
final readonly class ProblemDetails
{
    public const string MEDIA_TYPE = 'application/problem+json';

    /**
     * @param string         $type     the problem type, `about:blank` where the document names none
     * @param Option<string> $title    a short summary of the problem type
     * @param Option<int>    $status   the status code the server generated for this occurrence
     * @param Option<string> $detail   an explanation specific to this occurrence
     * @param Option<string> $instance a URI reference identifying this occurrence
     */
    private function __construct(
        public string $type,
        public Option $title,
        public Option $status,
        public Option $detail,
        public Option $instance,
    ) {
    }

    /**
     * The problem document of the response behind `$exception`.
     *
     * @return Option<self> none where the response is not served as `application/problem+json`, or
     *                      its body is not a JSON object
     */
    public static function of(ResponseException $exception): Option
    {
        if (!ContentType::fromHeader($exception->getResponse()->getHeaderLine('Content-Type'))->is(self::MEDIA_TYPE)) {
            return None::create();
        }
        try {
            $document = JsonBody::toArray($exception->getRawResponse());
        } catch (MalformedDataException) {
            return None::create();
        }

        return Some::create(
            new self(
                self::text($document, 'type')->getOrElse('about:blank'),
                self::text($document, 'title'),
                array_key_exists(
                    'status',
                    $document,
                ) && is_int($document['status']) ? Some::create($document['status']) : None::create(),
                self::text($document, 'detail'),
                self::text($document, 'instance'),
            ),
        );
    }

    /**
     * @param array<string, mixed> $document
     *
     * @return Option<string>
     */
    private static function text(array $document, string $member): Option
    {
        return array_key_exists(
            $member,
            $document,
        ) && is_string($document[$member]) ? Some::create($document[$member]) : None::create();
    }
}
