<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

/**
 * Rewrites a query parameter's value before it is serialized. Which parameters have one is settled
 * when the package is generated.
 *
 * Takes and returns a {@see ParameterValue} rather than a raw scalar-or-array union, so an
 * implementation states the shape it produces instead of leaving it to be re-derived: returning
 * `new ScalarValue('true')` or `ListValue::ofScalars([...])` is checked at the boundary.
 *
 * Part of the package's public contract: it is implemented outside the package, so a change to it
 * breaks code this package does not own — which is what the BC check has to see.
 */
interface QueryParameterTransformer
{
    public function transform(ParameterValue $value): ParameterValue;
}
