<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

/**
 * One query parameter: its wire name, its value, and whether reserved characters may travel
 * verbatim.
 *
 * `allowReserved` sits here rather than in a separate `getQueryAllowReserved(): list<string>`
 * lookup on the operation, because it is a property of the parameter. Keeping it alongside the
 * value removes the name-based `in_array()` that the split representation required.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class QueryParameter
{
    public function __construct(public string $name, public ParameterValue $value, public bool $allowReserved)
    {
    }

    public function withValue(ParameterValue $value): self
    {
        return new self($this->name, $value, $this->allowReserved);
    }
}
