<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use function array_values;
use function implode;

/**
 * The query parameters of one operation, in spec order.
 *
 * Built by a generated parameter object from its own typed properties, so the collection carries
 * each parameter's name, shape and `allowReserved` flag together instead of an `array<string,
 * mixed>` that serialization would have to re-interpret.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class QueryParameters
{
    /** @var list<QueryParameter> */
    public array $parameters;

    /**
     * Variadic rather than an `array` plus a docblock: the element type is then a real type hint
     * that PHP enforces — and that the runtime reachability scan can see, so `QueryParameter` ships
     * with the packages that use this one instead of being a name only a comment mentions.
     */
    public function __construct(QueryParameter ...$parameters)
    {
        $this->parameters = array_values($parameters);
    }

    public static function none(): self
    {
        return new self();
    }

    /**
     * Joins every parameter's pairs with `&`.
     *
     * A parameter that renders to nothing — an empty list or map — contributes no pairs at all, so
     * it cannot leave a separator behind: no leading or trailing `&`, no extra empty parameter.
     */
    public function encode(): string
    {
        $pairs = [];
        foreach ($this->parameters as $parameter) {
            foreach ($parameter->value->toQueryPairs($parameter->name, $parameter->allowReserved) as $pair) {
                $pairs[] = $pair;
            }
        }

        return implode('&', $pairs);
    }

    /**
     * Applies a transformer to the parameter of the given wire name, leaving every other parameter
     * and the overall order untouched. A name that is not present is a no-op, so generated code
     * needs no existence check of its own.
     */
    public function mapValue(string $name, QueryParameterTransformer $transformer): self
    {
        $parameters = [];
        foreach ($this->parameters as $parameter) {
            $parameters[] = $name === $parameter->name ? $parameter->withValue(
                $transformer->transform($parameter->value),
            ) : $parameter;
        }

        return new self(...$parameters);
    }
}
