<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use DateTimeImmutable;
use Prefabcortex\UpsTimeInTransit\Exception\ResponseException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_values;
use function count;
use function max;
use function preg_match;
use function str_ends_with;
use function trim;

/**
 * How long the server asks the client to wait before the next attempt — the `Retry-After` header of
 * the response behind an exception, typically a 429 or a 503 (RFC 9110 §10.2.3).
 *
 * The header is a number of seconds or an HTTP date. Both are read; {@see self::secondsFrom()}
 * answers the one question a retry needs either way.
 */
final readonly class RetryAfter
{
    /**
     * The HTTP date formats a recipient has to accept (RFC 9110 §5.6.7), each zoned in GMT.
     */
    private const array DATE_FORMATS = [
        '!D, d M Y H:i:s T',
        // IMF-fixdate: Sun, 06 Nov 1994 08:49:37 GMT
        '!l, d-M-y H:i:s T',
        // RFC 850:     Sunday, 06-Nov-94 08:49:37 GMT
        '!D M j H:i:s Y T',
    ];

    private function __construct(private int|DateTimeImmutable $value)
    {
    }

    /**
     * The header of the response behind `$exception`.
     *
     * @return Option<self> none where the response has no `Retry-After`, more than one, or one that
     *                      is neither a number of seconds nor an HTTP date
     */
    public static function of(ResponseException $exception): Option
    {
        $values = array_values($exception->getResponse()->getHeader('Retry-After'));
        if (1 !== count($values)) {
            return None::create();
        }
        // Nine digits are some thirty years; a longer number is no wait anyone means.
        $value = trim($values[0]);
        if (1 === preg_match('/^\d{1,9}$/', $value)) {
            return Some::create(new self((int) $value));
        }
        $zoned = str_ends_with($value, ' GMT') ? $value : $value . ' GMT';
        foreach (self::DATE_FORMATS as $format) {
            $date = DateTimeImmutable::createFromFormat($format, $zoned);
            if (false !== $date && false === DateTimeImmutable::getLastErrors()) {
                return Some::create(new self($date));
            }
        }

        return None::create();
    }

    /**
     * The seconds left to wait at `$now`; zero once the date has passed.
     */
    public function secondsFrom(DateTimeImmutable $now): int
    {
        if ($this->value instanceof DateTimeImmutable) {
            return max(0, $this->value->getTimestamp() - $now->getTimestamp());
        }

        return $this->value;
    }
}
