<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Override;

use function is_bool;
use function rawurlencode;
use function strtr;

/**
 * A single scalar parameter value.
 *
 * The native union is the whole point: a generated parameter object passes its typed property
 * straight in, and PHP itself rejects anything that has no wire representation.
 *
 * Part of the package's public contract: a {@see QueryParameterTransformer} reads and builds it.
 */
final readonly class ScalarValue implements ParameterValue
{
    /**
     * Percent-encodings of the RFC 3986 reserved set — gen-delims `:/?#[]@` and sub-delims
     * `!$&'()*+,;=` — mapped back to their literal character.
     *
     * `allowReserved` is expressed as a subtraction from full encoding rather than as a character
     * allowlist: encode everything, then let exactly these back through. A value like a space is
     * therefore still `%20`, because it is not reserved — passing it through raw would produce a
     * URL that is invalid rather than merely unpretty.
     */
    private const array RESERVED = [
        '%3A' => ':',
        '%2F' => '/',
        '%3F' => '?',
        '%23' => '#',
        '%5B' => '[',
        '%5D' => ']',
        '%40' => '@',
        '%21' => '!',
        '%24' => '$',
        '%26' => '&',
        '%27' => "'",
        '%28' => '(',
        '%29' => ')',
        '%2A' => '*',
        '%2B' => '+',
        '%2C' => ',',
        '%3B' => ';',
        '%3D' => '=',
    ];

    public function __construct(public string|int|float|bool $value)
    {
    }

    #[Override]
    public function toQueryPairs(string $name, bool $allowReserved): array
    {
        return [rawurlencode($name) . '=' . $this->toEncodedValue($allowReserved)];
    }

    /**
     * The value alone, percent-encoded for a query string — the part a non-exploded style strings
     * together with the others behind one name.
     */
    public function toEncodedValue(bool $allowReserved): string
    {
        return self::encode($this->toWireString(), $allowReserved);
    }

    #[Override]
    public function toHeaderValues(): array
    {
        return [$this->toWireString()];
    }

    /**
     * Booleans travel as `true`/`false` rather than PHP's `1`/`""` cast, which would make `false`
     * indistinguishable from an absent value.
     */
    private function toWireString(): string
    {
        return is_bool($this->value) ? $this->value ? 'true' : 'false' : (string) $this->value;
    }

    private static function encode(string $value, bool $allowReserved): string
    {
        $encoded = rawurlencode($value);

        return $allowReserved ? strtr($encoded, self::RESERVED) : $encoded;
    }
}
