<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_key_exists;
use function array_values;
use function implode;
use function in_array;
use function sprintf;

/**
 * One `{name}` of a server URL template, as the Server Variable Object describes it.
 *
 * The `default` "SHALL be sent if an alternate value is not supplied", and an `enum` limits the
 * alternates. A variable without a default is not something the specification allows — it is
 * REQUIRED — but a description may use one in its URL without defining it
 * (`http://{subdomain}.testserver` and no `subdomain` among its variables). Nothing can be sent for
 * it until the caller says what, which is exactly what `required()` stands for.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class ServerVariable
{
    /**
     * @param Option<string> $default
     * @param list<string>   $enum    empty where any value will do
     */
    private function __construct(public string $name, private Option $default, private array $enum)
    {
    }

    public static function of(string $name, string $default, string ...$enum): self
    {
        return new self($name, Some::create($default), array_values($enum));
    }

    /**
     * A variable the caller has to set, because the description gives it no default.
     */
    public static function required(string $name, string ...$enum): self
    {
        return new self($name, None::create(), array_values($enum));
    }

    public function accepts(string $value): bool
    {
        return [] === $this->enum || in_array($value, $this->enum, true);
    }

    /**
     * The value to substitute: the caller's where they gave one, the default otherwise.
     *
     * @param array<string, string> $values the values the caller set, by variable name
     *
     * @throws UnsupportedValueException when the caller's value is not one the variable allows, or
     *                                   there is neither a value nor a default
     */
    public function valueFrom(array $values): string
    {
        if (array_key_exists($this->name, $values)) {
            $value = $values[$this->name];
            if (!$this->accepts($value)) {
                throw new UnsupportedValueException(
                    sprintf(
                        'The server variable "%s" takes one of "%s", not "%s".',
                        $this->name,
                        implode('", "', $this->enum),
                        $value,
                    ),
                );
            }

            return $value;
        }
        if (!$this->default->isDefined()) {
            throw new UnsupportedValueException(
                sprintf(
                    'The server variable "%s" has no default; set one with ClientConfig::withServerVariable().',
                    $this->name,
                ),
            );
        }

        return $this->default->get();
    }
}
