<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;

use function array_key_exists;
use function rtrim;
use function sprintf;

/**
 * Which server each operation is sent to.
 *
 * OpenAPI gives every operation the `servers` of the operation, else of its path, else of the
 * document — the more specific list replaces the broader one. The generated package groups the
 * operations by the list they end up with, a *server set*, and this holds the server chosen for
 * each: the document's under {@see self::ROOT}, every other under the key its operations name in
 * `Operation::getServerSet()`.
 *
 * A server is kept as its template until a request is made. The caller's variable values apply to
 * every chosen server that declares the variable, by name — a `site` that picks the region does so
 * for an API and its log intake alike. A relative server URL is resolved against the origin the
 * caller gives, as the specification resolves it against the place the description is served from.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class ServerSelection
{
    /**
     * The set of the servers the document names at its top.
     */
    public const string ROOT = 'Server';

    /**
     * @param array<string, ServerUrl> $chosen     set => its server
     * @param array<string, string>    $unchosen   set => why no server is chosen for it
     * @param Option<string>           $everywhere one address for every operation, whatever its set
     * @param array<string, string>    $variables  the caller's values, by variable name
     * @param Option<string>           $origin     what relative server URLs resolve against
     */
    private function __construct(
        private array $chosen,
        private array $unchosen,
        private Option $everywhere,
        private array $variables,
        private Option $origin,
    ) {
    }

    /**
     * The document's own servers, with this one chosen.
     */
    public static function serving(ServerUrl $server): self
    {
        return new self([self::ROOT => $server], [], None::create(), [], None::create());
    }

    /**
     * Every operation to one address — a mock server, a proxy — whatever its description says.
     */
    public static function everywhere(string $baseUrl): self
    {
        return new self([], [], Some::create($baseUrl), [], None::create());
    }

    public function withSet(string $set, ServerUrl $server): self
    {
        $unchosen = $this->unchosen;
        unset($unchosen[$set]);

        return new self(
            [...$this->chosen, $set => $server],
            $unchosen,
            $this->everywhere,
            $this->variables,
            $this->origin,
        );
    }

    /**
     * A set whose server cannot follow the choice made for the document's servers: its operations
     * fail with `$reason` until one is chosen.
     */
    public function withoutChoice(string $set, string $reason): self
    {
        $chosen = $this->chosen;
        unset($chosen[$set]);

        return new self(
            $chosen,
            [...$this->unchosen, $set => $reason],
            $this->everywhere,
            $this->variables,
            $this->origin,
        );
    }

    /**
     * @throws UnsupportedValueException when no chosen server declares the variable, or one that
     *                                   does takes other values
     */
    public function withVariable(string $name, string $value): self
    {
        if ($this->everywhere->isDefined()) {
            throw new UnsupportedValueException(
                sprintf(
                    'A configuration made with ClientConfig::forBaseUrl() sends every request to one address; it has no server variable "%s".',
                    $name,
                ),
            );
        }
        $declared = false;
        foreach ($this->chosen as $server) {
            if (!$server->declares($name)) {
                continue;
            }
            $declared = true;
            if (!$server->accepts($name, $value)) {
                throw new UnsupportedValueException(
                    sprintf(
                        'The server `%s` does not take "%s" for its variable "%s".',
                        $server->template,
                        $value,
                        $name,
                    ),
                );
            }
        }
        if (!$declared) {
            throw new UnsupportedValueException(sprintf('None of the chosen servers has a variable "%s".', $name));
        }

        return new self(
            $this->chosen,
            $this->unchosen,
            $this->everywhere,
            [...$this->variables, $name => $value],
            $this->origin,
        );
    }

    /** @throws UnsupportedValueException when the origin is not an absolute URL with a host */
    public function withOrigin(string $origin): self
    {
        if (!UriReference::isAbsoluteWithHost($origin)) {
            throw new UnsupportedValueException(
                sprintf('An origin must carry a scheme and a host, got "%s".', $origin),
            );
        }

        return new self($this->chosen, $this->unchosen, $this->everywhere, $this->variables, Some::create($origin));
    }

    /**
     * The URL a set's operation paths are appended to, without a trailing slash: the specification
     * appends a path that starts with `/`.
     *
     * @throws UnsupportedValueException when the set has no server, or its server cannot address
     *                                   one
     */
    public function baseUrl(string $set): string
    {
        return rtrim($this->serverUrl($set), '/');
    }

    /**
     * A URL the description gives relative to a set's server — an OAuth `tokenUrl` — resolved
     * against it as RFC 3986 resolves a reference.
     *
     * @throws UnsupportedValueException when the set has no server, or its server cannot address
     *                                   one
     */
    public function resolve(string $set, string $reference): string
    {
        return UriReference::resolve($this->serverUrl($set), $reference);
    }

    /**
     * Resolves the document's server once, so a configuration that cannot address it fails where it
     * was made rather than on the first request. The other sets are left to the operations that use
     * them: a health check sent to `url: ''` should not make every caller say where the API runs,
     * only the one who calls it.
     *
     * @throws UnsupportedValueException
     */
    public function check(): void
    {
        $this->serverUrl(self::ROOT);
    }

    /** @throws UnsupportedValueException */
    private function serverUrl(string $set): string
    {
        if ($this->everywhere->isDefined()) {
            $url = $this->everywhere->get();
            if (!UriReference::isAbsoluteWithHost($url)) {
                throw new UnsupportedValueException(
                    sprintf('Base URL must carry a scheme and a host, got "%s".', $url),
                );
            }

            return $url;
        }
        if (array_key_exists($set, $this->unchosen)) {
            throw new UnsupportedValueException($this->unchosen[$set]);
        }
        if (!array_key_exists($set, $this->chosen)) {
            throw new UnsupportedValueException(sprintf('No server is configured for the operations of "%s".', $set));
        }
        $server = $this->chosen[$set];
        $url = $server->expand($this->variables);
        if (UriReference::isAbsoluteWithHost($url)) {
            return $url;
        }
        if (!$this->origin->isDefined()) {
            throw new UnsupportedValueException(
                sprintf(
                    'The server `%s` is relative to wherever the API is served; say where with ClientConfig::withOrigin().',
                    $server->template,
                ),
            );
        }
        $resolved = UriReference::resolve($this->origin->get(), $url);
        if (!UriReference::isAbsoluteWithHost($resolved)) {
            throw new UnsupportedValueException(
                sprintf(
                    'The server `%s` does not address a host, even against "%s".',
                    $server->template,
                    $this->origin->get(),
                ),
            );
        }

        return $resolved;
    }
}
