<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;

use function array_key_exists;
use function str_replace;

/**
 * A server URL as the description writes it: a template and its variables.
 *
 * Kept as a template until a request is made, not expanded when the package is generated: the
 * default of a variable is only what "SHALL be sent if an alternate value is not supplied", and the
 * alternates — a `site`, a `region` — are the caller's to supply.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final readonly class ServerUrl
{
    /** @param array<string, ServerVariable> $variables by name */
    private function __construct(public string $template, private array $variables)
    {
    }

    public static function of(string $template, ServerVariable ...$variables): self
    {
        $byName = [];
        foreach ($variables as $variable) {
            $byName[$variable->name] = $variable;
        }

        return new self($template, $byName);
    }

    public function declares(string $name): bool
    {
        return array_key_exists($name, $this->variables);
    }

    public function accepts(string $name, string $value): bool
    {
        return array_key_exists($name, $this->variables) && $this->variables[$name]->accepts($value);
    }

    /**
     * The template with every variable substituted. The values go in as they are: the specification
     * says nothing about encoding them, and some carry what a URL needs verbatim — a `{server}`
     * that is the scheme and host together.
     *
     * @param array<string, string> $values the values the caller set, by variable name
     *
     * @throws UnsupportedValueException when a value is not one its variable allows, or a variable
     *                                   without a default was not set
     */
    public function expand(array $values): string
    {
        $url = $this->template;
        foreach ($this->variables as $name => $variable) {
            $url = str_replace('{' . $name . '}', $variable->valueFrom($values), $url);
        }

        return $url;
    }
}
