<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;

use function min;
use function sprintf;

/**
 * How long a request may take: to connect, and in all.
 *
 * It applies to the HTTP client this package builds itself. A client handed over through
 * `ClientConfig::withHttpClient()` keeps whatever its owner configured, because the package cannot
 * reach into it and should not try.
 *
 * There is a default because Guzzle and cURL wait forever unless told otherwise, and a request
 * against a hanging endpoint would block its caller indefinitely. Ten seconds to connect is long
 * for any server that is up; a minute in all leaves room for an API that renders a document before
 * it answers.
 */
final readonly class Timeout
{
    private const float DEFAULT_CONNECT_SECONDS = 10.0;
    private const float DEFAULT_TOTAL_SECONDS = 60.0;

    private function __construct(public float $connectSeconds, public float $totalSeconds)
    {
    }

    /**
     * Ten seconds to connect, sixty in all.
     */
    public static function defaults(): self
    {
        return new self(self::DEFAULT_CONNECT_SECONDS, self::DEFAULT_TOTAL_SECONDS);
    }

    /**
     * A limit for the whole request; connecting gets the default ten seconds, or all of it where
     * the limit is shorter.
     *
     * @throws UnsupportedValueException when the limit is not above zero
     */
    public static function seconds(float $totalSeconds): self
    {
        return self::of(min(self::DEFAULT_CONNECT_SECONDS, $totalSeconds), $totalSeconds);
    }

    /**
     * @throws UnsupportedValueException when a limit is not above zero, or connecting may take
     *                                   longer than the whole request
     */
    public static function of(float $connectSeconds, float $totalSeconds): self
    {
        if ($connectSeconds <= 0.0 || $totalSeconds <= 0.0 || $connectSeconds > $totalSeconds) {
            throw new UnsupportedValueException(
                sprintf(
                    'A timeout needs 0 < connect <= total seconds, got %s to connect and %s in all.',
                    $connectSeconds,
                    $totalSeconds,
                ),
            );
        }

        return new self($connectSeconds, $totalSeconds);
    }
}
