<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;

use function array_pop;
use function implode;
use function preg_match;
use function sprintf;
use function str_starts_with;
use function strpos;
use function strrpos;
use function substr;

/**
 * A URI reference resolved against a base URI, as RFC 3986 section 5.2 defines it.
 *
 * OpenAPI leans on this twice: a server URL "MAY be relative, to indicate that the host location is
 * relative to the location where the document containing the Server Object is being served", and
 * other URL fields — an OAuth flow's `tokenUrl` — "are resolved using the URLs defined in the
 * Server Object as a Base URL". Both are the RFC's resolution, not string concatenation: `../token`
 * against `https://host/api/v2` is `https://host/api/token`.
 *
 * The request path is the one place this does not apply. The specification appends a Paths key to
 * the server URL "(no relative URL resolution)", and `ClientTrait` does exactly that.
 *
 * @internal plumbing of the generated package, not part of its public contract: only the
 *                    generated operations and client touch this, and it may change in any release
 */
final class UriReference
{
    /**
     * RFC 3986 appendix B, with a capture around each component's delimiter as well, so an absent
     * component (no `?` at all) stays apart from a present and empty one (`?` alone).
     */
    private const string COMPONENTS = '~^(([^:/?#]+):)?(//([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$~s';

    private function __construct()
    {
    }

    /**
     * @param string $base      an absolute URI — it must carry a scheme
     * @param string $reference any URI reference, absolute or relative
     *
     * @throws UnsupportedValueException when the base carries no scheme and so resolves nothing
     */
    public static function resolve(string $base, string $reference): string
    {
        $b = self::components($base);
        if (!$b['hasScheme']) {
            throw new UnsupportedValueException(
                sprintf('A relative reference needs an absolute base URI, got "%s".', $base),
            );
        }
        $r = self::components($reference);
        $target = $r;
        // Section 5.2.2, with the strict parser: a reference with a scheme is absolute on its own.
        if ($r['hasScheme']) {
            $target['path'] = self::removeDotSegments($r['path']);

            return self::recompose($target);
        }
        $target['scheme'] = $b['scheme'];
        $target['hasScheme'] = true;
        if ($r['hasAuthority']) {
            $target['path'] = self::removeDotSegments($r['path']);

            return self::recompose($target);
        }
        $target['authority'] = $b['authority'];
        $target['hasAuthority'] = $b['hasAuthority'];
        if ('' === $r['path']) {
            $target['path'] = $b['path'];
            if (!$r['hasQuery']) {
                $target['query'] = $b['query'];
                $target['hasQuery'] = $b['hasQuery'];
            }

            return self::recompose($target);
        }
        $target['path'] = str_starts_with(
            $r['path'],
            '/',
        ) ? self::removeDotSegments($r['path']) : self::removeDotSegments(
            self::merge($b['hasAuthority'], $b['path'], $r['path']),
        );

        return self::recompose($target);
    }

    /**
     * Whether a URI reference is absolute and names a host — the only kind a request can be sent
     * to.
     */
    public static function isAbsoluteWithHost(string $uri): bool
    {
        $components = self::components($uri);

        return $components['hasScheme'] && '' !== $components['authority'];
    }

    /** @return array{scheme: string, hasScheme: bool, authority: string, hasAuthority: bool, path: string, query: string, hasQuery: bool, fragment: string, hasFragment: bool} */
    private static function components(string $reference): array
    {
        // The pattern matches every string: each group is optional, and the path takes anything.
        preg_match(self::COMPONENTS, $reference, $matches);

        return [
            'scheme' => $matches[2] ?? '',
            'hasScheme' => '' !== ($matches[1] ?? ''),
            'authority' => $matches[4] ?? '',
            'hasAuthority' => '' !== ($matches[3] ?? ''),
            'path' => $matches[5] ?? '',
            'query' => $matches[7] ?? '',
            'hasQuery' => '' !== ($matches[6] ?? ''),
            'fragment' => $matches[9] ?? '',
            'hasFragment' => '' !== ($matches[8] ?? ''),
        ];
    }

    /**
     * Section 5.2.3.
     */
    private static function merge(bool $baseHasAuthority, string $basePath, string $path): string
    {
        if ($baseHasAuthority && '' === $basePath) {
            return '/' . $path;
        }
        $lastSlash = strrpos($basePath, '/');

        return false === $lastSlash ? $path : substr($basePath, 0, $lastSlash + 1) . $path;
    }

    /**
     * Section 5.2.4.
     */
    private static function removeDotSegments(string $path): string
    {
        $input = $path;
        $output = [];
        while ('' !== $input) {
            if (str_starts_with($input, '../')) {
                $input = substr($input, 3);
            } elseif (str_starts_with($input, './')) {
                $input = substr($input, 2);
            } elseif (str_starts_with($input, '/./')) {
                $input = substr($input, 2);
            } elseif ('/.' === $input) {
                $input = '/';
            } elseif (str_starts_with($input, '/../')) {
                $input = substr($input, 3);
                array_pop($output);
            } elseif ('/..' === $input) {
                $input = '/';
                array_pop($output);
            } elseif ('.' === $input || '..' === $input) {
                $input = '';
            } else {
                $next = strpos($input, '/', str_starts_with($input, '/') ? 1 : 0);
                $output[] = false === $next ? $input : substr($input, 0, $next);
                $input = false === $next ? '' : substr($input, $next);
            }
        }

        return implode('', $output);
    }

    /**
     * Section 5.3.
     *
     * @param array{scheme: string, hasScheme: bool, authority: string, hasAuthority: bool, path: string, query: string, hasQuery: bool, fragment: string, hasFragment: bool} $uri
     */
    private static function recompose(array $uri): string
    {
        return ($uri['hasScheme'] ? $uri['scheme'] . ':' : '') . ($uri['hasAuthority'] ? '//' . $uri['authority'] : '') . $uri['path'] . ($uri['hasQuery'] ? '?' . $uri['query'] : '') . ($uri['hasFragment'] ? '#' . $uri['fragment'] : '');
    }
}
