<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Http;

/**
 * How closely requests and responses are held to the constraints of the API description.
 *
 * The description says what the API *should* take and send; the API is the one that actually does,
 * and the two drift apart — a code declared three characters long whose every documented value has
 * two, a `maximum` on a weight that was meant as "at most once", a `detail` one character past its
 * `maxLength`. Held to such a description, a request the API would have answered never leaves, and
 * a response it did send cannot be read. So `Lax` is the default, and `Strict` is the choice for an
 * API that keeps to its description.
 *
 * Neither setting can switch off what a typed model needs to exist at all — a property of the
 * declared type, a required property present, an enum value it has a case for when sending.
 *
 * The two differ only in a package generated with validation. Without it there are no constraints
 * to hold anything to, and both behave the same way.
 */
enum ValidationMode
{
    /**
     * The constraints are skipped. A request is sent as its models hold it, and a response is read
     * as far as its model can hold it: lengths, patterns, ranges and formats reject nothing, and
     * `null` in an optional property reads as absent.
     */
    case Lax;
    /**
     * Every constraint the description declares is checked. A request that breaks one raises
     * `ValidationException` and is not sent; a response that breaks one raises
     * `ResponseValidationException` before it is read.
     */
    case Strict;
}
