<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Optional;

use Override;
use RuntimeException;

/** @implements Option<never> */
final class None implements Option
{
    private static ?self $instance = null;

    public static function create(): self
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    #[Override]
    public function isDefined(): bool
    {
        return false;
    }

    /** @throws RuntimeException */
    #[Override]
    public function get(): never
    {
        throw new RuntimeException('None has no value.');
    }

    /**
     * @template U
     *
     * @param U $default
     *
     * @return U
     */
    #[Override]
    public function getOrElse(mixed $default): mixed
    {
        return $default;
    }
}
