<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Optional;

/** @template-covariant T */
interface Option
{
    public function isDefined(): bool;

    /**
     * The value, which must be there: an `Option` holding none throws `RuntimeException`.
     *
     * That exception is the caller's mistake, not a way the API fails, and so deliberately not an
     * `ApiException`; `isDefined()` or `getOrElse()` avoid it. Said here in prose rather than as a
     * `@throws` tag: every read inside the package asks `isDefined()` first, and a tag on the
     * interface would put a `RuntimeException` into the `@throws` of every model getter that cannot
     * raise it.
     *
     * @return T
     */
    public function get(): mixed;

    /**
     * The value, or the one to use when there is none.
     *
     * Every consumer wrote `$o->isDefined() ? $o->get() : $default` by hand, which is three
     * mentions of `$o` to express one thing and puts the reader in front of a conditional where
     * there is no decision to make. The two methods stay: `isDefined()` for the branch that really
     * is one, `get()` for the value that must be there.
     *
     * @template U
     *
     * @param U $default
     *
     * @return T|U
     */
    public function getOrElse(mixed $default): mixed;
}
