<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Optional;

use Override;

/**
 * @template-covariant T
 *
 * @implements Option<T>
 */
final readonly class Some implements Option
{
    /** @param T $value */
    private function __construct(private mixed $value)
    {
    }

    /**
     * @template U
     *
     * @param U $value
     *
     * @return self<U>
     */
    public static function create(mixed $value): self
    {
        return new self($value);
    }

    #[Override]
    public function isDefined(): bool
    {
        return true;
    }

    /** @return T */
    #[Override]
    public function get(): mixed
    {
        return $this->value;
    }

    /**
     * @template U
     *
     * @param U $default
     *
     * @return T
     */
    #[Override]
    public function getOrElse(mixed $default): mixed
    {
        return $this->value;
    }
}
