<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Throwable;

/**
 * The root of everything this package throws.
 *
 * The README promises that one `catch (ApiException $e)` covers the whole package, and that promise
 * is only worth having if it is literally true — a consumer who writes the catch the documentation
 * shows them and still loses the two most common failures of a broken response
 * (`ValidationException` and a body that is not valid JSON) is worse off than one who was told
 * nothing. So the marker is not a decoration on the operation exceptions: it is the type every
 * throw site in the package answers to.
 *
 * The interface stays empty on purpose. Everything a caller can *ask* an exception is declared one
 * level down on `ResponseException`, because it is only true one level down:
 * `NoHttpClientException` is thrown before a request is ever made and has no response to hand back.
 */
interface ApiException extends Throwable
{
}
