<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

/**
 * The 4xx side of the error surface: the request is at fault.
 *
 * Implemented by the abstract class the generator writes for every declared status below 500, and
 * through it by every operation exception under one. A response is always in hand by the time one
 * of these is raised, hence {@see ResponseException} rather than the bare marker.
 */
interface ClientException extends ResponseException
{
}
