<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Psr\Http\Message\ResponseInterface;
use UnexpectedValueException;

use function implode;
use function sprintf;

/**
 * A response that arrived and cannot be read into what its description declares: not JSON, a
 * property of another type, a required property missing, an enum value the model has no case for.
 *
 * The request behind it reached the API, and whatever it asked for may well have happened. The
 * plain {@see MalformedDataException} says nothing of the kind and keeps nothing of the response.
 * This carries the response, its code is the response's status, and the reader's own message is
 * `getPrevious()`.
 *
 * A sibling of `MalformedDataException` below the same `UnexpectedValueException`, not a subclass:
 * that class is also what a request body JSON cannot represent raises, before anything is sent.
 *
 * `ValidationMode::Lax` does not skip this: what fails here is what a typed model needs in order to
 * exist at all. The message says so, so nobody looks for a setting that would.
 */
final class MalformedResponseException extends UnexpectedValueException implements ResponseException
{
    public function __construct(
        MalformedDataException $previous,
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
    ) {
        // One sentence per entry rather than one literal split with `.`: the printer that writes this
        // class into a package puts a concatenation on a single line, and the fixer then merges it.
        parent::__construct(
            implode(
                ' ',
                [
                    sprintf(
                        'The %d response cannot be read as the API description declares it: %s',
                        $response->getStatusCode(),
                        $previous->getMessage(),
                    ),
                    'The API does not keep to its own description here, and the request did reach it:',
                    'do not simply send it again, read getRawResponse() instead.',
                    'No ValidationMode skips this one, because the typed model cannot hold the value.',
                ],
            ),
            $response->getStatusCode(),
            $previous,
        );
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }
}
