<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use UnexpectedValueException;

/**
 * Data that cannot cross the boundary between a JSON document and a typed model.
 *
 * Every place the two meet raises this. Reading: the JSON reader, when a response body is not valid
 * JSON or decodes to the wrong shape, and every generated `fromArray()`, when a property arrives
 * with a type the description does not allow. Writing: the encoder, when a request body holds
 * something JSON cannot represent — a string field carrying bytes that are not valid UTF-8 is the
 * case that actually happens. Different directions, one question — is this data what the
 * description says it is — so one type to catch.
 *
 * Extends `UnexpectedValueException`, so a `catch` of the SPL type matches it, and carries the
 * marker, so `catch (ApiException $e)` covers a malformed response — the single likeliest way a
 * call goes wrong.
 *
 * In a package with API operations, a response one of them cannot read does not leave it as this
 * class: the operation raises `MalformedResponseException` in its place, which also hands back the
 * response that arrived.
 */
final class MalformedDataException extends UnexpectedValueException implements ApiException
{
}
