<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\NetworkExceptionInterface;
use Psr\Http\Message\RequestInterface;
use RuntimeException;

use function sprintf;

/**
 * The request never reached the server: the host did not resolve, the connection was refused, the
 * read timed out.
 *
 * This is the branch retry logic wants. A network failure says nothing about whether the call was
 * acceptable — repeating it verbatim is usually right, where repeating a rejected request is
 * usually pointless. It carries `NetworkExceptionInterface` so a `catch` written against the PSR
 * type keeps working, and {@see TransportException} so the documented single catch covers it too.
 *
 * Raised only by re-throwing what the PSR-18 client reported; nothing in this package decides on
 * its own that a connection failed.
 */
final class NetworkException extends RuntimeException implements TransportException, NetworkExceptionInterface
{
    public function __construct(private readonly RequestInterface $request, ClientExceptionInterface $previous)
    {
        parent::__construct(
            sprintf('The request to %s could not be sent: %s', $request->getUri(), $previous->getMessage()),
            0,
            $previous,
        );
    }

    #[Override]
    public function getRequest(): RequestInterface
    {
        return $this->request;
    }
}
