<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use RuntimeException;

use function implode;
use function sprintf;

/**
 * Thrown when no PSR-18 client can be found and none was configured.
 *
 * The package's `composer.json` requires the virtual `psr/http-client-implementation`, so Composer
 * refuses to install it into a project that has no PSR-18 client at all. This exception covers what
 * that requirement cannot: an implementation is installed, but it is one `HttpClientResolver` does
 * not know by name. The remedy is then not to install anything — it is to hand the client over
 * directly, so the message says so and names what was looked for.
 *
 * It is an {@see ApiException} and not a {@see ResponseException}: it comes from the same package
 * and belongs under the same catch, but it is raised while the client is still being assembled — no
 * request has gone out, so there is no response to hand back.
 */
final class NoHttpClientException extends RuntimeException implements ApiException
{
    /** @param list<string> $candidates the class names that were looked for, in the order tried */
    public static function noneOf(array $candidates): self
    {
        // One literal rather than two joined by `.`: this file is copied into every generated
        // package, where `no_useless_concat_operator` would merge them anyway and the two
        // spellings would drift apart between a run with the fixer and one without.
        return new self(
            sprintf(
                'No PSR-18 HTTP client found. None of the known implementations is installed (%s). Install one of them, or pass the client you already use to ClientConfig::withHttpClient().',
                implode(', ', $candidates),
            ),
        );
    }
}
