<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\RequestExceptionInterface;
use Psr\Http\Message\RequestInterface;
use RuntimeException;

use function sprintf;

/**
 * The client refused the request itself — it never got as far as the network.
 *
 * PSR-18 gives two examples and both are about the message rather than the connection: a request
 * missing its method, a body stream that cannot be rewound. Repeating such a call unchanged fails
 * the same way, which is what separates this from {@see NetworkException} and why the two are kept
 * apart rather than folded together.
 *
 * Named to pair with `ResponseException`: that one is raised once a response exists, this one when
 * none ever will. The pairing is deliberate even though one is an interface and the other a class —
 * the generated status exceptions need a type to implement, a re-thrown transport failure needs a
 * type to be.
 */
final class RequestException extends RuntimeException implements TransportException, RequestExceptionInterface
{
    public function __construct(private readonly RequestInterface $request, ClientExceptionInterface $previous)
    {
        parent::__construct(
            sprintf(
                'The request to %s was rejected before it was sent: %s',
                $request->getUri(),
                $previous->getMessage(),
            ),
            0,
            $previous,
        );
    }

    #[Override]
    public function getRequest(): RequestInterface
    {
        return $this->request;
    }
}
