<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Psr\Http\Message\ResponseInterface;

/**
 * An {@see ApiException} raised by a response that arrived — and therefore one that can hand the
 * response back.
 *
 * Catching this type reaches the response of every exception that has one, without an `instanceof`
 * chain over the concrete classes.
 *
 * It is deliberately *not* declared on `ApiException` itself: two exceptions have no response to
 * return — `NoHttpClientException`, thrown while the client is still being built, and
 * `ValidationException`, which carries a violation list instead.
 */
interface ResponseException extends ApiException
{
    /**
     * The response as the PSR-18 client handed it over: status, headers, stream.
     *
     * A seekable body stream is back at its start, so `getBody()->getContents()` reads it whole.
     * One that cannot seek was consumed by the parsing attempt; {@see getRawResponse()} has it.
     */
    public function getResponse(): ResponseInterface;

    /**
     * The response body as text, exactly as it arrived.
     *
     * Read once at the point the exception was raised, so it is there whatever the stream allows,
     * including a stream that could be read only once.
     */
    public function getRawResponse(): string;
}
