<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Prefabcortex\UpsTimeInTransit\Validation\ValidationException;
use Psr\Http\Message\ResponseInterface;
use RuntimeException;
use Symfony\Component\Validator\ConstraintViolationInterface;
use Symfony\Component\Validator\ConstraintViolationListInterface;

use function array_slice;
use function count;
use function implode;
use function iterator_to_array;
use function sprintf;

/**
 * A response that arrived and does not satisfy the constraints its description declares.
 *
 * The request behind it reached the API, and whatever it asked for may well have happened: an order
 * placed, a payment taken. The `ValidationException` a request body raises before it is sent says
 * the opposite, and a retry on its word does it all a second time. So this carries the response,
 * and its code is the response's status rather than the 400 of the request side.
 *
 * A sibling of `ValidationException`, not a subclass: a catch of that class means "nothing was
 * sent", and this is the one case where something was.
 *
 * Raised only under `ValidationMode::Strict`. The usual cause is not this package but the API: it
 * sends something its own description rules out. The message says so, and names the setting that
 * reads such responses anyway — `ClientConfig::withValidation(ValidationMode::Lax)`, the default.
 */
final class ResponseValidationException extends RuntimeException implements ResponseException
{
    /**
     * How many violations the message spells out; the rest are counted, and all are in the list.
     */
    private const int VIOLATIONS_IN_MESSAGE = 3;
    private readonly ConstraintViolationListInterface $violationList;

    public function __construct(
        ValidationException $previous,
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
    ) {
        $this->violationList = $previous->getViolationList();
        parent::__construct(
            self::describe($this->violationList, $response->getStatusCode()),
            $response->getStatusCode(),
            $previous,
        );
    }

    public function getViolationList(): ConstraintViolationListInterface
    {
        return $this->violationList;
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }

    private static function describe(ConstraintViolationListInterface $violationList, int $status): string
    {
        /** @var list<ConstraintViolationInterface> $violations */
        $violations = iterator_to_array($violationList, false);
        $described = [];
        foreach (array_slice($violations, 0, self::VIOLATIONS_IN_MESSAGE) as $violation) {
            $described[] = sprintf('%s: %s', $violation->getPropertyPath(), (string) $violation->getMessage());
        }
        $rest = count($violations) - count($described);

        // One sentence per entry rather than one literal split with `.`: the printer that writes this
        // class into a package puts a concatenation on a single line, and the fixer then merges it.
        return implode(
            ' ',
            [
                sprintf(
                    'The %d response does not match the API description (%s%s).',
                    $status,
                    implode('; ', $described),
                    $rest > 0 ? sprintf('; and %d more', $rest) : '',
                ),
                'The API does not keep to its own description here, and the request did reach it:',
                'do not simply send it again, read getRawResponse() instead.',
                'To use the API until its provider fixes this, read such responses without these checks:',
                'ClientConfig::withValidation(ValidationMode::Lax), the default.',
                'What the typed model cannot hold — a wrong type, a missing required property, an unknown',
                'enum value — is still rejected then.',
            ],
        );
    }
}
