<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

/**
 * The 5xx side of the error surface: the API is at fault.
 *
 * The counterpart of {@see ClientException}, and split from it for the one decision a consumer
 * actually makes on the difference — whether retrying the same request could ever help.
 */
interface ServerException extends ResponseException
{
}
