<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Prefabcortex\UpsTimeInTransit\Http\ErrorMessage;
use Prefabcortex\UpsTimeInTransit\Model\ErrorResponse;
use Psr\Http\Message\ResponseInterface;

final class TimeInTransitTooManyRequestsException extends TooManyRequestsException
{
    public function __construct(
        private readonly ErrorResponse $errorResponse,
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
    ) {
        parent::__construct(ErrorMessage::describe($rawResponse, 'Rate Limit Exceeded'));
    }

    public function getErrorResponse(): ErrorResponse
    {
        return $this->errorResponse;
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }
}
