<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Message\RequestInterface;
use RuntimeException;

use function sprintf;

/**
 * The call failed and the client did not say how.
 *
 * PSR-18 requires every failure to carry `ClientExceptionInterface` but leaves the two finer
 * interfaces optional, so a client may report that something went wrong without classifying it as a
 * network problem or a rejected request. This is that case, kept as its own type rather than folded
 * into one of the other two: claiming `NetworkExceptionInterface` would tell retry logic a
 * connection failed when nobody established that, and claiming `RequestExceptionInterface` would
 * blame a request the client never faulted.
 *
 * In practice it is rare — the widely used clients classify — which is exactly why it must exist:
 * the branch that almost never runs is the one no one would notice reporting a fiction.
 */
final class TransportFailedException extends RuntimeException implements TransportException
{
    public function __construct(private readonly RequestInterface $request, ClientExceptionInterface $previous)
    {
        parent::__construct(
            sprintf('The request to %s failed: %s', $request->getUri(), $previous->getMessage()),
            0,
            $previous,
        );
    }

    #[Override]
    public function getRequest(): RequestInterface
    {
        return $this->request;
    }
}
