<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Message\RequestInterface;

/**
 * An {@see ApiException} raised because the request never came back — no response exists to read.
 *
 * The PSR-18 client reports these as `ClientExceptionInterface`, which cannot be made to implement
 * {@see ApiException}. So the client's exception is caught at the one place it can be raised and
 * re-thrown as one of these, and a single `catch (ApiException $e)` covers a timeout too — the most
 * likely way a call fails in production.
 *
 * A `catch` written against the concrete class of a particular client —
 * `GuzzleHttp\Exception\ConnectException`, say — does not match, because this is not that class.
 * The original is kept as `getPrevious()`, and every *PSR-level* catch matches, which is the level
 * the generated `@throws` names.
 *
 * The classification the client made is preserved rather than flattened: a client that reported a
 * network failure produces {@see NetworkException}, one that reported a bad request produces {@see
 * RequestException}, and one that classified neither produces {@see TransportFailedException}.
 * Retry logic keys on exactly that distinction.
 *
 * `getRequest()` is declared here for the same reason `ResponseException` declares its accessors: a
 * caller who catches this type can always ask what was being sent. The PSR sub-interfaces declare
 * the identical method on two of the three, and the third would otherwise be the one case where the
 * question has no answer — even though the request is in hand at every throw site.
 */
interface TransportException extends ApiException, ClientExceptionInterface
{
    /**
     * The request that did not complete.
     *
     * Taken from the client's own exception where it reported one — a middleware may have rewritten
     * the request on the way out, and its copy is the one that actually went to the wire — and
     * otherwise the request this package handed over.
     */
    public function getRequest(): RequestInterface;
}
