<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Prefabcortex\UpsTimeInTransit\Http\ErrorMessage;
use Psr\Http\Message\ResponseInterface;
use RuntimeException;

final class UnexpectedContentTypeException extends RuntimeException implements ResponseException
{
    public function __construct(private readonly ResponseInterface $response, private readonly string $rawResponse)
    {
        parent::__construct(
            ErrorMessage::describeContentType(
                $rawResponse,
                $response->getStatusCode(),
                $response->getHeaderLine('Content-Type'),
            ),
            $response->getStatusCode(),
        );
    }

    #[Override]
    public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    public function getRawResponse(): string
    {
        return $this->rawResponse;
    }
}
