<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

/**
 * A 4xx the operation has no reading for. {@see UnexpectedStatusCodeException}.
 */
final class UnexpectedClientErrorException extends UnexpectedStatusCodeException implements ClientException
{
}
