<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use Override;
use Prefabcortex\UpsTimeInTransit\Http\ErrorMessage;
use Psr\Http\Message\ResponseInterface;
use RuntimeException;
use Throwable;

use function sprintf;

/**
 * A response the operation has no reading for: a status no response declares, or an error response
 * whose body does not read as the description declares it.
 *
 * What is raised is one of three subclasses, by the status HTTP gives the response: a 4xx is a
 * {@see ClientException}, a 5xx a {@see ServerException}, anything else neither. The description
 * may not know the status, but HTTP does (RFC 9110 §15), and `catch (ClientException)` is where a
 * caller looks for a 401 or a 429, declared or not.
 *
 * `catch (UnexpectedStatusCodeException)` catches all three.
 */
abstract class UnexpectedStatusCodeException extends RuntimeException implements ResponseException
{
    /** @param Throwable ...$previous at most one: what kept a declared error body from being read */
    final public function __construct(
        private readonly ResponseInterface $response,
        private readonly string $rawResponse,
        string $message,
        Throwable ...$previous,
    ) {
        parent::__construct($message, $response->getStatusCode(), $previous[0] ?? null);
    }

    /**
     * For a status no response of the operation declares.
     */
    final public static function of(ResponseInterface $response, string $rawResponse): self
    {
        return self::byStatus(
            $response,
            $rawResponse,
            ErrorMessage::describeStatus($rawResponse, $response->getStatusCode()),
        );
    }

    /**
     * For an error response the description declares, whose body does not read as it declares it.
     *
     * The status is what the caller needs first: the request failed, and a 404 whose problem
     * document has a `status` of the wrong type is still a 404 — a {@see ClientException}, which is
     * where a handler written for a failed request looks. The reason the body was not read is
     * `getPrevious()`.
     */
    final public static function ofUnreadableBody(
        ResponseInterface $response,
        string $rawResponse,
        Throwable $cause,
    ): self {
        return self::byStatus(
            $response,
            $rawResponse,
            sprintf(
                '%s — the body does not read as the description declares it; see getPrevious().',
                ErrorMessage::describeStatus($rawResponse, $response->getStatusCode()),
            ),
            $cause,
        );
    }

    #[Override]
    final public function getResponse(): ResponseInterface
    {
        return $this->response;
    }

    #[Override]
    final public function getRawResponse(): string
    {
        return $this->rawResponse;
    }

    private static function byStatus(
        ResponseInterface $response,
        string $rawResponse,
        string $message,
        Throwable ...$previous,
    ): self {
        $status = $response->getStatusCode();

        return match (true) {
            $status >= 500 => new UnexpectedServerErrorException($response, $rawResponse, $message, ...$previous),
            $status >= 400 => new UnexpectedClientErrorException($response, $rawResponse, $message, ...$previous),
            default => new UnexpectedNonErrorStatusException($response, $rawResponse, $message, ...$previous),
        };
    }
}
