<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

/**
 * A status below 400 the operation has no reading for — a `204` where `200` is declared, a redirect
 * the HTTP client did not follow. {@see UnexpectedStatusCodeException}.
 */
final class UnexpectedNonErrorStatusException extends UnexpectedStatusCodeException
{
}
