<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Exception;

use InvalidArgumentException;

/**
 * A value handed to the package that it cannot put on the wire.
 *
 * Every place that asks this question asks it before a request is sent: a base URI that names no
 * scheme and no host and could therefore address no server, a query parameter holding something
 * with no query-string form, a multipart field holding something that is not a form part, an API
 * key that no cookie value can carry, an authenticator for a scheme no operation requires. They
 * differ in when the caller supplied the value, not in what went wrong with it — so they are one
 * type, and a consumer who wants to tell them apart reads the message rather than catching another
 * class.
 *
 * Extends `InvalidArgumentException`, so a `catch` of the SPL type matches it, and carries the
 * marker. The root is not interchangeable with the one {@see MalformedDataException} uses:
 * `InvalidArgumentException` descends from `LogicException` and `UnexpectedValueException` from
 * `RuntimeException`, and the split is the honest line between the two. This one says the caller
 * passed something wrong — knowable before anything is sent, fixable in their code.
 * `MalformedDataException` says a document was not what its description promised, which is only
 * knowable once it arrives.
 *
 * It is an {@see ApiException} and not a `ResponseException` for the same reason {@see
 * NoHttpClientException} is not: nothing has been sent, so there is no response to hand back.
 */
final class UnsupportedValueException extends InvalidArgumentException implements ApiException
{
}
