<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Parameter;

use Prefabcortex\UpsTimeInTransit\Http\HeaderParameter;
use Prefabcortex\UpsTimeInTransit\Http\HeaderParameters;
use Prefabcortex\UpsTimeInTransit\Http\ScalarValue;

final readonly class TimeInTransitHeaderParameters
{
    /**
     * @param string $transId        An identifier unique to the request. Length 32
     * @param string $transactionSrc Identifies the clients/source application that is calling.
     *                               Length 512
     */
    public function __construct(private string $transId, private string $transactionSrc)
    {
    }

    public function getTransId(): string
    {
        return $this->transId;
    }

    public function getTransactionSrc(): string
    {
        return $this->transactionSrc;
    }

    /**
     * @internal called by the generated operation, not part of this package's public
     *                  contract: it may change in any release
     */
    public function toHeaderParameters(): HeaderParameters
    {
        $parameters = [];
        $parameters[] = new HeaderParameter('transId', new ScalarValue($this->transId));
        $parameters[] = new HeaderParameter('transactionSrc', new ScalarValue($this->transactionSrc));

        return new HeaderParameters(...$parameters);
    }
}
