<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit;

use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;
use Prefabcortex\UpsTimeInTransit\Http\ServerSelection;
use Prefabcortex\UpsTimeInTransit\Http\ServerUrl;
use Prefabcortex\UpsTimeInTransit\Http\Timeout;
use Prefabcortex\UpsTimeInTransit\Http\ValidationMode;
use Prefabcortex\UpsTimeInTransit\Optional\None;
use Prefabcortex\UpsTimeInTransit\Optional\Option;
use Prefabcortex\UpsTimeInTransit\Optional\Some;
use Psr\Http\Client\ClientInterface;

final readonly class ClientConfig
{
    /**
     * Which server each operation goes to.
     *
     * @internal plumbing of the generated package, not part of its public contract: only the
     *                    generated operations and client touch this, and it may change in any release
     */
    public ServerSelection $servers;
    /** @var Option<ClientInterface> */
    public Option $httpClient;
    public Timeout $timeout;
    public ValidationMode $validation;

    /** @param Option<ClientInterface> $httpClient */
    private function __construct(
        ServerSelection $servers,
        Option $httpClient,
        Timeout $timeout,
        ValidationMode $validation,
    ) {
        $this->servers = $servers;
        $this->httpClient = $httpClient;
        $this->timeout = $timeout;
        $this->validation = $validation;
    }

    /**
     * A configuration for one of the servers the API description names.
     *
     * Each is named after what the description says of it, and their order means nothing: pick the
     * one your credentials belong to.
     */
    public static function forServer(Server $server): self
    {
        return new self(self::selection($server), None::create(), Timeout::defaults(), ValidationMode::Lax);
    }

    /**
     * Every request to one address — a mock server, a proxy, a recorded fixture — including the
     * operations the description sends to servers of their own. Scheme and host included:
     * `https://api.example.com/v2`; each operation's path is appended to it.
     */
    public static function forBaseUrl(string $baseUrl): self
    {
        return new self(
            ServerSelection::everywhere($baseUrl),
            None::create(),
            Timeout::defaults(),
            ValidationMode::Lax,
        );
    }

    public function withHttpClient(ClientInterface $httpClient): self
    {
        return new self($this->servers, Some::create($httpClient), $this->timeout, $this->validation);
    }

    /**
     * How long a request may take: `Timeout::seconds(30)`, or `Timeout::of($connect, $total)`.
     *
     * The default is ten seconds to connect and sixty in all. It applies to the HTTP client this
     * package finds by itself; one handed over through `withHttpClient()` keeps its own.
     */
    public function withTimeout(Timeout $timeout): self
    {
        return new self($this->servers, $this->httpClient, $timeout, $this->validation);
    }

    /**
     * How closely requests and responses are held to the API description. `Lax` is the default.
     *
     * API descriptions are wrong often enough — a length nothing has, a range that was never one —
     * and APIs send what their description rules out. So `Lax` skips the constraints in both
     * directions: a request is sent as its models hold it, a response is read as far as its model
     * can hold it, and an enum value no case names reads as `UnknownEnumValue`.
     *
     * `Strict` is for an API that keeps to its description. It checks every constraint the
     * description declares: a request that breaks one raises `ValidationException` and is not sent,
     * a response that breaks one raises `ResponseValidationException`.
     *
     * What a typed model needs in order to exist (the type of a property, a required property) is
     * checked either way.
     */
    public function withValidation(ValidationMode $validation): self
    {
        return new self($this->servers, $this->httpClient, $this->timeout, $validation);
    }

    /**
     * A URL the description gives relative to its server — an OAuth token endpoint — resolved
     * against the chosen server as RFC 3986 resolves a reference: `/oauth/token` keeps only its
     * scheme and host.
     *
     * @throws UnsupportedValueException when the chosen server cannot address one
     */
    public function resolveUrl(string $reference): string
    {
        return $this->servers->resolve(ServerSelection::ROOT, $reference);
    }

    private static function selection(Server $server): ServerSelection
    {
        return ServerSelection::serving(self::serverUrl($server));
    }

    private static function serverUrl(Server $server): ServerUrl
    {
        return match ($server) {
            Server::CustomerIntegrationEnvironment => ServerUrl::of('https://wwwcie.ups.com/api'),
            Server::Production => ServerUrl::of('https://onlinetools.ups.com/api'),
        };
    }
}
