<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit;

use Nyholm\Psr7\Factory\Psr17Factory;
use Prefabcortex\UpsTimeInTransit\Authentication\Authenticator;
use Prefabcortex\UpsTimeInTransit\Authentication\AuthenticatorRegistry;
use Prefabcortex\UpsTimeInTransit\Exception\ApiException;
use Prefabcortex\UpsTimeInTransit\Exception\MalformedResponseException;
use Prefabcortex\UpsTimeInTransit\Exception\NoHttpClientException;
use Prefabcortex\UpsTimeInTransit\Exception\ResponseValidationException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitBadRequestException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitForbiddenException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitTooManyRequestsException;
use Prefabcortex\UpsTimeInTransit\Exception\TimeInTransitUnauthorizedException;
use Prefabcortex\UpsTimeInTransit\Exception\TransportException;
use Prefabcortex\UpsTimeInTransit\Exception\UnexpectedContentTypeException;
use Prefabcortex\UpsTimeInTransit\Exception\UnexpectedStatusCodeException;
use Prefabcortex\UpsTimeInTransit\Exception\UnsupportedValueException;
use Prefabcortex\UpsTimeInTransit\Http\ClientTrait;
use Prefabcortex\UpsTimeInTransit\Http\HttpClientResolver;
use Prefabcortex\UpsTimeInTransit\Model\TimeInTransitRequest;
use Prefabcortex\UpsTimeInTransit\Model\TimeInTransitResponse;
use Prefabcortex\UpsTimeInTransit\Operation\TimeInTransit;
use Prefabcortex\UpsTimeInTransit\Parameter\TimeInTransitHeaderParameters;
use Psr\Http\Message\ResponseInterface;
use SensitiveParameter;

use function array_values;

final class Client
{
    use ClientTrait;

    /**
     * @param string $version API Version
     *
     * @throws ApiException
     * @throws UnsupportedValueException
     * @throws TransportException
     * @throws ResponseValidationException
     * @throws MalformedResponseException
     * @throws TimeInTransitBadRequestException
     * @throws TimeInTransitUnauthorizedException
     * @throws TimeInTransitForbiddenException
     * @throws TimeInTransitTooManyRequestsException
     * @throws UnexpectedContentTypeException
     * @throws UnexpectedStatusCodeException
     */
    public function timeInTransit(
        string $version,
        TimeInTransitRequest $requestBody,
        TimeInTransitHeaderParameters $headerParameters,
    ): TimeInTransitResponse {
        return $this->executeOperation(new TimeInTransit($version, $requestBody, $headerParameters));
    }

    /**
     * @param string $version API Version
     *
     * @throws ApiException
     * @throws UnsupportedValueException
     * @throws TransportException
     */
    public function timeInTransitRaw(
        string $version,
        TimeInTransitRequest $requestBody,
        TimeInTransitHeaderParameters $headerParameters,
    ): ResponseInterface {
        return $this->executeRawOperation(new TimeInTransit($version, $requestBody, $headerParameters));
    }

    /**
     * @throws UnsupportedValueException
     * @throws NoHttpClientException
     */
    public static function withOAuth(#[SensitiveParameter] string $token, ClientConfig $config): self
    {
        return self::withAuthenticators($config, new Authentication\OAuth2Authentication($token));
    }

    /**
     * A client signing with authenticators you assemble yourself.
     *
     * Every other factory on this class is a shorthand for this one. Reach for it directly for a
     * scheme this package generates no authenticator for: implement `Authentication\Authenticator`
     * under the scheme's name and pass it. A request is signed by the authenticators for the
     * schemes its operation requires; one for a scheme no operation requires is refused. To sign
     * every request your own way, pass an HTTP client that does so to
     * `ClientConfig::withHttpClient()`.
     *
     * Note the argument order: `$config` comes first, because the authenticators are variadic and
     * have to come last.
     *
     * @throws UnsupportedValueException
     * @throws NoHttpClientException
     */
    public static function withAuthenticators(ClientConfig $config, Authenticator ...$authenticators): self
    {
        $factory = new Psr17Factory();
        $httpClient = $config->httpClient->isDefined() ? $config->httpClient->get() : HttpClientResolver::resolve(
            $factory,
            $factory,
            $config->timeout,
        );

        return new self(
            $config->servers,
            $httpClient,
            $factory,
            $factory,
            new AuthenticatorRegistry(array_values($authenticators), ['OAuth2']),
            $config->validation,
        );
    }

    /**
     * A client that signs nothing.
     *
     * For operations the description leaves without a security requirement, and for callers whose
     * own HTTP client already authenticates — see `ClientConfig::withHttpClient()`. A request whose
     * requirements no registered authenticator satisfies goes out unsigned, which is the point here
     * and a mistake anywhere else: to send credentials, use one of the `with…()` factories above,
     * or `withAuthenticators()` for a scheme they do not cover.
     *
     * @throws UnsupportedValueException
     * @throws NoHttpClientException
     */
    public static function create(ClientConfig $config): self
    {
        return self::withAuthenticators($config);
    }
}
