<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit;

/**
 * The servers the API description names, for `ClientConfig::forServer()`.
 *
 * Each is named after what the description says of it, and their order means nothing: pick the one
 * your credentials belong to.
 */
enum Server
{
    /**
     * Customer Integration Environment.
     *
     * `https://wwwcie.ups.com/api`
     */
    case CustomerIntegrationEnvironment;
    /**
     * Production.
     *
     * `https://onlinetools.ups.com/api`
     */
    case Production;
}
