<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Symfony\Component\Validator\Constraint;

/**
 * Part of the package's public contract: every generated `…Constraint` class implements it, and its
 * `constraints()` is how a caller gets the rules of a model to validate data against.
 */
interface ConstraintProviderInterface
{
    /** @return list<Constraint> */
    public static function constraints(): array;
}
