<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Override;
use Prefabcortex\UpsTimeInTransit\Model\EmsResponse;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see EmsResponse} has to satisfy.
 */
final class EmsResponseConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'shipDate' => new Required([
                    new Length(null, 10),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'shipTime' => new Required([new Type(['string']), new NotNull()]),
                'serviceLevel' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'billType' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'dutyType' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'residentialIndicator' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationCountryName' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationCountryCode' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationPostalCode' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationPostalCodeLow' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationPostalCodeHigh' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationStateProvince' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationCityName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originCountryName' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originCountryCode' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originPostalCode' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originPostalCodeLow' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originPostalCodeHigh' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originStateProvince' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originCityName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'weight' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'weightUnitOfMeasure' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'shipmentContentsValue' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 11),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'shipmentContentsCurrencyCode' => new Optional([
                    new Length(null, 3),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'guaranteeSuspended' => new Required([new Type(['bool']), new NotNull()]),
                'numberOfServices' => new Required([new Type(['integer']), new NotNull()]),
                'services' => new Optional([
                    new All([...ServicesConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
