<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Override;
use Prefabcortex\UpsTimeInTransit\Model\Errors;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Errors} has to satisfy.
 */
final class ErrorsConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'code' => new Optional([new Type(['string']), new NotNull()]),
                'message' => new Optional([new Type(['string']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
