<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Override;
use Prefabcortex\UpsTimeInTransit\Model\Services;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see Services} has to satisfy.
 */
final class ServicesConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'serviceLevel' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'serviceLevelDescription' => new Required([new Type(['string']), new NotNull()]),
                'shipDate' => new Required([
                    new Length(null, 10),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'deliveryDate' => new Required([
                    new Length(null, 10),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'commitTime' => new Required([
                    new Length(null, 8),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'deliveryTime' => new Required([
                    new Length(null, 8),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'deliveryDayOfWeek' => new Required([
                    new Length(null, 3),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'nextDayPickupIndicator' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 1),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'saturdayPickupIndicator' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 1),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'saturdayDeliveryDate' => new Optional([
                    new Length(null, 10),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'saturdayDeliveryTime' => new Optional([
                    new Length(null, 8),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'serviceRemarksText' => new Optional([new Type(['string']), new NotNull()]),
                'guaranteeIndicator' => new Required([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 1),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'totalTransitDays' => new Required([new Type(['integer']), new NotNull()]),
                'businessTransitDays' => new Required([new Type(['integer']), new NotNull()]),
                'restDaysCount' => new Required([new Type(['integer']), new NotNull()]),
                'holidayCount' => new Required([new Type(['integer']), new NotNull()]),
                'delayCount' => new Required([new Type(['integer']), new NotNull()]),
                'pickupDate' => new Required([
                    new Length(null, 10),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'pickupTime' => new Required([
                    new Length(null, 8),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'cstccutoffTime' => new Required([
                    new Length(null, 8),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'poddate' => new Optional([
                    new Length(null, 10),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'poddays' => new Optional([new Type(['integer']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
