<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Override;
use Prefabcortex\UpsTimeInTransit\Model\TimeInTransitResponse;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TimeInTransitResponse} has to satisfy.
 */
final class TimeInTransitResponseConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'validationList' => new Optional([new NotNull(), ...ValidationListConstraint::constraints()]),
                'destinationPickList' => new Optional([
                    new All([...CandidateAddressConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'originPickList' => new Optional([
                    new All([...CandidateAddressConstraint::constraints()]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'emsResponse' => new Optional([new NotNull(), ...EmsResponseConstraint::constraints()]),
            ], null, null, true),
        ];
    }
}
