<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Override;
use Prefabcortex\UpsTimeInTransit\Model\TimeInTransitRequest;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\LessThanOrEqual;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Required;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see TimeInTransitRequest} has to satisfy.
 */
final class TimeInTransitRequestConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'originCountryCode' => new Required([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originStateProvince' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originCityName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originTownName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'originPostalCode' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationCountryCode' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationStateProvince' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationCityName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationTownName' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 50),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'destinationPostalCode' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'residentialIndicator' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'shipDate' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 10),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'shipTime' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 8),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'weight' => new Optional([new Type(['number']), new NotNull()]),
                'weightUnitOfMeasure' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'shipmentContentsValue' => new Optional([new Type(['number']), new NotNull()]),
                'shipmentContentsCurrencyCode' => new Optional([
                    new Length(null, 1),
                    new NotBlank(null, null, null),
                    new Length(null, null, 3),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'billType' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
                'avvFlag' => new Optional([new Type(['bool']), new NotNull()]),
                'numberOfPackages' => new Optional([new Type(['integer']), new NotNull()]),
                'dropOffAtFacilityIndicator' => new Optional([
                    new LessThanOrEqual(1.0),
                    new Type(['integer']),
                    new NotNull(),
                ]),
                'holdForPickupIndicator' => new Optional([
                    new LessThanOrEqual(1.0),
                    new Type(['integer']),
                    new NotNull(),
                ]),
                'returnUnfilterdServices' => new Optional([new Type(['bool']), new NotNull()]),
                'maxList' => new Optional([new Type(['integer']), new NotNull()]),
                'premierIndicator' => new Optional([
                    new Length(null, 2),
                    new NotBlank(null, null, null),
                    new Length(null, null, 2),
                    new Type(['string']),
                    new NotNull(),
                ]),
            ], null, null, true),
        ];
    }
}
