<?php

/**
 * @generated by prefabcortex/openapi-php-generator
 *
 * Regenerating replaces this file, so a change made here by hand does not survive it.
 */
declare(strict_types=1);

namespace Prefabcortex\UpsTimeInTransit\Validator;

use Override;
use Prefabcortex\UpsTimeInTransit\Model\ValidationList;
use Symfony\Component\Validator\Constraints\All;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotNull;
use Symfony\Component\Validator\Constraints\Optional;
use Symfony\Component\Validator\Constraints\Type;

/**
 * The rules a document for {@see ValidationList} has to satisfy.
 */
final class ValidationListConstraint implements ConstraintProviderInterface
{
    #[Override]
    public static function constraints(): array
    {
        return [
            new NotNull(),
            new Collection([
                'invalidFieldList' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'invalidFieldListCodes' => new Optional([
                    new All([new Type(['string'])]),
                    new Type(['array']),
                    new NotNull(),
                ]),
                'destinationAmbiguous' => new Optional([new Type(['bool']), new NotNull()]),
                'originAmbiguous' => new Optional([new Type(['bool']), new NotNull()]),
            ], null, null, true),
        ];
    }
}
